apiVersion: stable.snowflake.m.crossplane.io/v1alpha1
kind: OnExternalTable
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/onexternaltable
  labels:
    testing.upbound.io/example-name: stream
  name: stream
  namespace: crossplane-system
spec:
  forProvider:
    database: database
    externalTable: ${snowflake_external_table.example.fully_qualified_name}
    schema: schema
