apiVersion: stable.snowflake.m.crossplane.io/v1alpha1
kind: PrivilegesToShare
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/privilegestoshare
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    onDatabase: ${snowflake_database.example.name}
    privileges:
    - USAGE

---

apiVersion: stable.snowflake.m.crossplane.io/v1alpha1
kind: Database
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/privilegestoshare
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider: {}
