apiVersion: stable.snowflake.m.crossplane.io/v1alpha1
kind: PrivilegesToAccountRole
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/privilegestoaccountrole
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    accountRoleName: ${snowflake_account_role.db_role.name}
    onAccount: true
    privileges:
    - CREATE DATABASE
    - CREATE USER

---

apiVersion: stable.snowflake.m.crossplane.io/v1alpha1
kind: AccountRole
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/privilegestoaccountrole
  labels:
    testing.upbound.io/example-name: db_role
  name: db-role
  namespace: crossplane-system
spec:
  forProvider: {}

---

apiVersion: stable.snowflake.m.crossplane.io/v1alpha1
kind: Database
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/privilegestoaccountrole
  labels:
    testing.upbound.io/example-name: db
  name: db
  namespace: crossplane-system
spec:
  forProvider: {}

---

apiVersion: stable.snowflake.m.crossplane.io/v1alpha1
kind: Schema
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/privilegestoaccountrole
  labels:
    testing.upbound.io/example-name: my_schema
  name: my-schema
  namespace: crossplane-system
spec:
  forProvider:
    database: database
