apiVersion: stable.snowflake.m.crossplane.io/v1alpha1
kind: PrivilegesToDatabaseRole
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/privilegestodatabaserole
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    databaseRoleName: ${snowflake_database_role.db_role.fully_qualified_name}
    onDatabase: ${snowflake_database.test_database.fully_qualified_name}
    privileges:
    - CREATE
    - MONITOR

---

apiVersion: stable.snowflake.m.crossplane.io/v1alpha1
kind: Database
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/privilegestodatabaserole
  labels:
    testing.upbound.io/example-name: db
  name: db
  namespace: crossplane-system
spec:
  forProvider: {}

---

apiVersion: stable.snowflake.m.crossplane.io/v1alpha1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/privilegestodatabaserole
  labels:
    testing.upbound.io/example-name: db_role
  name: db-role
  namespace: crossplane-system
spec:
  forProvider:
    database: database

---

apiVersion: stable.snowflake.m.crossplane.io/v1alpha1
kind: Schema
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/privilegestodatabaserole
  labels:
    testing.upbound.io/example-name: my_schema
  name: my-schema
  namespace: crossplane-system
spec:
  forProvider:
    database: database
