apiVersion: stable.snowflake.m.crossplane.io/v1alpha1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/role
  labels:
    testing.upbound.io/example-name: test_database_role
  name: test-database-role
  namespace: crossplane-system
spec:
  forProvider:
    comment: my database role
    database: ${snowflake_database.test_database.fully_qualified_name}

---

apiVersion: stable.snowflake.m.crossplane.io/v1alpha1
kind: Database
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/role
  labels:
    testing.upbound.io/example-name: test_database
  name: test-database
  namespace: crossplane-system
spec:
  forProvider: {}
