// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ApiIntegrationAzureApiManagementDescribeOutputInitParameters struct {
}

type ApiIntegrationAzureApiManagementDescribeOutputObservation struct {

	// (String)
	APIProvider *string `json:"apiProvider,omitempty" tf:"api_provider,omitempty"`

	// (List of String)
	AllowedPrefixes []*string `json:"allowedPrefixes,omitempty" tf:"allowed_prefixes,omitempty"`

	// (String) The 'Application (client) ID' of the Azure AD app for your Azure API Management instance.
	AzureAdApplicationID *string `json:"azureAdApplicationId,omitempty" tf:"azure_ad_application_id,omitempty"`

	// (String)
	AzureConsentURL *string `json:"azureConsentUrl,omitempty" tf:"azure_consent_url,omitempty"`

	// (String)
	AzureMultiTenantAppName *string `json:"azureMultiTenantAppName,omitempty" tf:"azure_multi_tenant_app_name,omitempty"`

	// (String) Specifies the ID for your Office 365 tenant that all Azure API Management instances belong to.
	AzureTenantID *string `json:"azureTenantId,omitempty" tf:"azure_tenant_id,omitempty"`

	// (List of String)
	BlockedPrefixes []*string `json:"blockedPrefixes,omitempty" tf:"blocked_prefixes,omitempty"`

	// (String) Specifies a comment for the integration.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean) Specifies whether this API integration is enabled or disabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type ApiIntegrationAzureApiManagementDescribeOutputParameters struct {
}

type ApiIntegrationAzureApiManagementInitParameters struct {

	// (List of String) Explicitly limits external functions that use the integration to reference one or more HTTPS proxy service and remote service endpoints and resources.
	// Explicitly limits external functions that use the integration to reference one or more HTTPS proxy service and remote service endpoints and resources.
	APIAllowedPrefixes []*string `json:"apiAllowedPrefixes,omitempty" tf:"api_allowed_prefixes,omitempty"`

	// (List of String) Lists the endpoints and resources in the HTTPS proxy service that are not allowed to be called from Snowflake.
	// Lists the endpoints and resources in the HTTPS proxy service that are not allowed to be called from Snowflake.
	APIBlockedPrefixes []*string `json:"apiBlockedPrefixes,omitempty" tf:"api_blocked_prefixes,omitempty"`

	// Specifies the API key (secret) that Snowflake uses to authenticate when making calls to the proxy service. Snowflake returns a masked value for this field in DESCRIBE output, so external changes to it cannot be detected. External changes for this field won't be detected.
	APIKeySecretRef *v2.SecretKeySelector `json:"apiKeySecretRef,omitempty" tf:"-"`

	// (String) The 'Application (client) ID' of the Azure AD app for your Azure API Management instance.
	// The 'Application (client) ID' of the Azure AD app for your Azure API Management instance.
	AzureAdApplicationID *string `json:"azureAdApplicationId,omitempty" tf:"azure_ad_application_id,omitempty"`

	// (String) Specifies the ID for your Office 365 tenant that all Azure API Management instances belong to.
	// Specifies the ID for your Office 365 tenant that all Azure API Management instances belong to.
	AzureTenantID *string `json:"azureTenantId,omitempty" tf:"azure_tenant_id,omitempty"`

	// (String) Specifies a comment for the integration.
	// Specifies a comment for the integration.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean) Specifies whether this API integration is enabled or disabled.
	// Specifies whether this API integration is enabled or disabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type ApiIntegrationAzureApiManagementObservation struct {

	// (List of String) Explicitly limits external functions that use the integration to reference one or more HTTPS proxy service and remote service endpoints and resources.
	// Explicitly limits external functions that use the integration to reference one or more HTTPS proxy service and remote service endpoints and resources.
	APIAllowedPrefixes []*string `json:"apiAllowedPrefixes,omitempty" tf:"api_allowed_prefixes,omitempty"`

	// (List of String) Lists the endpoints and resources in the HTTPS proxy service that are not allowed to be called from Snowflake.
	// Lists the endpoints and resources in the HTTPS proxy service that are not allowed to be called from Snowflake.
	APIBlockedPrefixes []*string `json:"apiBlockedPrefixes,omitempty" tf:"api_blocked_prefixes,omitempty"`

	// (String) The 'Application (client) ID' of the Azure AD app for your Azure API Management instance.
	// The 'Application (client) ID' of the Azure AD app for your Azure API Management instance.
	AzureAdApplicationID *string `json:"azureAdApplicationId,omitempty" tf:"azure_ad_application_id,omitempty"`

	// (String) Specifies the ID for your Office 365 tenant that all Azure API Management instances belong to.
	// Specifies the ID for your Office 365 tenant that all Azure API Management instances belong to.
	AzureTenantID *string `json:"azureTenantId,omitempty" tf:"azure_tenant_id,omitempty"`

	// (String) Specifies a comment for the integration.
	// Specifies a comment for the integration.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (List of Object) Outputs the result of DESCRIBE API INTEGRATION for the given integration. (see below for nested schema)
	// Outputs the result of `DESCRIBE API INTEGRATION` for the given integration.
	DescribeOutput []ApiIntegrationAzureApiManagementDescribeOutputObservation `json:"describeOutput,omitempty" tf:"describe_output,omitempty"`

	// (Boolean) Specifies whether this API integration is enabled or disabled.
	// Specifies whether this API integration is enabled or disabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Fully qualified name of the resource. For more information, see object name resolution.
	// Fully qualified name of the resource. For more information, see [object name resolution](https://docs.snowflake.com/en/sql-reference/name-resolution).
	FullyQualifiedName *string `json:"fullyQualifiedName,omitempty" tf:"fully_qualified_name,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (List of Object) Outputs the result of SHOW API INTEGRATIONS for the given integration. (see below for nested schema)
	// Outputs the result of `SHOW API INTEGRATIONS` for the given integration.
	ShowOutput []ApiIntegrationAzureApiManagementShowOutputObservation `json:"showOutput,omitempty" tf:"show_output,omitempty"`
}

type ApiIntegrationAzureApiManagementParameters struct {

	// (List of String) Explicitly limits external functions that use the integration to reference one or more HTTPS proxy service and remote service endpoints and resources.
	// Explicitly limits external functions that use the integration to reference one or more HTTPS proxy service and remote service endpoints and resources.
	// +kubebuilder:validation:Optional
	APIAllowedPrefixes []*string `json:"apiAllowedPrefixes,omitempty" tf:"api_allowed_prefixes,omitempty"`

	// (List of String) Lists the endpoints and resources in the HTTPS proxy service that are not allowed to be called from Snowflake.
	// Lists the endpoints and resources in the HTTPS proxy service that are not allowed to be called from Snowflake.
	// +kubebuilder:validation:Optional
	APIBlockedPrefixes []*string `json:"apiBlockedPrefixes,omitempty" tf:"api_blocked_prefixes,omitempty"`

	// Specifies the API key (secret) that Snowflake uses to authenticate when making calls to the proxy service. Snowflake returns a masked value for this field in DESCRIBE output, so external changes to it cannot be detected. External changes for this field won't be detected.
	// +kubebuilder:validation:Optional
	APIKeySecretRef *v2.SecretKeySelector `json:"apiKeySecretRef,omitempty" tf:"-"`

	// (String) The 'Application (client) ID' of the Azure AD app for your Azure API Management instance.
	// The 'Application (client) ID' of the Azure AD app for your Azure API Management instance.
	// +kubebuilder:validation:Optional
	AzureAdApplicationID *string `json:"azureAdApplicationId,omitempty" tf:"azure_ad_application_id,omitempty"`

	// (String) Specifies the ID for your Office 365 tenant that all Azure API Management instances belong to.
	// Specifies the ID for your Office 365 tenant that all Azure API Management instances belong to.
	// +kubebuilder:validation:Optional
	AzureTenantID *string `json:"azureTenantId,omitempty" tf:"azure_tenant_id,omitempty"`

	// (String) Specifies a comment for the integration.
	// Specifies a comment for the integration.
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean) Specifies whether this API integration is enabled or disabled.
	// Specifies whether this API integration is enabled or disabled.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type ApiIntegrationAzureApiManagementShowOutputInitParameters struct {
}

type ApiIntegrationAzureApiManagementShowOutputObservation struct {

	// (String)
	APIType *string `json:"apiType,omitempty" tf:"api_type,omitempty"`

	// (String)
	Category *string `json:"category,omitempty" tf:"category,omitempty"`

	// (String) Specifies a comment for the integration.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String)
	CreatedOn *string `json:"createdOn,omitempty" tf:"created_on,omitempty"`

	// (Boolean) Specifies whether this API integration is enabled or disabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Specifies the identifier (i.e. name) for the integration. This value must be unique in your account. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type ApiIntegrationAzureApiManagementShowOutputParameters struct {
}

// ApiIntegrationAzureApiManagementSpec defines the desired state of ApiIntegrationAzureApiManagement
type ApiIntegrationAzureApiManagementSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   ApiIntegrationAzureApiManagementParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ApiIntegrationAzureApiManagementInitParameters `json:"initProvider,omitempty"`
}

// ApiIntegrationAzureApiManagementStatus defines the observed state of ApiIntegrationAzureApiManagement.
type ApiIntegrationAzureApiManagementStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ApiIntegrationAzureApiManagementObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ApiIntegrationAzureApiManagement is the Schema for the ApiIntegrationAzureApiManagements API. Resource used to manage API integration Azure API Management objects. For more information, check api integration documentation https://docs.snowflake.com/en/sql-reference/sql/create-api-integration.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,snowflake}
type ApiIntegrationAzureApiManagement struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.apiAllowedPrefixes) || (has(self.initProvider) && has(self.initProvider.apiAllowedPrefixes))",message="spec.forProvider.apiAllowedPrefixes is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.azureAdApplicationId) || (has(self.initProvider) && has(self.initProvider.azureAdApplicationId))",message="spec.forProvider.azureAdApplicationId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.azureTenantId) || (has(self.initProvider) && has(self.initProvider.azureTenantId))",message="spec.forProvider.azureTenantId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.enabled) || (has(self.initProvider) && has(self.initProvider.enabled))",message="spec.forProvider.enabled is a required parameter"
	Spec   ApiIntegrationAzureApiManagementSpec   `json:"spec"`
	Status ApiIntegrationAzureApiManagementStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ApiIntegrationAzureApiManagementList contains a list of ApiIntegrationAzureApiManagements
type ApiIntegrationAzureApiManagementList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ApiIntegrationAzureApiManagement `json:"items"`
}

// Repository type metadata.
var (
	ApiIntegrationAzureApiManagement_Kind             = "ApiIntegrationAzureApiManagement"
	ApiIntegrationAzureApiManagement_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ApiIntegrationAzureApiManagement_Kind}.String()
	ApiIntegrationAzureApiManagement_KindAPIVersion   = ApiIntegrationAzureApiManagement_Kind + "." + CRDGroupVersion.String()
	ApiIntegrationAzureApiManagement_GroupVersionKind = CRDGroupVersion.WithKind(ApiIntegrationAzureApiManagement_Kind)
)

func init() {
	SchemeBuilder.Register(&ApiIntegrationAzureApiManagement{}, &ApiIntegrationAzureApiManagementList{})
}
