// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type EmailNotificationIntegrationInitParameters struct {

	// (Set of String) List of email addresses that should receive notifications.
	// List of email addresses that should receive notifications.
	// +listType=set
	AllowedRecipients []*string `json:"allowedRecipients,omitempty" tf:"allowed_recipients,omitempty"`

	// (String) A comment for the email integration.
	// A comment for the email integration.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean)
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type EmailNotificationIntegrationObservation struct {

	// (Set of String) List of email addresses that should receive notifications.
	// List of email addresses that should receive notifications.
	// +listType=set
	AllowedRecipients []*string `json:"allowedRecipients,omitempty" tf:"allowed_recipients,omitempty"`

	// (String) A comment for the email integration.
	// A comment for the email integration.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean)
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Fully qualified name of the resource. For more information, see object name resolution.
	// Fully qualified name of the resource. For more information, see [object name resolution](https://docs.snowflake.com/en/sql-reference/name-resolution).
	FullyQualifiedName *string `json:"fullyQualifiedName,omitempty" tf:"fully_qualified_name,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type EmailNotificationIntegrationParameters struct {

	// (Set of String) List of email addresses that should receive notifications.
	// List of email addresses that should receive notifications.
	// +kubebuilder:validation:Optional
	// +listType=set
	AllowedRecipients []*string `json:"allowedRecipients,omitempty" tf:"allowed_recipients,omitempty"`

	// (String) A comment for the email integration.
	// A comment for the email integration.
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

// EmailNotificationIntegrationSpec defines the desired state of EmailNotificationIntegration
type EmailNotificationIntegrationSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   EmailNotificationIntegrationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider EmailNotificationIntegrationInitParameters `json:"initProvider,omitempty"`
}

// EmailNotificationIntegrationStatus defines the observed state of EmailNotificationIntegration.
type EmailNotificationIntegrationStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               EmailNotificationIntegrationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// EmailNotificationIntegration is the Schema for the EmailNotificationIntegrations API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,snowflake}
type EmailNotificationIntegration struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.enabled) || (has(self.initProvider) && has(self.initProvider.enabled))",message="spec.forProvider.enabled is a required parameter"
	Spec   EmailNotificationIntegrationSpec   `json:"spec"`
	Status EmailNotificationIntegrationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// EmailNotificationIntegrationList contains a list of EmailNotificationIntegrations
type EmailNotificationIntegrationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []EmailNotificationIntegration `json:"items"`
}

// Repository type metadata.
var (
	EmailNotificationIntegration_Kind             = "EmailNotificationIntegration"
	EmailNotificationIntegration_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: EmailNotificationIntegration_Kind}.String()
	EmailNotificationIntegration_KindAPIVersion   = EmailNotificationIntegration_Kind + "." + CRDGroupVersion.String()
	EmailNotificationIntegration_GroupVersionKind = CRDGroupVersion.WithKind(EmailNotificationIntegration_Kind)
)

func init() {
	SchemeBuilder.Register(&EmailNotificationIntegration{}, &EmailNotificationIntegrationList{})
}
