// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type PostgresInstanceDescribeOutputInitParameters struct {
}

type PostgresInstanceDescribeOutputObservation struct {

	// insensitive): POSTGRES | POSTGRES_OR_SNOWFLAKE.
	AuthenticationAuthority *string `json:"authenticationAuthority,omitempty" tf:"authentication_authority,omitempty"`

	// (String) Specifies a comment for the Postgres instance.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// insensitive): STANDARD_M | STANDARD_L | STANDARD_XL | STANDARD_2XL | STANDARD_4XL | STANDARD_8XL | STANDARD_12XL | STANDARD_24XL | HIGHMEM_L | HIGHMEM_XL | HIGHMEM_2XL | HIGHMEM_4XL | HIGHMEM_8XL | HIGHMEM_12XL | HIGHMEM_16XL | HIGHMEM_24XL | HIGHMEM_32XL | HIGHMEM_48XL | BURST_XS | BURST_S | BURST_M.
	ComputeFamily *string `json:"computeFamily,omitempty" tf:"compute_family,omitempty"`

	// (String)
	CreatedOn *string `json:"createdOn,omitempty" tf:"created_on,omitempty"`

	// uses special value that cannot be set in the configuration manually (default)) Specifies whether the Postgres instance should be configured for high availability. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	HighAvailability *bool `json:"highAvailability,omitempty" tf:"high_availability,omitempty"`

	// (String)
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// uses special value that cannot be set in the configuration manually (-1)) Specifies the hour (0-23 UTC) at which the maintenance window starts.
	MaintenanceWindowStart *int64 `json:"maintenanceWindowStart,omitempty" tf:"maintenance_window_start,omitempty"`

	// (String) Specifies the identifier for the Postgres instance; must be unique for your account. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Specifies the network policy to associate with the Postgres instance.
	NetworkPolicy *string `json:"networkPolicy,omitempty" tf:"network_policy,omitempty"`

	// (String)
	Origin *string `json:"origin,omitempty" tf:"origin,omitempty"`

	// (String)
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// (String)
	OwnerRoleType *string `json:"ownerRoleType,omitempty" tf:"owner_role_type,omitempty"`

	// (String) Specifies custom Postgres settings as a JSON string.
	PostgresSettings *string `json:"postgresSettings,omitempty" tf:"postgres_settings,omitempty"`

	// (Number) Specifies the Postgres version for the instance. Note that Snowflake does not allow downgrading; the version can only be upgraded.
	PostgresVersion *int64 `json:"postgresVersion,omitempty" tf:"postgres_version,omitempty"`

	// (String)
	PrivatelinkServiceIdentifier *string `json:"privatelinkServiceIdentifier,omitempty" tf:"privatelink_service_identifier,omitempty"`

	// (Number)
	RetentionTime *int64 `json:"retentionTime,omitempty" tf:"retention_time,omitempty"`

	// (String)
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// (String) Specifies the storage integration for the Postgres instance.
	StorageIntegration *string `json:"storageIntegration,omitempty" tf:"storage_integration,omitempty"`

	// (Number) Specifies the storage size in GB for the Postgres instance.
	StorageSizeGb *int64 `json:"storageSizeGb,omitempty" tf:"storage_size_gb,omitempty"`

	// (String)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String)
	UpdatedOn *string `json:"updatedOn,omitempty" tf:"updated_on,omitempty"`
}

type PostgresInstanceDescribeOutputParameters struct {
}

type PostgresInstanceInitParameters struct {

	// insensitive): POSTGRES | POSTGRES_OR_SNOWFLAKE.
	// Specifies the authentication authority for the Postgres instance. Valid values are (case-insensitive): `POSTGRES` | `POSTGRES_OR_SNOWFLAKE`.
	AuthenticationAuthority *string `json:"authenticationAuthority,omitempty" tf:"authentication_authority,omitempty"`

	// (String) Specifies a comment for the Postgres instance.
	// Specifies a comment for the Postgres instance.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// insensitive): STANDARD_M | STANDARD_L | STANDARD_XL | STANDARD_2XL | STANDARD_4XL | STANDARD_8XL | STANDARD_12XL | STANDARD_24XL | HIGHMEM_L | HIGHMEM_XL | HIGHMEM_2XL | HIGHMEM_4XL | HIGHMEM_8XL | HIGHMEM_12XL | HIGHMEM_16XL | HIGHMEM_24XL | HIGHMEM_32XL | HIGHMEM_48XL | BURST_XS | BURST_S | BURST_M.
	// Specifies the compute family for the Postgres instance. Valid values are (case-insensitive): `STANDARD_M` | `STANDARD_L` | `STANDARD_XL` | `STANDARD_2XL` | `STANDARD_4XL` | `STANDARD_8XL` | `STANDARD_12XL` | `STANDARD_24XL` | `HIGHMEM_L` | `HIGHMEM_XL` | `HIGHMEM_2XL` | `HIGHMEM_4XL` | `HIGHMEM_8XL` | `HIGHMEM_12XL` | `HIGHMEM_16XL` | `HIGHMEM_24XL` | `HIGHMEM_32XL` | `HIGHMEM_48XL` | `BURST_XS` | `BURST_S` | `BURST_M`.
	ComputeFamily *string `json:"computeFamily,omitempty" tf:"compute_family,omitempty"`

	// uses special value that cannot be set in the configuration manually (default)) Specifies whether the Postgres instance should be configured for high availability. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	// Specifies whether the Postgres instance should be configured for high availability. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	HighAvailability *string `json:"highAvailability,omitempty" tf:"high_availability,omitempty"`

	// uses special value that cannot be set in the configuration manually (-1)) Specifies the hour (0-23 UTC) at which the maintenance window starts.
	// Specifies the hour (0-23 UTC) at which the maintenance window starts.
	MaintenanceWindowStart *int64 `json:"maintenanceWindowStart,omitempty" tf:"maintenance_window_start,omitempty"`

	// (String) Specifies the network policy to associate with the Postgres instance.
	// Specifies the network policy to associate with the Postgres instance.
	NetworkPolicy *string `json:"networkPolicy,omitempty" tf:"network_policy,omitempty"`

	// (String) Specifies custom Postgres settings as a JSON string.
	// Specifies custom Postgres settings as a JSON string.
	PostgresSettings *string `json:"postgresSettings,omitempty" tf:"postgres_settings,omitempty"`

	// (Number) Specifies the Postgres version for the instance. Note that Snowflake does not allow downgrading; the version can only be upgraded.
	// Specifies the Postgres version for the instance. Note that Snowflake does not allow downgrading; the version can only be upgraded.
	PostgresVersion *int64 `json:"postgresVersion,omitempty" tf:"postgres_version,omitempty"`

	// (String) Specifies the storage integration for the Postgres instance.
	// Specifies the storage integration for the Postgres instance.
	StorageIntegration *string `json:"storageIntegration,omitempty" tf:"storage_integration,omitempty"`

	// (Number) Specifies the storage size in GB for the Postgres instance.
	// Specifies the storage size in GB for the Postgres instance.
	StorageSizeGb *int64 `json:"storageSizeGb,omitempty" tf:"storage_size_gb,omitempty"`
}

type PostgresInstanceObservation struct {

	// insensitive): POSTGRES | POSTGRES_OR_SNOWFLAKE.
	// Specifies the authentication authority for the Postgres instance. Valid values are (case-insensitive): `POSTGRES` | `POSTGRES_OR_SNOWFLAKE`.
	AuthenticationAuthority *string `json:"authenticationAuthority,omitempty" tf:"authentication_authority,omitempty"`

	// (String) Specifies a comment for the Postgres instance.
	// Specifies a comment for the Postgres instance.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// insensitive): STANDARD_M | STANDARD_L | STANDARD_XL | STANDARD_2XL | STANDARD_4XL | STANDARD_8XL | STANDARD_12XL | STANDARD_24XL | HIGHMEM_L | HIGHMEM_XL | HIGHMEM_2XL | HIGHMEM_4XL | HIGHMEM_8XL | HIGHMEM_12XL | HIGHMEM_16XL | HIGHMEM_24XL | HIGHMEM_32XL | HIGHMEM_48XL | BURST_XS | BURST_S | BURST_M.
	// Specifies the compute family for the Postgres instance. Valid values are (case-insensitive): `STANDARD_M` | `STANDARD_L` | `STANDARD_XL` | `STANDARD_2XL` | `STANDARD_4XL` | `STANDARD_8XL` | `STANDARD_12XL` | `STANDARD_24XL` | `HIGHMEM_L` | `HIGHMEM_XL` | `HIGHMEM_2XL` | `HIGHMEM_4XL` | `HIGHMEM_8XL` | `HIGHMEM_12XL` | `HIGHMEM_16XL` | `HIGHMEM_24XL` | `HIGHMEM_32XL` | `HIGHMEM_48XL` | `BURST_XS` | `BURST_S` | `BURST_M`.
	ComputeFamily *string `json:"computeFamily,omitempty" tf:"compute_family,omitempty"`

	// (List of Object) Outputs the result of DESCRIBE POSTGRES INSTANCE for the given Postgres instance. (see below for nested schema)
	// Outputs the result of `DESCRIBE POSTGRES INSTANCE` for the given Postgres instance.
	DescribeOutput []PostgresInstanceDescribeOutputObservation `json:"describeOutput,omitempty" tf:"describe_output,omitempty"`

	// (String) Fully qualified name of the resource. For more information, see object name resolution.
	// Fully qualified name of the resource. For more information, see [object name resolution](https://docs.snowflake.com/en/sql-reference/name-resolution).
	FullyQualifiedName *string `json:"fullyQualifiedName,omitempty" tf:"fully_qualified_name,omitempty"`

	// uses special value that cannot be set in the configuration manually (default)) Specifies whether the Postgres instance should be configured for high availability. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	// Specifies whether the Postgres instance should be configured for high availability. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	HighAvailability *string `json:"highAvailability,omitempty" tf:"high_availability,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// uses special value that cannot be set in the configuration manually (-1)) Specifies the hour (0-23 UTC) at which the maintenance window starts.
	// Specifies the hour (0-23 UTC) at which the maintenance window starts.
	MaintenanceWindowStart *int64 `json:"maintenanceWindowStart,omitempty" tf:"maintenance_window_start,omitempty"`

	// (String) Specifies the network policy to associate with the Postgres instance.
	// Specifies the network policy to associate with the Postgres instance.
	NetworkPolicy *string `json:"networkPolicy,omitempty" tf:"network_policy,omitempty"`

	// (String) Specifies custom Postgres settings as a JSON string.
	// Specifies custom Postgres settings as a JSON string.
	PostgresSettings *string `json:"postgresSettings,omitempty" tf:"postgres_settings,omitempty"`

	// (Number) Specifies the Postgres version for the instance. Note that Snowflake does not allow downgrading; the version can only be upgraded.
	// Specifies the Postgres version for the instance. Note that Snowflake does not allow downgrading; the version can only be upgraded.
	PostgresVersion *int64 `json:"postgresVersion,omitempty" tf:"postgres_version,omitempty"`

	// (List of Object) Outputs the result of SHOW POSTGRES INSTANCES for the given Postgres instance. (see below for nested schema)
	// Outputs the result of `SHOW POSTGRES INSTANCES` for the given Postgres instance.
	ShowOutput []PostgresInstanceShowOutputObservation `json:"showOutput,omitempty" tf:"show_output,omitempty"`

	// (String) Specifies the storage integration for the Postgres instance.
	// Specifies the storage integration for the Postgres instance.
	StorageIntegration *string `json:"storageIntegration,omitempty" tf:"storage_integration,omitempty"`

	// (Number) Specifies the storage size in GB for the Postgres instance.
	// Specifies the storage size in GB for the Postgres instance.
	StorageSizeGb *int64 `json:"storageSizeGb,omitempty" tf:"storage_size_gb,omitempty"`
}

type PostgresInstanceParameters struct {

	// insensitive): POSTGRES | POSTGRES_OR_SNOWFLAKE.
	// Specifies the authentication authority for the Postgres instance. Valid values are (case-insensitive): `POSTGRES` | `POSTGRES_OR_SNOWFLAKE`.
	// +kubebuilder:validation:Optional
	AuthenticationAuthority *string `json:"authenticationAuthority,omitempty" tf:"authentication_authority,omitempty"`

	// (String) Specifies a comment for the Postgres instance.
	// Specifies a comment for the Postgres instance.
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// insensitive): STANDARD_M | STANDARD_L | STANDARD_XL | STANDARD_2XL | STANDARD_4XL | STANDARD_8XL | STANDARD_12XL | STANDARD_24XL | HIGHMEM_L | HIGHMEM_XL | HIGHMEM_2XL | HIGHMEM_4XL | HIGHMEM_8XL | HIGHMEM_12XL | HIGHMEM_16XL | HIGHMEM_24XL | HIGHMEM_32XL | HIGHMEM_48XL | BURST_XS | BURST_S | BURST_M.
	// Specifies the compute family for the Postgres instance. Valid values are (case-insensitive): `STANDARD_M` | `STANDARD_L` | `STANDARD_XL` | `STANDARD_2XL` | `STANDARD_4XL` | `STANDARD_8XL` | `STANDARD_12XL` | `STANDARD_24XL` | `HIGHMEM_L` | `HIGHMEM_XL` | `HIGHMEM_2XL` | `HIGHMEM_4XL` | `HIGHMEM_8XL` | `HIGHMEM_12XL` | `HIGHMEM_16XL` | `HIGHMEM_24XL` | `HIGHMEM_32XL` | `HIGHMEM_48XL` | `BURST_XS` | `BURST_S` | `BURST_M`.
	// +kubebuilder:validation:Optional
	ComputeFamily *string `json:"computeFamily,omitempty" tf:"compute_family,omitempty"`

	// uses special value that cannot be set in the configuration manually (default)) Specifies whether the Postgres instance should be configured for high availability. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	// Specifies whether the Postgres instance should be configured for high availability. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	// +kubebuilder:validation:Optional
	HighAvailability *string `json:"highAvailability,omitempty" tf:"high_availability,omitempty"`

	// uses special value that cannot be set in the configuration manually (-1)) Specifies the hour (0-23 UTC) at which the maintenance window starts.
	// Specifies the hour (0-23 UTC) at which the maintenance window starts.
	// +kubebuilder:validation:Optional
	MaintenanceWindowStart *int64 `json:"maintenanceWindowStart,omitempty" tf:"maintenance_window_start,omitempty"`

	// (String) Specifies the network policy to associate with the Postgres instance.
	// Specifies the network policy to associate with the Postgres instance.
	// +kubebuilder:validation:Optional
	NetworkPolicy *string `json:"networkPolicy,omitempty" tf:"network_policy,omitempty"`

	// (String) Specifies custom Postgres settings as a JSON string.
	// Specifies custom Postgres settings as a JSON string.
	// +kubebuilder:validation:Optional
	PostgresSettings *string `json:"postgresSettings,omitempty" tf:"postgres_settings,omitempty"`

	// (Number) Specifies the Postgres version for the instance. Note that Snowflake does not allow downgrading; the version can only be upgraded.
	// Specifies the Postgres version for the instance. Note that Snowflake does not allow downgrading; the version can only be upgraded.
	// +kubebuilder:validation:Optional
	PostgresVersion *int64 `json:"postgresVersion,omitempty" tf:"postgres_version,omitempty"`

	// (String) Specifies the storage integration for the Postgres instance.
	// Specifies the storage integration for the Postgres instance.
	// +kubebuilder:validation:Optional
	StorageIntegration *string `json:"storageIntegration,omitempty" tf:"storage_integration,omitempty"`

	// (Number) Specifies the storage size in GB for the Postgres instance.
	// Specifies the storage size in GB for the Postgres instance.
	// +kubebuilder:validation:Optional
	StorageSizeGb *int64 `json:"storageSizeGb,omitempty" tf:"storage_size_gb,omitempty"`
}

type PostgresInstanceShowOutputInitParameters struct {
}

type PostgresInstanceShowOutputObservation struct {

	// insensitive): POSTGRES | POSTGRES_OR_SNOWFLAKE.
	AuthenticationAuthority *string `json:"authenticationAuthority,omitempty" tf:"authentication_authority,omitempty"`

	// (String) Specifies a comment for the Postgres instance.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// insensitive): STANDARD_M | STANDARD_L | STANDARD_XL | STANDARD_2XL | STANDARD_4XL | STANDARD_8XL | STANDARD_12XL | STANDARD_24XL | HIGHMEM_L | HIGHMEM_XL | HIGHMEM_2XL | HIGHMEM_4XL | HIGHMEM_8XL | HIGHMEM_12XL | HIGHMEM_16XL | HIGHMEM_24XL | HIGHMEM_32XL | HIGHMEM_48XL | BURST_XS | BURST_S | BURST_M.
	ComputeFamily *string `json:"computeFamily,omitempty" tf:"compute_family,omitempty"`

	// (String)
	CreatedOn *string `json:"createdOn,omitempty" tf:"created_on,omitempty"`

	// (String)
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// (Boolean)
	IsHa *bool `json:"isHa,omitempty" tf:"is_ha,omitempty"`

	// (String) Specifies the identifier for the Postgres instance; must be unique for your account. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	Origin *string `json:"origin,omitempty" tf:"origin,omitempty"`

	// (String)
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// (String)
	OwnerRoleType *string `json:"ownerRoleType,omitempty" tf:"owner_role_type,omitempty"`

	// (String) Specifies custom Postgres settings as a JSON string.
	PostgresSettings *string `json:"postgresSettings,omitempty" tf:"postgres_settings,omitempty"`

	// (Number) Specifies the Postgres version for the instance. Note that Snowflake does not allow downgrading; the version can only be upgraded.
	PostgresVersion *string `json:"postgresVersion,omitempty" tf:"postgres_version,omitempty"`

	// (String)
	PrivatelinkServiceIdentifier *string `json:"privatelinkServiceIdentifier,omitempty" tf:"privatelink_service_identifier,omitempty"`

	// (Number)
	RetentionTime *int64 `json:"retentionTime,omitempty" tf:"retention_time,omitempty"`

	// (String)
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// (Number)
	StorageSize *int64 `json:"storageSize,omitempty" tf:"storage_size,omitempty"`

	// (String)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String)
	UpdatedOn *string `json:"updatedOn,omitempty" tf:"updated_on,omitempty"`
}

type PostgresInstanceShowOutputParameters struct {
}

// PostgresInstanceSpec defines the desired state of PostgresInstance
type PostgresInstanceSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PostgresInstanceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PostgresInstanceInitParameters `json:"initProvider,omitempty"`
}

// PostgresInstanceStatus defines the observed state of PostgresInstance.
type PostgresInstanceStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PostgresInstanceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// PostgresInstance is the Schema for the PostgresInstances API. Resource used to manage Postgres instance objects. For more information, check Postgres instance documentation https://docs.snowflake.com/en/sql-reference/sql/create-postgres-instance.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,snowflake}
type PostgresInstance struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.authenticationAuthority) || (has(self.initProvider) && has(self.initProvider.authenticationAuthority))",message="spec.forProvider.authenticationAuthority is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.computeFamily) || (has(self.initProvider) && has(self.initProvider.computeFamily))",message="spec.forProvider.computeFamily is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.postgresVersion) || (has(self.initProvider) && has(self.initProvider.postgresVersion))",message="spec.forProvider.postgresVersion is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.storageSizeGb) || (has(self.initProvider) && has(self.initProvider.storageSizeGb))",message="spec.forProvider.storageSizeGb is a required parameter"
	Spec   PostgresInstanceSpec   `json:"spec"`
	Status PostgresInstanceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PostgresInstanceList contains a list of PostgresInstances
type PostgresInstanceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PostgresInstance `json:"items"`
}

// Repository type metadata.
var (
	PostgresInstance_Kind             = "PostgresInstance"
	PostgresInstance_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PostgresInstance_Kind}.String()
	PostgresInstance_KindAPIVersion   = PostgresInstance_Kind + "." + CRDGroupVersion.String()
	PostgresInstance_GroupVersionKind = CRDGroupVersion.WithKind(PostgresInstance_Kind)
)

func init() {
	SchemeBuilder.Register(&PostgresInstance{}, &PostgresInstanceList{})
}
