// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ProcedureJavascriptArgumentsInitParameters struct {

	// (String) The argument type.
	// The argument type.
	ArgDataType *string `json:"argDataType,omitempty" tf:"arg_data_type,omitempty"`

	// Optional default value for the argument. For text values use single quotes. Numeric values can be unquoted. External changes for this field won't be detected.
	ArgDefaultValue *string `json:"argDefaultValue,omitempty" tf:"arg_default_value,omitempty"`

	// (String) The argument name. The provider wraps it in double quotes by default, so be aware of that while referencing the argument in the procedure definition.
	// The argument name. The provider wraps it in double quotes by default, so be aware of that while referencing the argument in the procedure definition.
	ArgName *string `json:"argName,omitempty" tf:"arg_name,omitempty"`
}

type ProcedureJavascriptArgumentsObservation struct {

	// (String) The argument type.
	// The argument type.
	ArgDataType *string `json:"argDataType,omitempty" tf:"arg_data_type,omitempty"`

	// Optional default value for the argument. For text values use single quotes. Numeric values can be unquoted. External changes for this field won't be detected.
	ArgDefaultValue *string `json:"argDefaultValue,omitempty" tf:"arg_default_value,omitempty"`

	// (String) The argument name. The provider wraps it in double quotes by default, so be aware of that while referencing the argument in the procedure definition.
	// The argument name. The provider wraps it in double quotes by default, so be aware of that while referencing the argument in the procedure definition.
	ArgName *string `json:"argName,omitempty" tf:"arg_name,omitempty"`
}

type ProcedureJavascriptArgumentsParameters struct {

	// (String) The argument type.
	// The argument type.
	// +kubebuilder:validation:Optional
	ArgDataType *string `json:"argDataType" tf:"arg_data_type,omitempty"`

	// Optional default value for the argument. For text values use single quotes. Numeric values can be unquoted. External changes for this field won't be detected.
	// +kubebuilder:validation:Optional
	ArgDefaultValue *string `json:"argDefaultValue,omitempty" tf:"arg_default_value,omitempty"`

	// (String) The argument name. The provider wraps it in double quotes by default, so be aware of that while referencing the argument in the procedure definition.
	// The argument name. The provider wraps it in double quotes by default, so be aware of that while referencing the argument in the procedure definition.
	// +kubebuilder:validation:Optional
	ArgName *string `json:"argName" tf:"arg_name,omitempty"`
}

type ProcedureJavascriptInitParameters struct {

	// (Block List) List of the arguments for the procedure. Consult the docs for more details. (see below for nested schema)
	// List of the arguments for the procedure. Consult the [docs](https://docs.snowflake.com/en/sql-reference/sql/create-procedure#all-languages) for more details.
	Arguments []ProcedureJavascriptArgumentsInitParameters `json:"arguments,omitempty" tf:"arguments,omitempty"`

	// defined procedure) Specifies a comment for the procedure.
	// (Default: `user-defined procedure`) Specifies a comment for the procedure.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) The database in which to create the procedure. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The database in which to create the procedure. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// (Boolean) Enable stdout/stderr fast path logging for anonyous stored procs. This is a public parameter (similar to LOG_LEVEL). For more information, check ENABLE_CONSOLE_OUTPUT docs.
	// Enable stdout/stderr fast path logging for anonyous stored procs. This is a public parameter (similar to LOG_LEVEL). For more information, check [ENABLE_CONSOLE_OUTPUT docs](https://docs.snowflake.com/en/sql-reference/parameters#enable-console-output).
	EnableConsoleOutput *bool `json:"enableConsoleOutput,omitempty" tf:"enable_console_output,omitempty"`

	// insensitive): CALLER | OWNER.
	// Specifies whether the stored procedure executes with the privileges of the owner (an “owner’s rights” stored procedure) or with the privileges of the caller (a “caller’s rights” stored procedure). If you execute the statement CREATE PROCEDURE … EXECUTE AS CALLER, then in the future the procedure will execute as a caller’s rights procedure. If you execute CREATE PROCEDURE … EXECUTE AS OWNER, then the procedure will execute as an owner’s rights procedure. For more information, see [Understanding caller’s rights and owner’s rights stored procedures](https://docs.snowflake.com/en/developer-guide/stored-procedure/stored-procedures-rights). Valid values are (case-insensitive): `CALLER` | `OWNER`.
	ExecuteAs *string `json:"executeAs,omitempty" tf:"execute_as,omitempty"`

	// uses special value that cannot be set in the configuration manually (default)) Specifies that the procedure is secure. For more information about secure procedures, see Protecting Sensitive Information with Secure UDFs and Stored Procedures. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	// (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`default`)) Specifies that the procedure is secure. For more information about secure procedures, see [Protecting Sensitive Information with Secure UDFs and Stored Procedures](https://docs.snowflake.com/en/developer-guide/secure-udf-procedure). Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	IsSecure *string `json:"isSecure,omitempty" tf:"is_secure,omitempty"`

	// insensitive): TRACE | DEBUG | INFO | WARN | ERROR | FATAL | OFF. For more information, check LOG_EVENT_LEVEL docs.
	// Specifies the severity level of log events (rows with record type EVENT) that should be ingested and made available in the active event table. Log events at the specified level (and at more severe levels) are ingested. For more information, see [LOG_EVENT_LEVEL](https://docs.snowflake.com/en/sql-reference/parameters#log_event_level). Valid values are (case-insensitive): `TRACE` | `DEBUG` | `INFO` | `WARN` | `ERROR` | `FATAL` | `OFF`. For more information, check [LOG_EVENT_LEVEL docs](https://docs.snowflake.com/en/sql-reference/parameters#log-event-level).
	LogEventLevel *string `json:"logEventLevel,omitempty" tf:"log_event_level,omitempty"`

	// (String) LOG_LEVEL to use when filtering events For more information, check LOG_LEVEL docs.
	// LOG_LEVEL to use when filtering events For more information, check [LOG_LEVEL docs](https://docs.snowflake.com/en/sql-reference/parameters#log-level).
	LogLevel *string `json:"logLevel,omitempty" tf:"log_level,omitempty"`

	// (String) METRIC_LEVEL value to control whether to emit metrics to Event Table For more information, check METRIC_LEVEL docs.
	// METRIC_LEVEL value to control whether to emit metrics to Event Table For more information, check [METRIC_LEVEL docs](https://docs.snowflake.com/en/sql-reference/parameters#metric-level).
	MetricLevel *string `json:"metricLevel,omitempty" tf:"metric_level,omitempty"`

	// (String) The name of the procedure; the identifier does not need to be unique for the schema in which the procedure is created because stored procedures are identified and resolved by the combination of the name and argument types. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The name of the procedure; the identifier does not need to be unique for the schema in which the procedure is created because stored procedures are [identified and resolved by the combination of the name and argument types](https://docs.snowflake.com/en/developer-guide/udf-stored-procedure-naming-conventions.html#label-procedure-function-name-overloading). Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// insensitive): CALLED ON NULL INPUT | RETURNS NULL ON NULL INPUT.
	// Specifies the behavior of the procedure when called with null inputs. Valid values are (case-insensitive): `CALLED ON NULL INPUT` | `RETURNS NULL ON NULL INPUT`.
	NullInputBehavior *string `json:"nullInputBehavior,omitempty" tf:"null_input_behavior,omitempty"`

	// (String) Defines the code executed by the stored procedure. The definition can consist of any valid code. Wrapping $$ signs are added by the provider automatically; do not include them. The procedure_definition value must be JavaScript source code. For more information, see JavaScript. To mitigate permadiff on this field, the provider replaces blank characters with a space. This can lead to false positives in cases where a change in case or run of whitespace is semantically significant.
	// Defines the code executed by the stored procedure. The definition can consist of any valid code. Wrapping `$$` signs are added by the provider automatically; do not include them. The `procedure_definition` value must be JavaScript source code. For more information, see [JavaScript](https://docs.snowflake.com/en/developer-guide/stored-procedure/stored-procedures-javascript). To mitigate permadiff on this field, the provider replaces blank characters with a space. This can lead to false positives in cases where a change in case or run of whitespace is semantically significant.
	ProcedureDefinition *string `json:"procedureDefinition,omitempty" tf:"procedure_definition,omitempty"`

	// (String) Specifies the type of the result returned by the stored procedure. For <result_data_type>, use the Snowflake data type that corresponds to the type of the language that you are using (see SQL and JavaScript data type mapping). For RETURNS TABLE ( [ col_name col_data_type [ , ... ] ] ), if you know the Snowflake data types of the columns in the returned table, specify the column names and types. Otherwise (e.g. if you are determining the column types during run time), you can omit the column names and types (i.e. TABLE ()).
	// Specifies the type of the result returned by the stored procedure. For `<result_data_type>`, use the Snowflake data type that corresponds to the type of the language that you are using (see [SQL and JavaScript data type mapping](https://docs.snowflake.com/en/developer-guide/stored-procedure/stored-procedures-javascript.html#label-stored-procedure-data-type-mapping)). For `RETURNS TABLE ( [ col_name col_data_type [ , ... ] ] )`, if you know the Snowflake data types of the columns in the returned table, specify the column names and types. Otherwise (e.g. if you are determining the column types during run time), you can omit the column names and types (i.e. `TABLE ()`).
	ReturnType *string `json:"returnType,omitempty" tf:"return_type,omitempty"`

	// (String) The schema in which to create the procedure. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The schema in which to create the procedure. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// (String) Trace level value to use when generating/filtering trace events For more information, check TRACE_LEVEL docs.
	// Trace level value to use when generating/filtering trace events For more information, check [TRACE_LEVEL docs](https://docs.snowflake.com/en/sql-reference/parameters#trace-level).
	TraceLevel *string `json:"traceLevel,omitempty" tf:"trace_level,omitempty"`
}

type ProcedureJavascriptObservation struct {

	// (Block List) List of the arguments for the procedure. Consult the docs for more details. (see below for nested schema)
	// List of the arguments for the procedure. Consult the [docs](https://docs.snowflake.com/en/sql-reference/sql/create-procedure#all-languages) for more details.
	Arguments []ProcedureJavascriptArgumentsObservation `json:"arguments,omitempty" tf:"arguments,omitempty"`

	// defined procedure) Specifies a comment for the procedure.
	// (Default: `user-defined procedure`) Specifies a comment for the procedure.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) The database in which to create the procedure. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The database in which to create the procedure. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// (Boolean) Enable stdout/stderr fast path logging for anonyous stored procs. This is a public parameter (similar to LOG_LEVEL). For more information, check ENABLE_CONSOLE_OUTPUT docs.
	// Enable stdout/stderr fast path logging for anonyous stored procs. This is a public parameter (similar to LOG_LEVEL). For more information, check [ENABLE_CONSOLE_OUTPUT docs](https://docs.snowflake.com/en/sql-reference/parameters#enable-console-output).
	EnableConsoleOutput *bool `json:"enableConsoleOutput,omitempty" tf:"enable_console_output,omitempty"`

	// insensitive): CALLER | OWNER.
	// Specifies whether the stored procedure executes with the privileges of the owner (an “owner’s rights” stored procedure) or with the privileges of the caller (a “caller’s rights” stored procedure). If you execute the statement CREATE PROCEDURE … EXECUTE AS CALLER, then in the future the procedure will execute as a caller’s rights procedure. If you execute CREATE PROCEDURE … EXECUTE AS OWNER, then the procedure will execute as an owner’s rights procedure. For more information, see [Understanding caller’s rights and owner’s rights stored procedures](https://docs.snowflake.com/en/developer-guide/stored-procedure/stored-procedures-rights). Valid values are (case-insensitive): `CALLER` | `OWNER`.
	ExecuteAs *string `json:"executeAs,omitempty" tf:"execute_as,omitempty"`

	// (String) Fully qualified name of the resource. For more information, see object name resolution.
	// Fully qualified name of the resource. For more information, see [object name resolution](https://docs.snowflake.com/en/sql-reference/name-resolution).
	FullyQualifiedName *string `json:"fullyQualifiedName,omitempty" tf:"fully_qualified_name,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// uses special value that cannot be set in the configuration manually (default)) Specifies that the procedure is secure. For more information about secure procedures, see Protecting Sensitive Information with Secure UDFs and Stored Procedures. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	// (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`default`)) Specifies that the procedure is secure. For more information about secure procedures, see [Protecting Sensitive Information with Secure UDFs and Stored Procedures](https://docs.snowflake.com/en/developer-guide/secure-udf-procedure). Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	IsSecure *string `json:"isSecure,omitempty" tf:"is_secure,omitempty"`

	// insensitive): TRACE | DEBUG | INFO | WARN | ERROR | FATAL | OFF. For more information, check LOG_EVENT_LEVEL docs.
	// Specifies the severity level of log events (rows with record type EVENT) that should be ingested and made available in the active event table. Log events at the specified level (and at more severe levels) are ingested. For more information, see [LOG_EVENT_LEVEL](https://docs.snowflake.com/en/sql-reference/parameters#log_event_level). Valid values are (case-insensitive): `TRACE` | `DEBUG` | `INFO` | `WARN` | `ERROR` | `FATAL` | `OFF`. For more information, check [LOG_EVENT_LEVEL docs](https://docs.snowflake.com/en/sql-reference/parameters#log-event-level).
	LogEventLevel *string `json:"logEventLevel,omitempty" tf:"log_event_level,omitempty"`

	// (String) LOG_LEVEL to use when filtering events For more information, check LOG_LEVEL docs.
	// LOG_LEVEL to use when filtering events For more information, check [LOG_LEVEL docs](https://docs.snowflake.com/en/sql-reference/parameters#log-level).
	LogLevel *string `json:"logLevel,omitempty" tf:"log_level,omitempty"`

	// (String) METRIC_LEVEL value to control whether to emit metrics to Event Table For more information, check METRIC_LEVEL docs.
	// METRIC_LEVEL value to control whether to emit metrics to Event Table For more information, check [METRIC_LEVEL docs](https://docs.snowflake.com/en/sql-reference/parameters#metric-level).
	MetricLevel *string `json:"metricLevel,omitempty" tf:"metric_level,omitempty"`

	// (String) The name of the procedure; the identifier does not need to be unique for the schema in which the procedure is created because stored procedures are identified and resolved by the combination of the name and argument types. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The name of the procedure; the identifier does not need to be unique for the schema in which the procedure is created because stored procedures are [identified and resolved by the combination of the name and argument types](https://docs.snowflake.com/en/developer-guide/udf-stored-procedure-naming-conventions.html#label-procedure-function-name-overloading). Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// insensitive): CALLED ON NULL INPUT | RETURNS NULL ON NULL INPUT.
	// Specifies the behavior of the procedure when called with null inputs. Valid values are (case-insensitive): `CALLED ON NULL INPUT` | `RETURNS NULL ON NULL INPUT`.
	NullInputBehavior *string `json:"nullInputBehavior,omitempty" tf:"null_input_behavior,omitempty"`

	// (List of Object) Outputs the result of SHOW PARAMETERS IN PROCEDURE for the given procedure. (see below for nested schema)
	// Outputs the result of `SHOW PARAMETERS IN PROCEDURE` for the given procedure.
	Parameters []ProcedureJavascriptParametersObservation `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// (String) Defines the code executed by the stored procedure. The definition can consist of any valid code. Wrapping $$ signs are added by the provider automatically; do not include them. The procedure_definition value must be JavaScript source code. For more information, see JavaScript. To mitigate permadiff on this field, the provider replaces blank characters with a space. This can lead to false positives in cases where a change in case or run of whitespace is semantically significant.
	// Defines the code executed by the stored procedure. The definition can consist of any valid code. Wrapping `$$` signs are added by the provider automatically; do not include them. The `procedure_definition` value must be JavaScript source code. For more information, see [JavaScript](https://docs.snowflake.com/en/developer-guide/stored-procedure/stored-procedures-javascript). To mitigate permadiff on this field, the provider replaces blank characters with a space. This can lead to false positives in cases where a change in case or run of whitespace is semantically significant.
	ProcedureDefinition *string `json:"procedureDefinition,omitempty" tf:"procedure_definition,omitempty"`

	// (String) Specifies language for the procedure. Used to detect external changes.
	// Specifies language for the procedure. Used to detect external changes.
	ProcedureLanguage *string `json:"procedureLanguage,omitempty" tf:"procedure_language,omitempty"`

	// (String) Specifies the type of the result returned by the stored procedure. For <result_data_type>, use the Snowflake data type that corresponds to the type of the language that you are using (see SQL and JavaScript data type mapping). For RETURNS TABLE ( [ col_name col_data_type [ , ... ] ] ), if you know the Snowflake data types of the columns in the returned table, specify the column names and types. Otherwise (e.g. if you are determining the column types during run time), you can omit the column names and types (i.e. TABLE ()).
	// Specifies the type of the result returned by the stored procedure. For `<result_data_type>`, use the Snowflake data type that corresponds to the type of the language that you are using (see [SQL and JavaScript data type mapping](https://docs.snowflake.com/en/developer-guide/stored-procedure/stored-procedures-javascript.html#label-stored-procedure-data-type-mapping)). For `RETURNS TABLE ( [ col_name col_data_type [ , ... ] ] )`, if you know the Snowflake data types of the columns in the returned table, specify the column names and types. Otherwise (e.g. if you are determining the column types during run time), you can omit the column names and types (i.e. `TABLE ()`).
	ReturnType *string `json:"returnType,omitempty" tf:"return_type,omitempty"`

	// (String) The schema in which to create the procedure. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The schema in which to create the procedure. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// (List of Object) Outputs the result of SHOW PROCEDURE for the given procedure. (see below for nested schema)
	// Outputs the result of `SHOW PROCEDURE` for the given procedure.
	ShowOutput []ProcedureJavascriptShowOutputObservation `json:"showOutput,omitempty" tf:"show_output,omitempty"`

	// (String) Trace level value to use when generating/filtering trace events For more information, check TRACE_LEVEL docs.
	// Trace level value to use when generating/filtering trace events For more information, check [TRACE_LEVEL docs](https://docs.snowflake.com/en/sql-reference/parameters#trace-level).
	TraceLevel *string `json:"traceLevel,omitempty" tf:"trace_level,omitempty"`
}

type ProcedureJavascriptParameters struct {

	// (Block List) List of the arguments for the procedure. Consult the docs for more details. (see below for nested schema)
	// List of the arguments for the procedure. Consult the [docs](https://docs.snowflake.com/en/sql-reference/sql/create-procedure#all-languages) for more details.
	// +kubebuilder:validation:Optional
	Arguments []ProcedureJavascriptArgumentsParameters `json:"arguments,omitempty" tf:"arguments,omitempty"`

	// defined procedure) Specifies a comment for the procedure.
	// (Default: `user-defined procedure`) Specifies a comment for the procedure.
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) The database in which to create the procedure. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The database in which to create the procedure. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	// +kubebuilder:validation:Optional
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// (Boolean) Enable stdout/stderr fast path logging for anonyous stored procs. This is a public parameter (similar to LOG_LEVEL). For more information, check ENABLE_CONSOLE_OUTPUT docs.
	// Enable stdout/stderr fast path logging for anonyous stored procs. This is a public parameter (similar to LOG_LEVEL). For more information, check [ENABLE_CONSOLE_OUTPUT docs](https://docs.snowflake.com/en/sql-reference/parameters#enable-console-output).
	// +kubebuilder:validation:Optional
	EnableConsoleOutput *bool `json:"enableConsoleOutput,omitempty" tf:"enable_console_output,omitempty"`

	// insensitive): CALLER | OWNER.
	// Specifies whether the stored procedure executes with the privileges of the owner (an “owner’s rights” stored procedure) or with the privileges of the caller (a “caller’s rights” stored procedure). If you execute the statement CREATE PROCEDURE … EXECUTE AS CALLER, then in the future the procedure will execute as a caller’s rights procedure. If you execute CREATE PROCEDURE … EXECUTE AS OWNER, then the procedure will execute as an owner’s rights procedure. For more information, see [Understanding caller’s rights and owner’s rights stored procedures](https://docs.snowflake.com/en/developer-guide/stored-procedure/stored-procedures-rights). Valid values are (case-insensitive): `CALLER` | `OWNER`.
	// +kubebuilder:validation:Optional
	ExecuteAs *string `json:"executeAs,omitempty" tf:"execute_as,omitempty"`

	// uses special value that cannot be set in the configuration manually (default)) Specifies that the procedure is secure. For more information about secure procedures, see Protecting Sensitive Information with Secure UDFs and Stored Procedures. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	// (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`default`)) Specifies that the procedure is secure. For more information about secure procedures, see [Protecting Sensitive Information with Secure UDFs and Stored Procedures](https://docs.snowflake.com/en/developer-guide/secure-udf-procedure). Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	// +kubebuilder:validation:Optional
	IsSecure *string `json:"isSecure,omitempty" tf:"is_secure,omitempty"`

	// insensitive): TRACE | DEBUG | INFO | WARN | ERROR | FATAL | OFF. For more information, check LOG_EVENT_LEVEL docs.
	// Specifies the severity level of log events (rows with record type EVENT) that should be ingested and made available in the active event table. Log events at the specified level (and at more severe levels) are ingested. For more information, see [LOG_EVENT_LEVEL](https://docs.snowflake.com/en/sql-reference/parameters#log_event_level). Valid values are (case-insensitive): `TRACE` | `DEBUG` | `INFO` | `WARN` | `ERROR` | `FATAL` | `OFF`. For more information, check [LOG_EVENT_LEVEL docs](https://docs.snowflake.com/en/sql-reference/parameters#log-event-level).
	// +kubebuilder:validation:Optional
	LogEventLevel *string `json:"logEventLevel,omitempty" tf:"log_event_level,omitempty"`

	// (String) LOG_LEVEL to use when filtering events For more information, check LOG_LEVEL docs.
	// LOG_LEVEL to use when filtering events For more information, check [LOG_LEVEL docs](https://docs.snowflake.com/en/sql-reference/parameters#log-level).
	// +kubebuilder:validation:Optional
	LogLevel *string `json:"logLevel,omitempty" tf:"log_level,omitempty"`

	// (String) METRIC_LEVEL value to control whether to emit metrics to Event Table For more information, check METRIC_LEVEL docs.
	// METRIC_LEVEL value to control whether to emit metrics to Event Table For more information, check [METRIC_LEVEL docs](https://docs.snowflake.com/en/sql-reference/parameters#metric-level).
	// +kubebuilder:validation:Optional
	MetricLevel *string `json:"metricLevel,omitempty" tf:"metric_level,omitempty"`

	// (String) The name of the procedure; the identifier does not need to be unique for the schema in which the procedure is created because stored procedures are identified and resolved by the combination of the name and argument types. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The name of the procedure; the identifier does not need to be unique for the schema in which the procedure is created because stored procedures are [identified and resolved by the combination of the name and argument types](https://docs.snowflake.com/en/developer-guide/udf-stored-procedure-naming-conventions.html#label-procedure-function-name-overloading). Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// insensitive): CALLED ON NULL INPUT | RETURNS NULL ON NULL INPUT.
	// Specifies the behavior of the procedure when called with null inputs. Valid values are (case-insensitive): `CALLED ON NULL INPUT` | `RETURNS NULL ON NULL INPUT`.
	// +kubebuilder:validation:Optional
	NullInputBehavior *string `json:"nullInputBehavior,omitempty" tf:"null_input_behavior,omitempty"`

	// (String) Defines the code executed by the stored procedure. The definition can consist of any valid code. Wrapping $$ signs are added by the provider automatically; do not include them. The procedure_definition value must be JavaScript source code. For more information, see JavaScript. To mitigate permadiff on this field, the provider replaces blank characters with a space. This can lead to false positives in cases where a change in case or run of whitespace is semantically significant.
	// Defines the code executed by the stored procedure. The definition can consist of any valid code. Wrapping `$$` signs are added by the provider automatically; do not include them. The `procedure_definition` value must be JavaScript source code. For more information, see [JavaScript](https://docs.snowflake.com/en/developer-guide/stored-procedure/stored-procedures-javascript). To mitigate permadiff on this field, the provider replaces blank characters with a space. This can lead to false positives in cases where a change in case or run of whitespace is semantically significant.
	// +kubebuilder:validation:Optional
	ProcedureDefinition *string `json:"procedureDefinition,omitempty" tf:"procedure_definition,omitempty"`

	// (String) Specifies the type of the result returned by the stored procedure. For <result_data_type>, use the Snowflake data type that corresponds to the type of the language that you are using (see SQL and JavaScript data type mapping). For RETURNS TABLE ( [ col_name col_data_type [ , ... ] ] ), if you know the Snowflake data types of the columns in the returned table, specify the column names and types. Otherwise (e.g. if you are determining the column types during run time), you can omit the column names and types (i.e. TABLE ()).
	// Specifies the type of the result returned by the stored procedure. For `<result_data_type>`, use the Snowflake data type that corresponds to the type of the language that you are using (see [SQL and JavaScript data type mapping](https://docs.snowflake.com/en/developer-guide/stored-procedure/stored-procedures-javascript.html#label-stored-procedure-data-type-mapping)). For `RETURNS TABLE ( [ col_name col_data_type [ , ... ] ] )`, if you know the Snowflake data types of the columns in the returned table, specify the column names and types. Otherwise (e.g. if you are determining the column types during run time), you can omit the column names and types (i.e. `TABLE ()`).
	// +kubebuilder:validation:Optional
	ReturnType *string `json:"returnType,omitempty" tf:"return_type,omitempty"`

	// (String) The schema in which to create the procedure. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The schema in which to create the procedure. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	// +kubebuilder:validation:Optional
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// (String) Trace level value to use when generating/filtering trace events For more information, check TRACE_LEVEL docs.
	// Trace level value to use when generating/filtering trace events For more information, check [TRACE_LEVEL docs](https://docs.snowflake.com/en/sql-reference/parameters#trace-level).
	// +kubebuilder:validation:Optional
	TraceLevel *string `json:"traceLevel,omitempty" tf:"trace_level,omitempty"`
}

type ProcedureJavascriptParametersEnableConsoleOutputInitParameters struct {
}

type ProcedureJavascriptParametersEnableConsoleOutputObservation struct {

	// (String)
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String)
	Level *string `json:"level,omitempty" tf:"level,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ProcedureJavascriptParametersEnableConsoleOutputParameters struct {
}

type ProcedureJavascriptParametersInitParameters struct {
}

type ProcedureJavascriptParametersLogEventLevelInitParameters struct {
}

type ProcedureJavascriptParametersLogEventLevelObservation struct {

	// (String)
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String)
	Level *string `json:"level,omitempty" tf:"level,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ProcedureJavascriptParametersLogEventLevelParameters struct {
}

type ProcedureJavascriptParametersLogLevelInitParameters struct {
}

type ProcedureJavascriptParametersLogLevelObservation struct {

	// (String)
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String)
	Level *string `json:"level,omitempty" tf:"level,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ProcedureJavascriptParametersLogLevelParameters struct {
}

type ProcedureJavascriptParametersMetricLevelInitParameters struct {
}

type ProcedureJavascriptParametersMetricLevelObservation struct {

	// (String)
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String)
	Level *string `json:"level,omitempty" tf:"level,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ProcedureJavascriptParametersMetricLevelParameters struct {
}

type ProcedureJavascriptParametersObservation struct {

	// (Boolean) Enable stdout/stderr fast path logging for anonyous stored procs. This is a public parameter (similar to LOG_LEVEL). For more information, check ENABLE_CONSOLE_OUTPUT docs.
	EnableConsoleOutput []ProcedureJavascriptParametersEnableConsoleOutputObservation `json:"enableConsoleOutput,omitempty" tf:"enable_console_output,omitempty"`

	// insensitive): TRACE | DEBUG | INFO | WARN | ERROR | FATAL | OFF. For more information, check LOG_EVENT_LEVEL docs.
	LogEventLevel []ProcedureJavascriptParametersLogEventLevelObservation `json:"logEventLevel,omitempty" tf:"log_event_level,omitempty"`

	// (String) LOG_LEVEL to use when filtering events For more information, check LOG_LEVEL docs.
	LogLevel []ProcedureJavascriptParametersLogLevelObservation `json:"logLevel,omitempty" tf:"log_level,omitempty"`

	// (String) METRIC_LEVEL value to control whether to emit metrics to Event Table For more information, check METRIC_LEVEL docs.
	MetricLevel []ProcedureJavascriptParametersMetricLevelObservation `json:"metricLevel,omitempty" tf:"metric_level,omitempty"`

	// (String) Trace level value to use when generating/filtering trace events For more information, check TRACE_LEVEL docs.
	TraceLevel []ProcedureJavascriptParametersTraceLevelObservation `json:"traceLevel,omitempty" tf:"trace_level,omitempty"`
}

type ProcedureJavascriptParametersParameters struct {
}

type ProcedureJavascriptParametersTraceLevelInitParameters struct {
}

type ProcedureJavascriptParametersTraceLevelObservation struct {

	// (String)
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String)
	Level *string `json:"level,omitempty" tf:"level,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ProcedureJavascriptParametersTraceLevelParameters struct {
}

type ProcedureJavascriptShowOutputInitParameters struct {
}

type ProcedureJavascriptShowOutputObservation struct {

	// (String)
	ArgumentsRaw *string `json:"argumentsRaw,omitempty" tf:"arguments_raw,omitempty"`

	// (String)
	CatalogName *string `json:"catalogName,omitempty" tf:"catalog_name,omitempty"`

	// (String)
	CreatedOn *string `json:"createdOn,omitempty" tf:"created_on,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	ExternalAccessIntegrations *string `json:"externalAccessIntegrations,omitempty" tf:"external_access_integrations,omitempty"`

	// (Boolean)
	IsAggregate *bool `json:"isAggregate,omitempty" tf:"is_aggregate,omitempty"`

	// (Boolean)
	IsAnsi *bool `json:"isAnsi,omitempty" tf:"is_ansi,omitempty"`

	// (Boolean)
	IsBuiltin *bool `json:"isBuiltin,omitempty" tf:"is_builtin,omitempty"`

	// uses special value that cannot be set in the configuration manually (default)) Specifies that the procedure is secure. For more information about secure procedures, see Protecting Sensitive Information with Secure UDFs and Stored Procedures. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	IsSecure *bool `json:"isSecure,omitempty" tf:"is_secure,omitempty"`

	// (Boolean)
	IsTableFunction *bool `json:"isTableFunction,omitempty" tf:"is_table_function,omitempty"`

	// (Number)
	MaxNumArguments *float64 `json:"maxNumArguments,omitempty" tf:"max_num_arguments,omitempty"`

	// (Number)
	MinNumArguments *float64 `json:"minNumArguments,omitempty" tf:"min_num_arguments,omitempty"`

	// (String) The name of the procedure; the identifier does not need to be unique for the schema in which the procedure is created because stored procedures are identified and resolved by the combination of the name and argument types. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	SchemaName *string `json:"schemaName,omitempty" tf:"schema_name,omitempty"`

	// (String)
	Secrets *string `json:"secrets,omitempty" tf:"secrets,omitempty"`

	// (Boolean)
	ValidForClustering *bool `json:"validForClustering,omitempty" tf:"valid_for_clustering,omitempty"`
}

type ProcedureJavascriptShowOutputParameters struct {
}

// ProcedureJavascriptSpec defines the desired state of ProcedureJavascript
type ProcedureJavascriptSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ProcedureJavascriptParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ProcedureJavascriptInitParameters `json:"initProvider,omitempty"`
}

// ProcedureJavascriptStatus defines the observed state of ProcedureJavascript.
type ProcedureJavascriptStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ProcedureJavascriptObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ProcedureJavascript is the Schema for the ProcedureJavascripts API. Resource used to manage javascript procedure objects. For more information, check procedure documentation https://docs.snowflake.com/en/sql-reference/sql/create-procedure.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,snowflake}
type ProcedureJavascript struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.database) || (has(self.initProvider) && has(self.initProvider.database))",message="spec.forProvider.database is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.procedureDefinition) || (has(self.initProvider) && has(self.initProvider.procedureDefinition))",message="spec.forProvider.procedureDefinition is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.returnType) || (has(self.initProvider) && has(self.initProvider.returnType))",message="spec.forProvider.returnType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.schema) || (has(self.initProvider) && has(self.initProvider.schema))",message="spec.forProvider.schema is a required parameter"
	Spec   ProcedureJavascriptSpec   `json:"spec"`
	Status ProcedureJavascriptStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProcedureJavascriptList contains a list of ProcedureJavascripts
type ProcedureJavascriptList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ProcedureJavascript `json:"items"`
}

// Repository type metadata.
var (
	ProcedureJavascript_Kind             = "ProcedureJavascript"
	ProcedureJavascript_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ProcedureJavascript_Kind}.String()
	ProcedureJavascript_KindAPIVersion   = ProcedureJavascript_Kind + "." + CRDGroupVersion.String()
	ProcedureJavascript_GroupVersionKind = CRDGroupVersion.WithKind(ProcedureJavascript_Kind)
)

func init() {
	SchemeBuilder.Register(&ProcedureJavascript{}, &ProcedureJavascriptList{})
}
