// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type UserPasswordPolicyAttachmentInitParameters struct {
}

type UserPasswordPolicyAttachmentObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Fully qualified name of the password policy
	// Fully qualified name of the password policy
	PasswordPolicyName *string `json:"passwordPolicyName,omitempty" tf:"password_policy_name,omitempty"`
}

type UserPasswordPolicyAttachmentParameters struct {

	// (String) Fully qualified name of the password policy
	// Fully qualified name of the password policy
	// +kubebuilder:validation:Required
	PasswordPolicyName *string `json:"passwordPolicyName" tf:"password_policy_name,omitempty"`
}

// UserPasswordPolicyAttachmentSpec defines the desired state of UserPasswordPolicyAttachment
type UserPasswordPolicyAttachmentSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     UserPasswordPolicyAttachmentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider UserPasswordPolicyAttachmentInitParameters `json:"initProvider,omitempty"`
}

// UserPasswordPolicyAttachmentStatus defines the observed state of UserPasswordPolicyAttachment.
type UserPasswordPolicyAttachmentStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        UserPasswordPolicyAttachmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// UserPasswordPolicyAttachment is the Schema for the UserPasswordPolicyAttachments API. Specifies the password policy to use for a certain user.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,snowflake}
type UserPasswordPolicyAttachment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              UserPasswordPolicyAttachmentSpec   `json:"spec"`
	Status            UserPasswordPolicyAttachmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UserPasswordPolicyAttachmentList contains a list of UserPasswordPolicyAttachments
type UserPasswordPolicyAttachmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []UserPasswordPolicyAttachment `json:"items"`
}

// Repository type metadata.
var (
	UserPasswordPolicyAttachment_Kind             = "UserPasswordPolicyAttachment"
	UserPasswordPolicyAttachment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: UserPasswordPolicyAttachment_Kind}.String()
	UserPasswordPolicyAttachment_KindAPIVersion   = UserPasswordPolicyAttachment_Kind + "." + CRDGroupVersion.String()
	UserPasswordPolicyAttachment_GroupVersionKind = CRDGroupVersion.WithKind(UserPasswordPolicyAttachment_Kind)
)

func init() {
	SchemeBuilder.Register(&UserPasswordPolicyAttachment{}, &UserPasswordPolicyAttachmentList{})
}
