// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type StatementQueuedTimeoutInSecondsInitParameters struct {
}

type StatementQueuedTimeoutInSecondsObservation struct {

	// (String)
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String)
	Level *string `json:"level,omitempty" tf:"level,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type StatementQueuedTimeoutInSecondsParameters struct {
}

type StatementTimeoutInSecondsInitParameters struct {
}

type StatementTimeoutInSecondsObservation struct {

	// (String)
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String)
	Level *string `json:"level,omitempty" tf:"level,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type StatementTimeoutInSecondsParameters struct {
}

type WarehouseAdaptiveInitParameters struct {

	// (String) Specifies a comment for the adaptive warehouse.
	// Specifies a comment for the adaptive warehouse.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// insensitive): XSMALL | SMALL | MEDIUM | LARGE | XLARGE | XXLARGE | XXXLARGE | X4LARGE.
	// Specifies the maximum query performance level for the adaptive warehouse. Determines the initial compute capacity. Valid values are (case-insensitive): `XSMALL` | `SMALL` | `MEDIUM` | `LARGE` | `XLARGE` | `XXLARGE` | `XXXLARGE` | `X4LARGE`.
	MaxQueryPerformanceLevel *string `json:"maxQueryPerformanceLevel,omitempty" tf:"max_query_performance_level,omitempty"`

	// uses special value that cannot be set in the configuration manually (-1)) Specifies the query throughput multiplier for the adaptive warehouse.
	// Specifies the query throughput multiplier for the adaptive warehouse.
	QueryThroughputMultiplier *int64 `json:"queryThroughputMultiplier,omitempty" tf:"query_throughput_multiplier,omitempty"`

	// (String) Specifies the name of a resource monitor that is explicitly assigned to the adaptive warehouse. For more information about this resource, see docs.
	// Specifies the name of a resource monitor that is explicitly assigned to the adaptive warehouse. For more information about this resource, see [docs](./resource_monitor).
	ResourceMonitor *string `json:"resourceMonitor,omitempty" tf:"resource_monitor,omitempty"`

	// (Number) Object parameter that specifies the time, in seconds, a SQL statement (query, DDL, DML, etc.) can be queued on a warehouse before it is canceled by the system.
	// Object parameter that specifies the time, in seconds, a SQL statement (query, DDL, DML, etc.) can be queued on a warehouse before it is canceled by the system.
	StatementQueuedTimeoutInSeconds *int64 `json:"statementQueuedTimeoutInSeconds,omitempty" tf:"statement_queued_timeout_in_seconds,omitempty"`

	// (Number) Specifies the time, in seconds, after which a running SQL statement (query, DDL, DML, etc.) is canceled by the system.
	// Specifies the time, in seconds, after which a running SQL statement (query, DDL, DML, etc.) is canceled by the system.
	StatementTimeoutInSeconds *int64 `json:"statementTimeoutInSeconds,omitempty" tf:"statement_timeout_in_seconds,omitempty"`
}

type WarehouseAdaptiveObservation struct {

	// (String) Specifies a comment for the adaptive warehouse.
	// Specifies a comment for the adaptive warehouse.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) Fully qualified name of the resource. For more information, see object name resolution.
	// Fully qualified name of the resource. For more information, see [object name resolution](https://docs.snowflake.com/en/sql-reference/name-resolution).
	FullyQualifiedName *string `json:"fullyQualifiedName,omitempty" tf:"fully_qualified_name,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// insensitive): XSMALL | SMALL | MEDIUM | LARGE | XLARGE | XXLARGE | XXXLARGE | X4LARGE.
	// Specifies the maximum query performance level for the adaptive warehouse. Determines the initial compute capacity. Valid values are (case-insensitive): `XSMALL` | `SMALL` | `MEDIUM` | `LARGE` | `XLARGE` | `XXLARGE` | `XXXLARGE` | `X4LARGE`.
	MaxQueryPerformanceLevel *string `json:"maxQueryPerformanceLevel,omitempty" tf:"max_query_performance_level,omitempty"`

	// (List of Object) Outputs the result of SHOW PARAMETERS IN WAREHOUSE for the given adaptive warehouse. (see below for nested schema)
	// Outputs the result of `SHOW PARAMETERS IN WAREHOUSE` for the given adaptive warehouse.
	Parameters []WarehouseAdaptiveParametersObservation `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// uses special value that cannot be set in the configuration manually (-1)) Specifies the query throughput multiplier for the adaptive warehouse.
	// Specifies the query throughput multiplier for the adaptive warehouse.
	QueryThroughputMultiplier *int64 `json:"queryThroughputMultiplier,omitempty" tf:"query_throughput_multiplier,omitempty"`

	// (String) Specifies the name of a resource monitor that is explicitly assigned to the adaptive warehouse. For more information about this resource, see docs.
	// Specifies the name of a resource monitor that is explicitly assigned to the adaptive warehouse. For more information about this resource, see [docs](./resource_monitor).
	ResourceMonitor *string `json:"resourceMonitor,omitempty" tf:"resource_monitor,omitempty"`

	// (List of Object) Outputs the result of SHOW WAREHOUSES for the given adaptive warehouse. (see below for nested schema)
	// Outputs the result of `SHOW WAREHOUSES` for the given adaptive warehouse.
	ShowOutput []WarehouseAdaptiveShowOutputObservation `json:"showOutput,omitempty" tf:"show_output,omitempty"`

	// (Number) Object parameter that specifies the time, in seconds, a SQL statement (query, DDL, DML, etc.) can be queued on a warehouse before it is canceled by the system.
	// Object parameter that specifies the time, in seconds, a SQL statement (query, DDL, DML, etc.) can be queued on a warehouse before it is canceled by the system.
	StatementQueuedTimeoutInSeconds *int64 `json:"statementQueuedTimeoutInSeconds,omitempty" tf:"statement_queued_timeout_in_seconds,omitempty"`

	// (Number) Specifies the time, in seconds, after which a running SQL statement (query, DDL, DML, etc.) is canceled by the system.
	// Specifies the time, in seconds, after which a running SQL statement (query, DDL, DML, etc.) is canceled by the system.
	StatementTimeoutInSeconds *int64 `json:"statementTimeoutInSeconds,omitempty" tf:"statement_timeout_in_seconds,omitempty"`

	// (String) Specifies the type for the adaptive warehouse. This field is used for checking external changes and recreating the resource if needed.
	// Specifies the type for the adaptive warehouse. This field is used for checking external changes and recreating the resource if needed.
	WarehouseType *string `json:"warehouseType,omitempty" tf:"warehouse_type,omitempty"`
}

type WarehouseAdaptiveParameters struct {

	// (String) Specifies a comment for the adaptive warehouse.
	// Specifies a comment for the adaptive warehouse.
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// insensitive): XSMALL | SMALL | MEDIUM | LARGE | XLARGE | XXLARGE | XXXLARGE | X4LARGE.
	// Specifies the maximum query performance level for the adaptive warehouse. Determines the initial compute capacity. Valid values are (case-insensitive): `XSMALL` | `SMALL` | `MEDIUM` | `LARGE` | `XLARGE` | `XXLARGE` | `XXXLARGE` | `X4LARGE`.
	// +kubebuilder:validation:Optional
	MaxQueryPerformanceLevel *string `json:"maxQueryPerformanceLevel,omitempty" tf:"max_query_performance_level,omitempty"`

	// uses special value that cannot be set in the configuration manually (-1)) Specifies the query throughput multiplier for the adaptive warehouse.
	// Specifies the query throughput multiplier for the adaptive warehouse.
	// +kubebuilder:validation:Optional
	QueryThroughputMultiplier *int64 `json:"queryThroughputMultiplier,omitempty" tf:"query_throughput_multiplier,omitempty"`

	// (String) Specifies the name of a resource monitor that is explicitly assigned to the adaptive warehouse. For more information about this resource, see docs.
	// Specifies the name of a resource monitor that is explicitly assigned to the adaptive warehouse. For more information about this resource, see [docs](./resource_monitor).
	// +kubebuilder:validation:Optional
	ResourceMonitor *string `json:"resourceMonitor,omitempty" tf:"resource_monitor,omitempty"`

	// (Number) Object parameter that specifies the time, in seconds, a SQL statement (query, DDL, DML, etc.) can be queued on a warehouse before it is canceled by the system.
	// Object parameter that specifies the time, in seconds, a SQL statement (query, DDL, DML, etc.) can be queued on a warehouse before it is canceled by the system.
	// +kubebuilder:validation:Optional
	StatementQueuedTimeoutInSeconds *int64 `json:"statementQueuedTimeoutInSeconds,omitempty" tf:"statement_queued_timeout_in_seconds,omitempty"`

	// (Number) Specifies the time, in seconds, after which a running SQL statement (query, DDL, DML, etc.) is canceled by the system.
	// Specifies the time, in seconds, after which a running SQL statement (query, DDL, DML, etc.) is canceled by the system.
	// +kubebuilder:validation:Optional
	StatementTimeoutInSeconds *int64 `json:"statementTimeoutInSeconds,omitempty" tf:"statement_timeout_in_seconds,omitempty"`
}

type WarehouseAdaptiveParametersInitParameters struct {
}

type WarehouseAdaptiveParametersObservation struct {

	// (Number) Object parameter that specifies the time, in seconds, a SQL statement (query, DDL, DML, etc.) can be queued on a warehouse before it is canceled by the system.
	StatementQueuedTimeoutInSeconds []StatementQueuedTimeoutInSecondsObservation `json:"statementQueuedTimeoutInSeconds,omitempty" tf:"statement_queued_timeout_in_seconds,omitempty"`

	// (Number) Specifies the time, in seconds, after which a running SQL statement (query, DDL, DML, etc.) is canceled by the system.
	StatementTimeoutInSeconds []StatementTimeoutInSecondsObservation `json:"statementTimeoutInSeconds,omitempty" tf:"statement_timeout_in_seconds,omitempty"`
}

type WarehouseAdaptiveParametersParameters struct {
}

type WarehouseAdaptiveShowOutputInitParameters struct {
}

type WarehouseAdaptiveShowOutputObservation struct {

	// (Boolean)
	AutoResume *bool `json:"autoResume,omitempty" tf:"auto_resume,omitempty"`

	// (Number)
	Available *float64 `json:"available,omitempty" tf:"available,omitempty"`

	// (String) Specifies a comment for the adaptive warehouse.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String)
	CreatedOn *string `json:"createdOn,omitempty" tf:"created_on,omitempty"`

	// (Boolean)
	IsCurrent *bool `json:"isCurrent,omitempty" tf:"is_current,omitempty"`

	// (Boolean)
	IsDefault *bool `json:"isDefault,omitempty" tf:"is_default,omitempty"`

	// insensitive): XSMALL | SMALL | MEDIUM | LARGE | XLARGE | XXLARGE | XXXLARGE | X4LARGE.
	MaxQueryPerformanceLevel *string `json:"maxQueryPerformanceLevel,omitempty" tf:"max_query_performance_level,omitempty"`

	// (String) Identifier for the adaptive warehouse; must be unique for your account. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number)
	Other *float64 `json:"other,omitempty" tf:"other,omitempty"`

	// (String)
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// (String)
	OwnerRoleType *string `json:"ownerRoleType,omitempty" tf:"owner_role_type,omitempty"`

	// (Number)
	Provisioning *float64 `json:"provisioning,omitempty" tf:"provisioning,omitempty"`

	// uses special value that cannot be set in the configuration manually (-1)) Specifies the query throughput multiplier for the adaptive warehouse.
	QueryThroughputMultiplier *int64 `json:"queryThroughputMultiplier,omitempty" tf:"query_throughput_multiplier,omitempty"`

	// (Number)
	Queued *int64 `json:"queued,omitempty" tf:"queued,omitempty"`

	// (Number)
	Quiescing *float64 `json:"quiescing,omitempty" tf:"quiescing,omitempty"`

	// (String) Specifies the name of a resource monitor that is explicitly assigned to the adaptive warehouse. For more information about this resource, see docs.
	ResourceMonitor *string `json:"resourceMonitor,omitempty" tf:"resource_monitor,omitempty"`

	// (String)
	ResumedOn *string `json:"resumedOn,omitempty" tf:"resumed_on,omitempty"`

	// (Number)
	Running *int64 `json:"running,omitempty" tf:"running,omitempty"`

	// (String)
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// (String)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String)
	UpdatedOn *string `json:"updatedOn,omitempty" tf:"updated_on,omitempty"`
}

type WarehouseAdaptiveShowOutputParameters struct {
}

// WarehouseAdaptiveSpec defines the desired state of WarehouseAdaptive
type WarehouseAdaptiveSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   WarehouseAdaptiveParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider WarehouseAdaptiveInitParameters `json:"initProvider,omitempty"`
}

// WarehouseAdaptiveStatus defines the observed state of WarehouseAdaptive.
type WarehouseAdaptiveStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               WarehouseAdaptiveObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// WarehouseAdaptive is the Schema for the WarehouseAdaptives API. Resource used to manage adaptive warehouse objects. Adaptive Compute is a compute service focused on delivering strong performance with effortless operations. It replaces the fixed compute of the Standard Warehouse with a workload-aware one that adapts to your queries automatically. The system decides how to allocate resources for the best performance, eliminating the need for infrastructure tuning.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,snowflake}
type WarehouseAdaptive struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              WarehouseAdaptiveSpec   `json:"spec"`
	Status            WarehouseAdaptiveStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// WarehouseAdaptiveList contains a list of WarehouseAdaptives
type WarehouseAdaptiveList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []WarehouseAdaptive `json:"items"`
}

// Repository type metadata.
var (
	WarehouseAdaptive_Kind             = "WarehouseAdaptive"
	WarehouseAdaptive_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: WarehouseAdaptive_Kind}.String()
	WarehouseAdaptive_KindAPIVersion   = WarehouseAdaptive_Kind + "." + CRDGroupVersion.String()
	WarehouseAdaptive_GroupVersionKind = CRDGroupVersion.WithKind(WarehouseAdaptive_Kind)
)

func init() {
	SchemeBuilder.Register(&WarehouseAdaptive{}, &WarehouseAdaptiveList{})
}
