// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type AgentDescribeOutputInitParameters struct {
}

type AgentDescribeOutputObservation struct {

	// (String)
	AgentSpec *string `json:"agentSpec,omitempty" tf:"agent_spec,omitempty"`

	// (String)
	Aliases *string `json:"aliases,omitempty" tf:"aliases,omitempty"`

	// (String) Specifies a comment for the Cortex agent.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String)
	CreatedOn *string `json:"createdOn,omitempty" tf:"created_on,omitempty"`

	// (String)
	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`

	// (String)
	DefaultVersionName *string `json:"defaultVersionName,omitempty" tf:"default_version_name,omitempty"`

	// (String) Specifies the identifier for the Cortex agent. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// (Block List, Max: 1) Specifies agent profile information, such as display_name, avatar, and color. (see below for nested schema)
	Profile []ProfileObservation `json:"profile,omitempty" tf:"profile,omitempty"`

	// (String)
	SchemaName *string `json:"schemaName,omitempty" tf:"schema_name,omitempty"`

	// (String)
	Versions *string `json:"versions,omitempty" tf:"versions,omitempty"`
}

type AgentDescribeOutputParameters struct {
}

type AgentInitParameters struct {

	// (String) Specifies a comment for the Cortex agent.
	// Specifies a comment for the Cortex agent.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Block List, Max: 1) Specifies agent profile information, such as display_name, avatar, and color. (see below for nested schema)
	// Specifies agent profile information, such as display_name, avatar, and color.
	Profile []AgentProfileInitParameters `json:"profile,omitempty" tf:"profile,omitempty"`

	// (String) Specifies a YAML object containing the settings for the Cortex agent. The provider wraps it in $$ by default, so be aware of that while referencing the argument in the spec definition. Using $$ in this field is disallowed.
	// Specifies a YAML object containing the settings for the Cortex agent. The provider wraps it in `$$` by default, so be aware of that while referencing the argument in the spec definition. Using `$$` in this field is disallowed.
	Specification *string `json:"specification,omitempty" tf:"specification,omitempty"`
}

type AgentObservation struct {

	// (String) Specifies a comment for the Cortex agent.
	// Specifies a comment for the Cortex agent.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) The database in which to create the Cortex agent. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The database in which to create the Cortex agent. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// (List of Object) Outputs the result of DESCRIBE AGENT for this Cortex agent. (see below for nested schema)
	// Outputs the result of `DESCRIBE AGENT` for this Cortex agent.
	DescribeOutput []AgentDescribeOutputObservation `json:"describeOutput,omitempty" tf:"describe_output,omitempty"`

	// (String) Fully qualified name of the resource. For more information, see object name resolution.
	// Fully qualified name of the resource. For more information, see [object name resolution](https://docs.snowflake.com/en/sql-reference/name-resolution).
	FullyQualifiedName *string `json:"fullyQualifiedName,omitempty" tf:"fully_qualified_name,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Block List, Max: 1) Specifies agent profile information, such as display_name, avatar, and color. (see below for nested schema)
	// Specifies agent profile information, such as display_name, avatar, and color.
	Profile []AgentProfileObservation `json:"profile,omitempty" tf:"profile,omitempty"`

	// (String) The schema in which to create the Cortex agent. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The schema in which to create the Cortex agent. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// (List of Object) Outputs the result of SHOW AGENTS for this Cortex agent. (see below for nested schema)
	// Outputs the result of `SHOW AGENTS` for this Cortex agent.
	ShowOutput []AgentShowOutputObservation `json:"showOutput,omitempty" tf:"show_output,omitempty"`

	// (String) Specifies a YAML object containing the settings for the Cortex agent. The provider wraps it in $$ by default, so be aware of that while referencing the argument in the spec definition. Using $$ in this field is disallowed.
	// Specifies a YAML object containing the settings for the Cortex agent. The provider wraps it in `$$` by default, so be aware of that while referencing the argument in the spec definition. Using `$$` in this field is disallowed.
	Specification *string `json:"specification,omitempty" tf:"specification,omitempty"`
}

type AgentParameters struct {

	// (String) Specifies a comment for the Cortex agent.
	// Specifies a comment for the Cortex agent.
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) The database in which to create the Cortex agent. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The database in which to create the Cortex agent. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	// +kubebuilder:validation:Required
	Database *string `json:"database" tf:"database,omitempty"`

	// (Block List, Max: 1) Specifies agent profile information, such as display_name, avatar, and color. (see below for nested schema)
	// Specifies agent profile information, such as display_name, avatar, and color.
	// +kubebuilder:validation:Optional
	Profile []AgentProfileParameters `json:"profile,omitempty" tf:"profile,omitempty"`

	// (String) The schema in which to create the Cortex agent. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The schema in which to create the Cortex agent. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	// +kubebuilder:validation:Required
	Schema *string `json:"schema" tf:"schema,omitempty"`

	// (String) Specifies a YAML object containing the settings for the Cortex agent. The provider wraps it in $$ by default, so be aware of that while referencing the argument in the spec definition. Using $$ in this field is disallowed.
	// Specifies a YAML object containing the settings for the Cortex agent. The provider wraps it in `$$` by default, so be aware of that while referencing the argument in the spec definition. Using `$$` in this field is disallowed.
	// +kubebuilder:validation:Optional
	Specification *string `json:"specification,omitempty" tf:"specification,omitempty"`
}

type AgentProfileInitParameters struct {

	// (String) Specifies an avatar image file name or identifier.
	// Specifies an avatar image file name or identifier.
	Avatar *string `json:"avatar,omitempty" tf:"avatar,omitempty"`

	// (String) Specifies a color theme for the Cortex agent.
	// Specifies a color theme for the Cortex agent.
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// (String) Specifies a display name for the Cortex agent.
	// Specifies a display name for the Cortex agent.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`
}

type AgentProfileObservation struct {

	// (String) Specifies an avatar image file name or identifier.
	// Specifies an avatar image file name or identifier.
	Avatar *string `json:"avatar,omitempty" tf:"avatar,omitempty"`

	// (String) Specifies a color theme for the Cortex agent.
	// Specifies a color theme for the Cortex agent.
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// (String) Specifies a display name for the Cortex agent.
	// Specifies a display name for the Cortex agent.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`
}

type AgentProfileParameters struct {

	// (String) Specifies an avatar image file name or identifier.
	// Specifies an avatar image file name or identifier.
	// +kubebuilder:validation:Optional
	Avatar *string `json:"avatar,omitempty" tf:"avatar,omitempty"`

	// (String) Specifies a color theme for the Cortex agent.
	// Specifies a color theme for the Cortex agent.
	// +kubebuilder:validation:Optional
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// (String) Specifies a display name for the Cortex agent.
	// Specifies a display name for the Cortex agent.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`
}

type AgentShowOutputInitParameters struct {
}

type AgentShowOutputObservation struct {

	// (String) Specifies a comment for the Cortex agent.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String)
	CreatedOn *string `json:"createdOn,omitempty" tf:"created_on,omitempty"`

	// (String)
	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`

	// (String) Specifies the identifier for the Cortex agent. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// (Block List, Max: 1) Specifies agent profile information, such as display_name, avatar, and color. (see below for nested schema)
	Profile []ShowOutputProfileObservation `json:"profile,omitempty" tf:"profile,omitempty"`

	// (String)
	SchemaName *string `json:"schemaName,omitempty" tf:"schema_name,omitempty"`
}

type AgentShowOutputParameters struct {
}

type ProfileInitParameters struct {
}

type ProfileObservation struct {

	// (String) Specifies an avatar image file name or identifier.
	Avatar *string `json:"avatar,omitempty" tf:"avatar,omitempty"`

	// (String) Specifies a color theme for the Cortex agent.
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// (String) Specifies a display name for the Cortex agent.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`
}

type ProfileParameters struct {
}

type ShowOutputProfileInitParameters struct {
}

type ShowOutputProfileObservation struct {

	// (String) Specifies an avatar image file name or identifier.
	Avatar *string `json:"avatar,omitempty" tf:"avatar,omitempty"`

	// (String) Specifies a color theme for the Cortex agent.
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// (String) Specifies a display name for the Cortex agent.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`
}

type ShowOutputProfileParameters struct {
}

// AgentSpec defines the desired state of Agent
type AgentSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            AgentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AgentInitParameters `json:"initProvider,omitempty"`
}

// AgentStatus defines the observed state of Agent.
type AgentStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AgentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Agent is the Schema for the Agents API. Resource used to manage Cortex agent objects. For more information, check Cortex agent documentation https://docs.snowflake.com/en/sql-reference/sql/create-agent.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,snowflake}
type Agent struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.specification) || (has(self.initProvider) && has(self.initProvider.specification))",message="spec.forProvider.specification is a required parameter"
	Spec   AgentSpec   `json:"spec"`
	Status AgentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AgentList contains a list of Agents
type AgentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Agent `json:"items"`
}

// Repository type metadata.
var (
	Agent_Kind             = "Agent"
	Agent_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Agent_Kind}.String()
	Agent_KindAPIVersion   = Agent_Kind + "." + CRDGroupVersion.String()
	Agent_GroupVersionKind = CRDGroupVersion.WithKind(Agent_Kind)
)

func init() {
	SchemeBuilder.Register(&Agent{}, &AgentList{})
}
