// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type IcebergTableFromFilesDescribeOutputInitParameters struct {
}

type IcebergTableFromFilesDescribeOutputObservation struct {

	// (String)
	Check *string `json:"check,omitempty" tf:"check,omitempty"`

	// (String) Specifies a comment for the Iceberg table.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String)
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// (String)
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	// (Boolean)
	IsNullable *bool `json:"isNullable,omitempty" tf:"is_nullable,omitempty"`

	// (String)
	Kind *string `json:"kind,omitempty" tf:"kind,omitempty"`

	// (String) Specifies the identifier for the Iceberg table; must be unique for the schema in which the Iceberg table is created. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	NameMapping *string `json:"nameMapping,omitempty" tf:"name_mapping,omitempty"`

	// (String)
	PolicyName *string `json:"policyName,omitempty" tf:"policy_name,omitempty"`

	// (Boolean)
	PrimaryKey *bool `json:"primaryKey,omitempty" tf:"primary_key,omitempty"`

	// (String)
	PrivacyDomain *string `json:"privacyDomain,omitempty" tf:"privacy_domain,omitempty"`

	// (String)
	SourceIcebergType *string `json:"sourceIcebergType,omitempty" tf:"source_iceberg_type,omitempty"`

	// (String)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (Boolean)
	UniqueKey *bool `json:"uniqueKey,omitempty" tf:"unique_key,omitempty"`

	// (String)
	WriteDefault *string `json:"writeDefault,omitempty" tf:"write_default,omitempty"`
}

type IcebergTableFromFilesDescribeOutputParameters struct {
}

type IcebergTableFromFilesInitParameters struct {

	// level default is used.
	// Specifies the identifier for the catalog integration to use for the Iceberg table. If not specified, the account-level default is used.
	Catalog *string `json:"catalog,omitempty" tf:"catalog,omitempty"`

	// (String) Specifies a comment for the Iceberg table.
	// Specifies a comment for the Iceberg table.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// level default is used.
	// Specifies the identifier for the external volume where the Iceberg table stores its metadata files and data in Parquet format. If not specified, the account-level default is used.
	ExternalVolume *string `json:"externalVolume,omitempty" tf:"external_volume,omitempty"`

	// Specifies the relative path of the Iceberg metadata file in the external volume. Cannot be changed after creation. External changes for this field won't be detected.
	MetadataFilePath *string `json:"metadataFilePath,omitempty" tf:"metadata_file_path,omitempty"`

	// 8 characters with the Unicode replacement character (�) in query results for an Iceberg table. For more information, check REPLACE_INVALID_CHARACTERS docs.
	// Specifies whether to replace invalid UTF-8 characters with the Unicode replacement character (`�`) in query results for an Iceberg table. For more information, check [REPLACE_INVALID_CHARACTERS docs](https://docs.snowflake.com/en/sql-reference/parameters#replace-invalid-characters).
	ReplaceInvalidCharacters *bool `json:"replaceInvalidCharacters,omitempty" tf:"replace_invalid_characters,omitempty"`
}

type IcebergTableFromFilesObservation struct {

	// level default is used.
	// Specifies the identifier for the catalog integration to use for the Iceberg table. If not specified, the account-level default is used.
	Catalog *string `json:"catalog,omitempty" tf:"catalog,omitempty"`

	// (String) Specifies a comment for the Iceberg table.
	// Specifies a comment for the Iceberg table.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) The database in which to create the Iceberg table. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The database in which to create the Iceberg table. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// (List of Object) Outputs the result of DESCRIBE ICEBERG TABLE for the given Iceberg table. (see below for nested schema)
	// Outputs the result of `DESCRIBE ICEBERG TABLE` for the given Iceberg table.
	DescribeOutput []IcebergTableFromFilesDescribeOutputObservation `json:"describeOutput,omitempty" tf:"describe_output,omitempty"`

	// level default is used.
	// Specifies the identifier for the external volume where the Iceberg table stores its metadata files and data in Parquet format. If not specified, the account-level default is used.
	ExternalVolume *string `json:"externalVolume,omitempty" tf:"external_volume,omitempty"`

	// (String) Fully qualified name of the resource. For more information, see object name resolution.
	// Fully qualified name of the resource. For more information, see [object name resolution](https://docs.snowflake.com/en/sql-reference/name-resolution).
	FullyQualifiedName *string `json:"fullyQualifiedName,omitempty" tf:"fully_qualified_name,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Specifies the relative path of the Iceberg metadata file in the external volume. Cannot be changed after creation. External changes for this field won't be detected.
	MetadataFilePath *string `json:"metadataFilePath,omitempty" tf:"metadata_file_path,omitempty"`

	// (List of Object) Outputs the result of SHOW PARAMETERS IN ICEBERG TABLE for the given Iceberg table. (see below for nested schema)
	// Outputs the result of `SHOW PARAMETERS IN ICEBERG TABLE` for the given Iceberg table.
	Parameters []IcebergTableFromFilesParametersObservation `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// 8 characters with the Unicode replacement character (�) in query results for an Iceberg table. For more information, check REPLACE_INVALID_CHARACTERS docs.
	// Specifies whether to replace invalid UTF-8 characters with the Unicode replacement character (`�`) in query results for an Iceberg table. For more information, check [REPLACE_INVALID_CHARACTERS docs](https://docs.snowflake.com/en/sql-reference/parameters#replace-invalid-characters).
	ReplaceInvalidCharacters *bool `json:"replaceInvalidCharacters,omitempty" tf:"replace_invalid_characters,omitempty"`

	// (String) The schema in which to create the Iceberg table. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The schema in which to create the Iceberg table. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// (List of Object) Outputs the result of SHOW ICEBERG TABLES for the given Iceberg table. Note that this value will be only recomputed whenever values of fields affecting the output change. (see below for nested schema)
	// Outputs the result of `SHOW ICEBERG TABLES` for the given Iceberg table. Note that this value will be only recomputed whenever values of fields affecting the output change.
	ShowOutput []IcebergTableFromFilesShowOutputObservation `json:"showOutput,omitempty" tf:"show_output,omitempty"`
}

type IcebergTableFromFilesParameters struct {

	// level default is used.
	// Specifies the identifier for the catalog integration to use for the Iceberg table. If not specified, the account-level default is used.
	// +kubebuilder:validation:Optional
	Catalog *string `json:"catalog,omitempty" tf:"catalog,omitempty"`

	// (String) Specifies a comment for the Iceberg table.
	// Specifies a comment for the Iceberg table.
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) The database in which to create the Iceberg table. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The database in which to create the Iceberg table. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	// +kubebuilder:validation:Required
	Database *string `json:"database" tf:"database,omitempty"`

	// level default is used.
	// Specifies the identifier for the external volume where the Iceberg table stores its metadata files and data in Parquet format. If not specified, the account-level default is used.
	// +kubebuilder:validation:Optional
	ExternalVolume *string `json:"externalVolume,omitempty" tf:"external_volume,omitempty"`

	// Specifies the relative path of the Iceberg metadata file in the external volume. Cannot be changed after creation. External changes for this field won't be detected.
	// +kubebuilder:validation:Optional
	MetadataFilePath *string `json:"metadataFilePath,omitempty" tf:"metadata_file_path,omitempty"`

	// 8 characters with the Unicode replacement character (�) in query results for an Iceberg table. For more information, check REPLACE_INVALID_CHARACTERS docs.
	// Specifies whether to replace invalid UTF-8 characters with the Unicode replacement character (`�`) in query results for an Iceberg table. For more information, check [REPLACE_INVALID_CHARACTERS docs](https://docs.snowflake.com/en/sql-reference/parameters#replace-invalid-characters).
	// +kubebuilder:validation:Optional
	ReplaceInvalidCharacters *bool `json:"replaceInvalidCharacters,omitempty" tf:"replace_invalid_characters,omitempty"`

	// (String) The schema in which to create the Iceberg table. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The schema in which to create the Iceberg table. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	// +kubebuilder:validation:Required
	Schema *string `json:"schema" tf:"schema,omitempty"`
}

type IcebergTableFromFilesParametersInitParameters struct {
}

type IcebergTableFromFilesParametersObservation struct {

	// level default is used.
	Catalog []ParametersCatalogObservation `json:"catalog,omitempty" tf:"catalog,omitempty"`

	// level default is used.
	ExternalVolume []ParametersExternalVolumeObservation `json:"externalVolume,omitempty" tf:"external_volume,omitempty"`

	// 8 characters with the Unicode replacement character (�) in query results for an Iceberg table. For more information, check REPLACE_INVALID_CHARACTERS docs.
	ReplaceInvalidCharacters []ParametersReplaceInvalidCharactersObservation `json:"replaceInvalidCharacters,omitempty" tf:"replace_invalid_characters,omitempty"`
}

type IcebergTableFromFilesParametersParameters struct {
}

type IcebergTableFromFilesShowOutputInitParameters struct {
}

type IcebergTableFromFilesShowOutputObservation struct {

	// (List of Object) (see below for nested schema)
	AutoRefreshStatus []ShowOutputAutoRefreshStatusObservation `json:"autoRefreshStatus,omitempty" tf:"auto_refresh_status,omitempty"`

	// (String)
	BaseLocation *string `json:"baseLocation,omitempty" tf:"base_location,omitempty"`

	// (Boolean)
	CanWriteMetadata *bool `json:"canWriteMetadata,omitempty" tf:"can_write_metadata,omitempty"`

	// (String)
	CatalogName *string `json:"catalogName,omitempty" tf:"catalog_name,omitempty"`

	// (String)
	CatalogNamespace *string `json:"catalogNamespace,omitempty" tf:"catalog_namespace,omitempty"`

	// (String)
	CatalogSyncName *string `json:"catalogSyncName,omitempty" tf:"catalog_sync_name,omitempty"`

	// (String)
	CatalogTableName *string `json:"catalogTableName,omitempty" tf:"catalog_table_name,omitempty"`

	// (String) Specifies a comment for the Iceberg table.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String)
	CreatedOn *string `json:"createdOn,omitempty" tf:"created_on,omitempty"`

	// (Number)
	CurrentPartitionSpecID *int64 `json:"currentPartitionSpecId,omitempty" tf:"current_partition_spec_id,omitempty"`

	// (String)
	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`

	// (String)
	ExternalVolumeName *string `json:"externalVolumeName,omitempty" tf:"external_volume_name,omitempty"`

	// (Number)
	IcebergTableFormatVersion *int64 `json:"icebergTableFormatVersion,omitempty" tf:"iceberg_table_format_version,omitempty"`

	// (String)
	IcebergTableType *string `json:"icebergTableType,omitempty" tf:"iceberg_table_type,omitempty"`

	// (String) Specifies the identifier for the Iceberg table; must be unique for the schema in which the Iceberg table is created. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	NameMapping *string `json:"nameMapping,omitempty" tf:"name_mapping,omitempty"`

	// (String)
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// (String)
	OwnerRoleType *string `json:"ownerRoleType,omitempty" tf:"owner_role_type,omitempty"`

	// (List of Object) (see below for nested schema)
	PartitionSpecs []ShowOutputPartitionSpecsObservation `json:"partitionSpecs,omitempty" tf:"partition_specs,omitempty"`

	// (String)
	SchemaName *string `json:"schemaName,omitempty" tf:"schema_name,omitempty"`
}

type IcebergTableFromFilesShowOutputParameters struct {
}

type ParametersCatalogInitParameters struct {
}

type ParametersCatalogObservation struct {

	// (String)
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String)
	Level *string `json:"level,omitempty" tf:"level,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ParametersCatalogParameters struct {
}

type ParametersExternalVolumeInitParameters struct {
}

type ParametersExternalVolumeObservation struct {

	// (String)
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String)
	Level *string `json:"level,omitempty" tf:"level,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ParametersExternalVolumeParameters struct {
}

type ParametersReplaceInvalidCharactersInitParameters struct {
}

type ParametersReplaceInvalidCharactersObservation struct {

	// (String)
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String)
	Level *string `json:"level,omitempty" tf:"level,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ParametersReplaceInvalidCharactersParameters struct {
}

type PartitionSpecsFieldsInitParameters struct {
}

type PartitionSpecsFieldsObservation struct {

	// (Number)
	FieldID *int64 `json:"fieldId,omitempty" tf:"field_id,omitempty"`

	// (String) Specifies the identifier for the Iceberg table; must be unique for the schema in which the Iceberg table is created. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number)
	SourceID *int64 `json:"sourceId,omitempty" tf:"source_id,omitempty"`

	// (String)
	Transform *string `json:"transform,omitempty" tf:"transform,omitempty"`
}

type PartitionSpecsFieldsParameters struct {
}

type ShowOutputAutoRefreshStatusInitParameters struct {
}

type ShowOutputAutoRefreshStatusObservation struct {

	// (Number)
	CurrentSnapshotID *int64 `json:"currentSnapshotId,omitempty" tf:"current_snapshot_id,omitempty"`

	// (String)
	ExecutionState *string `json:"executionState,omitempty" tf:"execution_state,omitempty"`

	// (String)
	LastSnapshotTime *string `json:"lastSnapshotTime,omitempty" tf:"last_snapshot_time,omitempty"`

	// (String)
	LastUpdatedTime *string `json:"lastUpdatedTime,omitempty" tf:"last_updated_time,omitempty"`

	// (Number)
	PendingSnapshotCount *int64 `json:"pendingSnapshotCount,omitempty" tf:"pending_snapshot_count,omitempty"`
}

type ShowOutputAutoRefreshStatusParameters struct {
}

type ShowOutputPartitionSpecsInitParameters struct {
}

type ShowOutputPartitionSpecsObservation struct {

	// (List of Object) (see below for nested schema)
	Fields []PartitionSpecsFieldsObservation `json:"fields,omitempty" tf:"fields,omitempty"`

	// (Number)
	SpecID *int64 `json:"specId,omitempty" tf:"spec_id,omitempty"`
}

type ShowOutputPartitionSpecsParameters struct {
}

// IcebergTableFromFilesSpec defines the desired state of IcebergTableFromFiles
type IcebergTableFromFilesSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            IcebergTableFromFilesParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider IcebergTableFromFilesInitParameters `json:"initProvider,omitempty"`
}

// IcebergTableFromFilesStatus defines the observed state of IcebergTableFromFiles.
type IcebergTableFromFilesStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               IcebergTableFromFilesObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// IcebergTableFromFiles is the Schema for the IcebergTableFromFiless API. Resource used to manage an Iceberg table whose metadata is created from an existing Apache Iceberg metadata file in an external volume. For more information, check the official documentation https://docs.snowflake.com/en/sql-reference/sql/create-iceberg-table-iceberg-files.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,snowflake}
type IcebergTableFromFiles struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.metadataFilePath) || (has(self.initProvider) && has(self.initProvider.metadataFilePath))",message="spec.forProvider.metadataFilePath is a required parameter"
	Spec   IcebergTableFromFilesSpec   `json:"spec"`
	Status IcebergTableFromFilesStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// IcebergTableFromFilesList contains a list of IcebergTableFromFiless
type IcebergTableFromFilesList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []IcebergTableFromFiles `json:"items"`
}

// Repository type metadata.
var (
	IcebergTableFromFiles_Kind             = "IcebergTableFromFiles"
	IcebergTableFromFiles_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: IcebergTableFromFiles_Kind}.String()
	IcebergTableFromFiles_KindAPIVersion   = IcebergTableFromFiles_Kind + "." + CRDGroupVersion.String()
	IcebergTableFromFiles_GroupVersionKind = CRDGroupVersion.WithKind(IcebergTableFromFiles_Kind)
)

func init() {
	SchemeBuilder.Register(&IcebergTableFromFiles{}, &IcebergTableFromFilesList{})
}
