// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type UserAuthenticationPolicyAttachmentInitParameters struct {
}

type UserAuthenticationPolicyAttachmentObservation struct {

	// (String) Fully qualified name of the authentication policy.
	// Fully qualified name of the authentication policy.
	AuthenticationPolicyName *string `json:"authenticationPolicyName,omitempty" tf:"authentication_policy_name,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type UserAuthenticationPolicyAttachmentParameters struct {

	// (String) Fully qualified name of the authentication policy.
	// Fully qualified name of the authentication policy.
	// +kubebuilder:validation:Required
	AuthenticationPolicyName *string `json:"authenticationPolicyName" tf:"authentication_policy_name,omitempty"`
}

// UserAuthenticationPolicyAttachmentSpec defines the desired state of UserAuthenticationPolicyAttachment
type UserAuthenticationPolicyAttachmentSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            UserAuthenticationPolicyAttachmentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider UserAuthenticationPolicyAttachmentInitParameters `json:"initProvider,omitempty"`
}

// UserAuthenticationPolicyAttachmentStatus defines the observed state of UserAuthenticationPolicyAttachment.
type UserAuthenticationPolicyAttachmentStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        UserAuthenticationPolicyAttachmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// UserAuthenticationPolicyAttachment is the Schema for the UserAuthenticationPolicyAttachments API. Specifies the authentication policy to use for a certain user.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,snowflake}
type UserAuthenticationPolicyAttachment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              UserAuthenticationPolicyAttachmentSpec   `json:"spec"`
	Status            UserAuthenticationPolicyAttachmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UserAuthenticationPolicyAttachmentList contains a list of UserAuthenticationPolicyAttachments
type UserAuthenticationPolicyAttachmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []UserAuthenticationPolicyAttachment `json:"items"`
}

// Repository type metadata.
var (
	UserAuthenticationPolicyAttachment_Kind             = "UserAuthenticationPolicyAttachment"
	UserAuthenticationPolicyAttachment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: UserAuthenticationPolicyAttachment_Kind}.String()
	UserAuthenticationPolicyAttachment_KindAPIVersion   = UserAuthenticationPolicyAttachment_Kind + "." + CRDGroupVersion.String()
	UserAuthenticationPolicyAttachment_GroupVersionKind = CRDGroupVersion.WithKind(UserAuthenticationPolicyAttachment_Kind)
)

func init() {
	SchemeBuilder.Register(&UserAuthenticationPolicyAttachment{}, &UserAuthenticationPolicyAttachmentList{})
}
