// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type UserPublicKeysInitParameters struct {

	// pair authentication. Must be on 1 line without header and trailer.
	// Specifies the user’s RSA public key; used for key-pair authentication. Must be on 1 line without header and trailer.
	RsaPublicKey *string `json:"rsaPublicKey,omitempty" tf:"rsa_public_key,omitempty"`

	// pair authentication based on an expiration schedule set by your organization. Must be on 1 line without header and trailer.
	// Specifies the user’s second RSA public key; used to rotate the public and Public keys for key-pair authentication based on an expiration schedule set by your organization. Must be on 1 line without header and trailer.
	RsaPublicKey2 *string `json:"rsaPublicKey2,omitempty" tf:"rsa_public_key_2,omitempty"`
}

type UserPublicKeysObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// pair authentication. Must be on 1 line without header and trailer.
	// Specifies the user’s RSA public key; used for key-pair authentication. Must be on 1 line without header and trailer.
	RsaPublicKey *string `json:"rsaPublicKey,omitempty" tf:"rsa_public_key,omitempty"`

	// pair authentication based on an expiration schedule set by your organization. Must be on 1 line without header and trailer.
	// Specifies the user’s second RSA public key; used to rotate the public and Public keys for key-pair authentication based on an expiration schedule set by your organization. Must be on 1 line without header and trailer.
	RsaPublicKey2 *string `json:"rsaPublicKey2,omitempty" tf:"rsa_public_key_2,omitempty"`
}

type UserPublicKeysParameters struct {

	// pair authentication. Must be on 1 line without header and trailer.
	// Specifies the user’s RSA public key; used for key-pair authentication. Must be on 1 line without header and trailer.
	// +kubebuilder:validation:Optional
	RsaPublicKey *string `json:"rsaPublicKey,omitempty" tf:"rsa_public_key,omitempty"`

	// pair authentication based on an expiration schedule set by your organization. Must be on 1 line without header and trailer.
	// Specifies the user’s second RSA public key; used to rotate the public and Public keys for key-pair authentication based on an expiration schedule set by your organization. Must be on 1 line without header and trailer.
	// +kubebuilder:validation:Optional
	RsaPublicKey2 *string `json:"rsaPublicKey2,omitempty" tf:"rsa_public_key_2,omitempty"`
}

// UserPublicKeysSpec defines the desired state of UserPublicKeys
type UserPublicKeysSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            UserPublicKeysParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider UserPublicKeysInitParameters `json:"initProvider,omitempty"`
}

// UserPublicKeysStatus defines the observed state of UserPublicKeys.
type UserPublicKeysStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        UserPublicKeysObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// UserPublicKeys is the Schema for the UserPublicKeyss API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,snowflake}
type UserPublicKeys struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              UserPublicKeysSpec   `json:"spec"`
	Status            UserPublicKeysStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UserPublicKeysList contains a list of UserPublicKeyss
type UserPublicKeysList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []UserPublicKeys `json:"items"`
}

// Repository type metadata.
var (
	UserPublicKeys_Kind             = "UserPublicKeys"
	UserPublicKeys_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: UserPublicKeys_Kind}.String()
	UserPublicKeys_KindAPIVersion   = UserPublicKeys_Kind + "." + CRDGroupVersion.String()
	UserPublicKeys_GroupVersionKind = CRDGroupVersion.WithKind(UserPublicKeys_Kind)
)

func init() {
	SchemeBuilder.Register(&UserPublicKeys{}, &UserPublicKeysList{})
}
