apiVersion: preview.snowflake.crossplane.io/v1alpha1
kind: PasswordPolicyAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: preview/v1alpha1/passwordpolicyattachment
  labels:
    testing.upbound.io/example-name: ppa
  name: ppa
spec:
  forProvider:
    passwordPolicyName: ${snowflake_password_policy.pp.fully_qualified_name}

---

apiVersion: stable.snowflake.crossplane.io/v1alpha1
kind: PasswordPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: preview/v1alpha1/passwordpolicyattachment
  labels:
    testing.upbound.io/example-name: pp
  name: pp
spec:
  forProvider:
    database: prod
    schema: security

---

apiVersion: stable.snowflake.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: preview/v1alpha1/passwordpolicyattachment
  labels:
    testing.upbound.io/example-name: user
  name: user
spec:
  forProvider: {}
