apiVersion: preview.snowflake.crossplane.io/v1alpha1
kind: TableFromFiles
metadata:
  annotations:
    meta.upbound.io/example-id: preview/v1alpha1/tablefromfiles
  labels:
    testing.upbound.io/example-name: basic
  name: basic
spec:
  forProvider:
    database: DATABASE
    externalVolume: my_external_volume
    metadataFilePath: path/to/metadata/v1.metadata.json
    schema: SCHEMA
