apiVersion: preview.snowflake.crossplane.io/v1alpha1
kind: ApiIntegrationGitRepositoryGithubApp
metadata:
  annotations:
    meta.upbound.io/example-id: preview/v1alpha1/apiintegrationgitrepositorygithubapp
  labels:
    testing.upbound.io/example-name: basic
  name: basic
spec:
  forProvider:
    apiAllowedPrefixes:
    - https://github.com/my-org/
    enabled: true
