apiVersion: preview.snowflake.crossplane.io/v1alpha1
kind: CortexAgent
metadata:
  annotations:
    meta.upbound.io/example-id: preview/v1alpha1/cortexagent
  labels:
    testing.upbound.io/example-name: basic
  name: basic
spec:
  forProvider:
    database: database_name
    schema: schema_name
    specification: |
      orchestration:
        budget:
          seconds: 30
          tokens: 16000
      instructions:
        response: "You are a helpful assistant."
