apiVersion: preview.snowflake.crossplane.io/v1alpha1
kind: EmailNotificationIntegration
metadata:
  annotations:
    meta.upbound.io/example-id: preview/v1alpha1/emailnotificationintegration
  labels:
    testing.upbound.io/example-name: email_int
  name: email-int
spec:
  forProvider:
    allowedRecipients:
    - john.doe@gmail.com
    comment: A notification integration.
    enabled: true
