apiVersion: preview.snowflake.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: preview/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: basic
  name: basic
spec:
  forProvider:
    authenticationAuthority: POSTGRES
    computeFamily: STANDARD_M
    storageSizeGb: 10
