#!/usr/bin/env bash
# Regenerates the "Resource Support" tables in README.md from
# internal/resourcelist/{stable,preview}.go, cross-referenced against
# hack/tested_resources.txt (one manually-tested Terraform resource name
# per line). There is no automated test suite for this provider yet, so
# "Tested" tracks manual verification only.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tested_file="$root/hack/tested_resources.txt"
readme="$root/README.md"

# ponytail: bash port of internal/resourcelist/kind.go's ToKind. Keep in
# sync by hand if that function changes; invoking Go here would need a
# build step for no real benefit.
to_kind() {
	local name="${1#snowflake_}" out="" part parts
	IFS='_' read -ra parts <<<"$name"
	for part in "${parts[@]}"; do
		out+="${part^}"
	done
	printf '%s' "$out"
}

is_tested() {
	grep -qxF "$1" "$tested_file" 2>/dev/null
}

# Extracts quoted "snowflake_..." resource names from a resourcelist file, sorted.
extract_resources() {
	grep -oE '"snowflake_[a-z0-9_]+"' "$1" | tr -d '"' | sort
}

render_table() {
	local file="$1" name status
	printf '| Kind | Terraform Resource | Tested |\n'
	printf '|---|---|---|\n'
	while IFS= read -r name; do
		[[ -z "$name" ]] && continue
		status="⬜"
		is_tested "$name" && status="✅"
		printf '| %s | `%s` | %s |\n' "$(to_kind "$name")" "$name" "$status"
	done < <(extract_resources "$file")
}

stable_file="$root/internal/resourcelist/stable.go"
preview_file="$root/internal/resourcelist/preview.go"
stable_count=$(extract_resources "$stable_file" | wc -l | tr -d ' ')
preview_count=$(extract_resources "$preview_file" | wc -l | tr -d ' ')
tested_count=$(grep -cvE '^[[:space:]]*(#|$)' "$tested_file" 2>/dev/null || true)
tested_count=${tested_count:-0}

block=$(cat <<EOF
<!-- RESOURCE_SUPPORT_START -->
## Resource Support

Generated by \`hack/resource_support.sh\` from \`internal/resourcelist/\`. Every
resource listed is already code-generated by upjet; **Tested** marks only
those walked through the manual test procedure (no automated test suite
exists yet). To mark a resource tested, add its Terraform name to
\`hack/tested_resources.txt\` and re-run the script.

$tested_count / $((stable_count + preview_count)) resources manually tested.

### Stable ($stable_count)

$(render_table "$stable_file")

### Preview ($preview_count)

$(render_table "$preview_file")
<!-- RESOURCE_SUPPORT_END -->
EOF
)

if grep -q '<!-- RESOURCE_SUPPORT_START -->' "$readme"; then
	awk -v block="$block" '
		/<!-- RESOURCE_SUPPORT_START -->/ { inblock=1 }
		!inblock { print }
		/<!-- RESOURCE_SUPPORT_END -->/ { print block; inblock=0 }
	' "$readme" >"$readme.tmp"
	mv "$readme.tmp" "$readme"
else
	printf '\n%s\n' "$block" >>"$readme"
fi

echo "Updated $readme ($stable_count stable, $preview_count preview, $tested_count tested)"
