apiVersion: stable.snowflake.m.crossplane.io/v1alpha1
kind: GrantDatabaseRole
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/grantdatabaserole
  labels:
    testing.upbound.io/example-name: g
  name: g
  namespace: crossplane-system
spec:
  forProvider:
    databaseRoleName: '"${var.database}"."${snowflake_database_role.database_role.name}"'
    parentRoleName: ${snowflake_account_role.parent_role.name}

---

apiVersion: stable.snowflake.m.crossplane.io/v1alpha1
kind: AccountRole
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/grantdatabaserole
  labels:
    testing.upbound.io/example-name: parent_role
  name: parent-role
  namespace: crossplane-system
spec:
  forProvider: {}

---

apiVersion: stable.snowflake.m.crossplane.io/v1alpha1
kind: DatabaseRole
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/grantdatabaserole
  labels:
    testing.upbound.io/example-name: database_role
  name: database-role
  namespace: crossplane-system
spec:
  forProvider:
    database: ${var.database}

---

apiVersion: stable.snowflake.m.crossplane.io/v1alpha1
kind: DatabaseRole
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/grantdatabaserole
  labels:
    testing.upbound.io/example-name: parent_database_role
  name: parent-database-role
  namespace: crossplane-system
spec:
  forProvider:
    database: ${var.database}
