apiVersion: stable.snowflake.m.crossplane.io/v1alpha1
kind: GrantAccountRole
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/grantaccountrole
  labels:
    testing.upbound.io/example-name: g
  name: g
  namespace: crossplane-system
spec:
  forProvider:
    parentRoleName: ${snowflake_account_role.parent_role.name}
    roleName: ${snowflake_account_role.role.name}

---

apiVersion: stable.snowflake.m.crossplane.io/v1alpha1
kind: AccountRole
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/grantaccountrole
  labels:
    testing.upbound.io/example-name: parent_role
  name: parent-role
  namespace: crossplane-system
spec:
  forProvider: {}

---

apiVersion: stable.snowflake.m.crossplane.io/v1alpha1
kind: AccountRole
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/grantaccountrole
  labels:
    testing.upbound.io/example-name: role
  name: role
  namespace: crossplane-system
spec:
  forProvider: {}

---

apiVersion: stable.snowflake.m.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/grantaccountrole
  labels:
    testing.upbound.io/example-name: user
  name: user
  namespace: crossplane-system
spec:
  forProvider: {}
