apiVersion: stable.snowflake.m.crossplane.io/v1alpha1
kind: Saml2Integration
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/saml2integration
  labels:
    testing.upbound.io/example-name: saml_integration
  name: saml-integration
  namespace: crossplane-system
spec:
  forProvider:
    saml2Issuer: test_issuer
    saml2Provider: CUSTOM
    saml2SsoUrl: https://example.com
    saml2X509CertSecretRef:
      key: attribute.cert.pem
      name: example-secret
