apiVersion: stable.snowflake.m.crossplane.io/v1alpha1
kind: SecretWithBasicAuthentication
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/secretwithbasicauthentication
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: crossplane-system
spec:
  forProvider:
    database: EXAMPLE_DB
    passwordSecretRef:
      key: example-key
      name: example-secret
    schema: EXAMPLE_SCHEMA
    usernameSecretRef:
      key: example-key
      name: example-secret
