apiVersion: stable.snowflake.m.crossplane.io/v1alpha1
kind: StorageIntegrationGcs
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/storageintegrationgcs
  labels:
    testing.upbound.io/example-name: minimal
  name: minimal
  namespace: crossplane-system
spec:
  forProvider:
    enabled: true
    storageAllowedLocations:
    - gcs://mybucket1/path1
