apiVersion: stable.snowflake.m.crossplane.io/v1alpha1
kind: StorageIntegrationAzure
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/storageintegrationazure
  labels:
    testing.upbound.io/example-name: minimal
  name: minimal
  namespace: crossplane-system
spec:
  forProvider:
    azureTenantId: a123b4c5-1234-123a-a12b-1a23b45678c9
    enabled: true
    storageAllowedLocations:
    - azure://myaccount.blob.core.windows.net/mycontainer/path1/
