apiVersion: stable.snowflake.m.crossplane.io/v1alpha1
kind: StreamOnTable
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/streamontable
  labels:
    testing.upbound.io/example-name: stream
  name: stream
  namespace: crossplane-system
spec:
  forProvider:
    database: database
    schema: schema
    table: ${snowflake_table.example.fully_qualified_name}
