apiVersion: stable.snowflake.m.crossplane.io/v1alpha1
kind: UserSessionPolicyAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/usersessionpolicyattachment
  labels:
    testing.upbound.io/example-name: spa
  name: spa
  namespace: crossplane-system
spec:
  forProvider:
    sessionPolicyName: ${snowflake_session_policy.sp.fully_qualified_name}

---

apiVersion: stable.snowflake.m.crossplane.io/v1alpha1
kind: SessionPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/usersessionpolicyattachment
  labels:
    testing.upbound.io/example-name: sp
  name: sp
  namespace: crossplane-system
spec:
  forProvider:
    database: prod
    schema: security

---

apiVersion: stable.snowflake.m.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/usersessionpolicyattachment
  labels:
    testing.upbound.io/example-name: user
  name: user
  namespace: crossplane-system
spec:
  forProvider: {}
