apiVersion: user.snowflake.crossplane.io/v1alpha1
kind: SessionPolicyAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: user/v1alpha1/sessionpolicyattachment
  labels:
    testing.upbound.io/example-name: spa
  name: spa
spec:
  forProvider:
    sessionPolicyName: ${snowflake_session_policy.sp.fully_qualified_name}
    userName: ${snowflake_user.user.name}

---

apiVersion: user.snowflake.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: user/v1alpha1/sessionpolicyattachment
  labels:
    testing.upbound.io/example-name: user
  name: user
spec:
  forProvider: {}
