apiVersion: stable.snowflake.crossplane.io/v1alpha1
kind: AccountSessionPolicyAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/accountsessionpolicyattachment
  labels:
    testing.upbound.io/example-name: attachment
  name: attachment
spec:
  forProvider: {}
