apiVersion: stable.snowflake.crossplane.io/v1alpha1
kind: SharedDatabase
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/shareddatabase
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    fromShare: <primary_account_organization_name>.<primary_account_name>.${snowflake_share.test.name}
    provider: ${secondary_account}

---

apiVersion: stable.snowflake.crossplane.io/v1alpha1
kind: Database
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/shareddatabase
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    provider: ${primary_account}
