apiVersion: stable.snowflake.crossplane.io/v1alpha1
kind: Volume
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/volume
  labels:
    testing.upbound.io/example-name: s3_basic
  name: s3-basic
spec:
  forProvider:
    storageLocation:
    - storageAwsRoleArn: arn:aws:iam::123456789012:role/myrole
      storageBaseUrl: s3://mybucket/
      storageLocationName: my-s3-location
      storageProvider: S3
