apiVersion: preview.snowflake.m.crossplane.io/v1alpha1
kind: AccountAuthenticationPolicyAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: preview/v1alpha1/accountauthenticationpolicyattachment
  labels:
    testing.upbound.io/example-name: attachment
  name: attachment
  namespace: crossplane-system
spec:
  forProvider: {}

---

apiVersion: stable.snowflake.m.crossplane.io/v1alpha1
kind: AuthenticationPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: preview/v1alpha1/accountauthenticationpolicyattachment
  labels:
    testing.upbound.io/example-name: default
  name: default
  namespace: crossplane-system
spec:
  forProvider:
    database: prod
    schema: security
