apiVersion: preview.snowflake.m.crossplane.io/v1alpha1
kind: Account
metadata:
  annotations:
    meta.upbound.io/example-id: preview/v1alpha1/account
  labels:
    testing.upbound.io/example-name: account
  name: account
  namespace: crossplane-system
spec:
  forProvider:
    adminName: admin
    adminPasswordSecretRef:
      key: example-key
      name: example-secret
    comment: A managed account.
    type: READER
