apiVersion: preview.snowflake.m.crossplane.io/v1alpha1
kind: ApiIntegrationGitRepositoryToken
metadata:
  annotations:
    meta.upbound.io/example-id: preview/v1alpha1/apiintegrationgitrepositorytoken
  labels:
    testing.upbound.io/example-name: basic
  name: basic
  namespace: crossplane-system
spec:
  forProvider:
    apiAllowedPrefixes:
    - https://github.com/my-org/
    enabled: true
    noAllowedAuthenticationSecrets: true
