apiVersion: preview.snowflake.m.crossplane.io/v1alpha1
kind: ExternalTable
metadata:
  annotations:
    meta.upbound.io/example-id: preview/v1alpha1/externaltable
  labels:
    testing.upbound.io/example-name: external_table
  name: external-table
  namespace: crossplane-system
spec:
  forProvider:
    column:
    - name: id
      type: int
    - name: data
      type: text
    comment: External table
    database: db
    fileFormat: TYPE = CSV FIELD_DELIMITER = '|'
    schema: schema
