apiVersion: preview.snowflake.m.crossplane.io/v1alpha1
kind: FileFormat
metadata:
  annotations:
    meta.upbound.io/example-id: preview/v1alpha1/fileformat
  labels:
    testing.upbound.io/example-name: example_file_format
  name: example-file-format
  namespace: crossplane-system
spec:
  forProvider:
    database: EXAMPLE_DB
    formatType: CSV
    schema: EXAMPLE_SCHEMA
