apiVersion: preview.snowflake.m.crossplane.io/v1alpha1
kind: FunctionJavascript
metadata:
  annotations:
    meta.upbound.io/example-id: preview/v1alpha1/functionjavascript
  labels:
    testing.upbound.io/example-name: minimal
  name: minimal
  namespace: crossplane-system
spec:
  forProvider:
    arguments:
    - argDataType: VARIANT
      argName: x
    database: ${snowflake_database.test.name}
    functionDefinition: |2
        if (x == 0) {
          return 1;
        } else {
          return 2;
        }
    name: my_javascript_function
    returnType: VARIANT
    schema: ${snowflake_schema.test.name}
