apiVersion: preview.snowflake.m.crossplane.io/v1alpha1
kind: Notebook
metadata:
  annotations:
    meta.upbound.io/example-id: preview/v1alpha1/notebook
  labels:
    testing.upbound.io/example-name: basic
  name: basic
  namespace: crossplane-system
spec:
  forProvider:
    database: DATABASE
    schema: SCHEMA
