apiVersion: preview.snowflake.m.crossplane.io/v1alpha1
kind: ObjectParameter
metadata:
  annotations:
    meta.upbound.io/example-id: preview/v1alpha1/objectparameter
  labels:
    testing.upbound.io/example-name: o
  name: o
  namespace: crossplane-system
spec:
  forProvider:
    key: SUSPEND_TASK_AFTER_NUM_FAILURES
    objectIdentifier:
    - name: ${snowflake_database.d.name}
    objectType: DATABASE
    value: "33"

---

apiVersion: stable.snowflake.m.crossplane.io/v1alpha1
kind: Database
metadata:
  annotations:
    meta.upbound.io/example-id: preview/v1alpha1/objectparameter
  labels:
    testing.upbound.io/example-name: d
  name: d
  namespace: crossplane-system
spec:
  forProvider: {}

---

apiVersion: stable.snowflake.m.crossplane.io/v1alpha1
kind: Schema
metadata:
  annotations:
    meta.upbound.io/example-id: preview/v1alpha1/objectparameter
  labels:
    testing.upbound.io/example-name: s
  name: s
  namespace: crossplane-system
spec:
  forProvider:
    database: TEST_DB

---

apiVersion: preview.snowflake.m.crossplane.io/v1alpha1
kind: Table
metadata:
  annotations:
    meta.upbound.io/example-id: preview/v1alpha1/objectparameter
  labels:
    testing.upbound.io/example-name: t
  name: t
  namespace: crossplane-system
spec:
  forProvider:
    column:
    - name: id
      type: NUMBER
    database: TEST_DB
    schema: TEST_SCHEMA
