apiVersion: preview.snowflake.m.crossplane.io/v1alpha1
kind: SearchService
metadata:
  annotations:
    meta.upbound.io/example-id: preview/v1alpha1/searchservice
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: crossplane-system
spec:
  forProvider:
    comment: some comment
    database: ${snowflake_database.test.name}
    embeddingModel: snowflake-arctic-embed-m-v1.5
    "on": SOME_TEXT
    query: SELECT SOME_TEXT FROM "some_database"."some_schema"."some_table"
    schema: ${snowflake_schema.test.name}
    targetLag: 2 minutes
    warehouse: some_warehouse

---

apiVersion: stable.snowflake.m.crossplane.io/v1alpha1
kind: Database
metadata:
  annotations:
    meta.upbound.io/example-id: preview/v1alpha1/searchservice
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: crossplane-system
spec:
  forProvider: {}

---

apiVersion: stable.snowflake.m.crossplane.io/v1alpha1
kind: Schema
metadata:
  annotations:
    meta.upbound.io/example-id: preview/v1alpha1/searchservice
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: crossplane-system
spec:
  forProvider:
    database: some_database

---

apiVersion: preview.snowflake.m.crossplane.io/v1alpha1
kind: Table
metadata:
  annotations:
    meta.upbound.io/example-id: preview/v1alpha1/searchservice
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: crossplane-system
spec:
  forProvider:
    changeTracking: true
    column:
    - name: ID
      type: NUMBER(38,0)
    - name: SOME_TEXT
      type: VARCHAR
    database: some_database
    schema: some_schema
