apiVersion: preview.snowflake.m.crossplane.io/v1alpha1
kind: StorageLifecyclePolicy
metadata:
  annotations:
    meta.upbound.io/example-id: preview/v1alpha1/storagelifecyclepolicy
  labels:
    testing.upbound.io/example-name: basic
  name: basic
  namespace: crossplane-system
spec:
  forProvider:
    argument:
    - name: VAL
      type: VARCHAR
    body: LENGTH(VAL) > 0
    database: database_name
    schema: schema_name
