apiVersion: preview.snowflake.m.crossplane.io/v1alpha1
kind: TableFromDeltaFiles
metadata:
  annotations:
    meta.upbound.io/example-id: preview/v1alpha1/tablefromdeltafiles
  labels:
    testing.upbound.io/example-name: basic
  name: basic
  namespace: crossplane-system
spec:
  forProvider:
    baseLocation: path/to/delta/table
    database: DATABASE
    schema: SCHEMA
