apiVersion: stable.snowflake.crossplane.io/v1alpha1
kind: CatalogIntegrationAwsGlue
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/catalogintegrationawsglue
  labels:
    testing.upbound.io/example-name: basic
  name: basic
spec:
  forProvider:
    enabled: false
    glueAwsRoleArn: arn:aws:iam::123456789012:role/testRole
    glueCatalogId: "123456789012"
