apiVersion: stable.snowflake.crossplane.io/v1alpha1
kind: Connection
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/connection
  labels:
    testing.upbound.io/example-name: basic
  name: basic
spec:
  forProvider: {}
