apiVersion: stable.snowflake.crossplane.io/v1alpha1
kind: DatabaseRole
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/databaserole
  labels:
    testing.upbound.io/example-name: test_database_role
  name: test-database-role
spec:
  forProvider:
    comment: my database role
    database: ${snowflake_database.test_database.fully_qualified_name}

---

apiVersion: stable.snowflake.crossplane.io/v1alpha1
kind: Database
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/databaserole
  labels:
    testing.upbound.io/example-name: test_database
  name: test-database
spec:
  forProvider: {}
