apiVersion: stable.snowflake.crossplane.io/v1alpha1
kind: SecondaryConnection
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/secondaryconnection
  labels:
    testing.upbound.io/example-name: basic
  name: basic
spec:
  forProvider:
    asReplicaOf: '"<organization_name>"."<account_name>"."<connection_name>"'
