apiVersion: stable.snowflake.crossplane.io/v1alpha1
kind: StageExternalS3
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/stageexternals3
  labels:
    testing.upbound.io/example-name: basic
  name: basic
spec:
  forProvider:
    database: my_database
    schema: my_schema
    url: s3://mybucket/mypath/
