apiVersion: stable.snowflake.crossplane.io/v1alpha1
kind: StreamOnView
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/streamonview
  labels:
    testing.upbound.io/example-name: stream
  name: stream
spec:
  forProvider:
    database: database
    schema: schema
    view: ${snowflake_view.example.fully_qualified_name}
