apiVersion: stable.snowflake.crossplane.io/v1alpha1
kind: UserProgrammaticAccessToken
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/userprogrammaticaccesstoken
  labels:
    testing.upbound.io/example-name: basic
  name: basic
spec:
  forProvider:
    user: USER

---

apiVersion: stable.snowflake.crossplane.io/v1alpha1
kind: AccountRole
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/userprogrammaticaccesstoken
  labels:
    testing.upbound.io/example-name: role
  name: role
spec:
  forProvider: {}

---

apiVersion: stable.snowflake.crossplane.io/v1alpha1
kind: GrantAccountRole
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/userprogrammaticaccesstoken
  labels:
    testing.upbound.io/example-name: grant_role_to_user
  name: grant-role-to-user
spec:
  forProvider:
    roleName: ROLE
    userName: USER

---

apiVersion: stable.snowflake.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/userprogrammaticaccesstoken
  labels:
    testing.upbound.io/example-name: user
  name: user
spec:
  forProvider: {}
