apiVersion: stable.snowflake.crossplane.io/v1alpha1
kind: WithClientCredentials
metadata:
  annotations:
    meta.upbound.io/example-id: stable/v1alpha1/withclientcredentials
  labels:
    testing.upbound.io/example-name: basic
  name: basic
spec:
  forProvider:
    apiAuthentication: ${snowflake_api_authentication_integration_with_client_credentials.example.fully_qualified_name}
    database: EXAMPLE_DB
    schema: EXAMPLE_SCHEMA
