// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ImageRepositoryInitParameters struct {

	// (String) Specifies a comment for the object.
	// Specifies a comment for the object.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// insensitive): SNOWFLAKE_FULL | SNOWFLAKE_SSE.
	// Specifies the encryption type for the image repository. Can only be set at creation time. Valid values are (case-insensitive): `SNOWFLAKE_FULL` | `SNOWFLAKE_SSE`.
	Encryption *string `json:"encryption,omitempty" tf:"encryption,omitempty"`
}

type ImageRepositoryObservation struct {

	// (String) Specifies a comment for the object.
	// Specifies a comment for the object.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) The database in which to create the image repository. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The database in which to create the image repository. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// insensitive): SNOWFLAKE_FULL | SNOWFLAKE_SSE.
	// Specifies the encryption type for the image repository. Can only be set at creation time. Valid values are (case-insensitive): `SNOWFLAKE_FULL` | `SNOWFLAKE_SSE`.
	Encryption *string `json:"encryption,omitempty" tf:"encryption,omitempty"`

	// (String) Fully qualified name of the resource. For more information, see object name resolution.
	// Fully qualified name of the resource. For more information, see [object name resolution](https://docs.snowflake.com/en/sql-reference/name-resolution).
	FullyQualifiedName *string `json:"fullyQualifiedName,omitempty" tf:"fully_qualified_name,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The schema in which to create the image repository. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The schema in which to create the image repository. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// (List of Object) Outputs the result of SHOW IMAGE REPOSITORIES for the given image repository. (see below for nested schema)
	// Outputs the result of `SHOW IMAGE REPOSITORIES` for the given image repository.
	ShowOutput []ImageRepositoryShowOutputObservation `json:"showOutput,omitempty" tf:"show_output,omitempty"`
}

type ImageRepositoryParameters struct {

	// (String) Specifies a comment for the object.
	// Specifies a comment for the object.
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) The database in which to create the image repository. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The database in which to create the image repository. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	// +kubebuilder:validation:Required
	Database *string `json:"database" tf:"database,omitempty"`

	// insensitive): SNOWFLAKE_FULL | SNOWFLAKE_SSE.
	// Specifies the encryption type for the image repository. Can only be set at creation time. Valid values are (case-insensitive): `SNOWFLAKE_FULL` | `SNOWFLAKE_SSE`.
	// +kubebuilder:validation:Optional
	Encryption *string `json:"encryption,omitempty" tf:"encryption,omitempty"`

	// (String) The schema in which to create the image repository. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The schema in which to create the image repository. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	// +kubebuilder:validation:Required
	Schema *string `json:"schema" tf:"schema,omitempty"`
}

type ImageRepositoryShowOutputInitParameters struct {
}

type ImageRepositoryShowOutputObservation struct {

	// (String) Specifies a comment for the object.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String)
	CreatedOn *string `json:"createdOn,omitempty" tf:"created_on,omitempty"`

	// (String)
	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`

	// insensitive): SNOWFLAKE_FULL | SNOWFLAKE_SSE.
	Encryption *string `json:"encryption,omitempty" tf:"encryption,omitempty"`

	// (String) Specifies the identifier for the image repository; must be unique for the schema in which the image repository is created. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// (String)
	OwnerRoleType *string `json:"ownerRoleType,omitempty" tf:"owner_role_type,omitempty"`

	// (String)
	PrivatelinkRepositoryURL *string `json:"privatelinkRepositoryUrl,omitempty" tf:"privatelink_repository_url,omitempty"`

	// (String)
	RepositoryURL *string `json:"repositoryUrl,omitempty" tf:"repository_url,omitempty"`

	// (String)
	SchemaName *string `json:"schemaName,omitempty" tf:"schema_name,omitempty"`
}

type ImageRepositoryShowOutputParameters struct {
}

// ImageRepositorySpec defines the desired state of ImageRepository
type ImageRepositorySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ImageRepositoryParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ImageRepositoryInitParameters `json:"initProvider,omitempty"`
}

// ImageRepositoryStatus defines the observed state of ImageRepository.
type ImageRepositoryStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ImageRepositoryObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ImageRepository is the Schema for the ImageRepositorys API. Resource used to manage image repositories. For more information, check image repositories documentation https://docs.snowflake.com/en/sql-reference/sql/create-image-repository. Snowpark Container Services provides an OCIv2-compliant image registry service and a storage unit call repository to store images. See Working with an image registry and repository https://docs.snowflake.com/en/developer-guide/snowpark-container-services/working-with-registry-repository developer guide for more details.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,snowflake}
type ImageRepository struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ImageRepositorySpec   `json:"spec"`
	Status            ImageRepositoryStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ImageRepositoryList contains a list of ImageRepositorys
type ImageRepositoryList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ImageRepository `json:"items"`
}

// Repository type metadata.
var (
	ImageRepository_Kind             = "ImageRepository"
	ImageRepository_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ImageRepository_Kind}.String()
	ImageRepository_KindAPIVersion   = ImageRepository_Kind + "." + CRDGroupVersion.String()
	ImageRepository_GroupVersionKind = CRDGroupVersion.WithKind(ImageRepository_Kind)
)

func init() {
	SchemeBuilder.Register(&ImageRepository{}, &ImageRepositoryList{})
}
