// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type NetworkPolicyDescribeOutputInitParameters struct {
}

type NetworkPolicyDescribeOutputObservation struct {

	// (Set of String) Specifies one or more IPv4 addresses (CIDR notation) that are allowed access to your Snowflake account.
	AllowedIPList *string `json:"allowedIpList,omitempty" tf:"allowed_ip_list,omitempty"`

	// (Set of String) Specifies a list of fully qualified network rules that contain the network identifiers that are allowed access to Snowflake. For more information about this resource, see docs.
	AllowedNetworkRuleList *string `json:"allowedNetworkRuleList,omitempty" tf:"allowed_network_rule_list,omitempty"`

	// (Set of String) Specifies one or more IPv4 addresses (CIDR notation) that are denied access to your Snowflake account. Do not add 0.0.0.0/0 to blocked_ip_list, in order to block all IP addresses except a select list, you only need to add IP addresses to allowed_ip_list.
	BlockedIPList *string `json:"blockedIpList,omitempty" tf:"blocked_ip_list,omitempty"`

	// (Set of String) Specifies a list of fully qualified network rules that contain the network identifiers that are denied access to Snowflake. For more information about this resource, see docs.
	BlockedNetworkRuleList *string `json:"blockedNetworkRuleList,omitempty" tf:"blocked_network_rule_list,omitempty"`
}

type NetworkPolicyDescribeOutputParameters struct {
}

type NetworkPolicyInitParameters_2 struct {

	// (Set of String) Specifies one or more IPv4 addresses (CIDR notation) that are allowed access to your Snowflake account.
	// Specifies one or more IPv4 addresses (CIDR notation) that are allowed access to your Snowflake account.
	// +listType=set
	AllowedIPList []*string `json:"allowedIpList,omitempty" tf:"allowed_ip_list,omitempty"`

	// (Set of String) Specifies a list of fully qualified network rules that contain the network identifiers that are allowed access to Snowflake. For more information about this resource, see docs.
	// Specifies a list of fully qualified network rules that contain the network identifiers that are allowed access to Snowflake. For more information about this resource, see [docs](./network_rule).
	// +listType=set
	AllowedNetworkRuleList []*string `json:"allowedNetworkRuleList,omitempty" tf:"allowed_network_rule_list,omitempty"`

	// (Set of String) Specifies one or more IPv4 addresses (CIDR notation) that are denied access to your Snowflake account. Do not add 0.0.0.0/0 to blocked_ip_list, in order to block all IP addresses except a select list, you only need to add IP addresses to allowed_ip_list.
	// Specifies one or more IPv4 addresses (CIDR notation) that are denied access to your Snowflake account. **Do not** add `0.0.0.0/0` to `blocked_ip_list`, in order to block all IP addresses except a select list, you only need to add IP addresses to `allowed_ip_list`.
	// +listType=set
	BlockedIPList []*string `json:"blockedIpList,omitempty" tf:"blocked_ip_list,omitempty"`

	// (Set of String) Specifies a list of fully qualified network rules that contain the network identifiers that are denied access to Snowflake. For more information about this resource, see docs.
	// Specifies a list of fully qualified network rules that contain the network identifiers that are denied access to Snowflake. For more information about this resource, see [docs](./network_rule).
	// +listType=set
	BlockedNetworkRuleList []*string `json:"blockedNetworkRuleList,omitempty" tf:"blocked_network_rule_list,omitempty"`

	// (String) Specifies a comment for the network policy.
	// Specifies a comment for the network policy.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`
}

type NetworkPolicyObservation_2 struct {

	// (Set of String) Specifies one or more IPv4 addresses (CIDR notation) that are allowed access to your Snowflake account.
	// Specifies one or more IPv4 addresses (CIDR notation) that are allowed access to your Snowflake account.
	// +listType=set
	AllowedIPList []*string `json:"allowedIpList,omitempty" tf:"allowed_ip_list,omitempty"`

	// (Set of String) Specifies a list of fully qualified network rules that contain the network identifiers that are allowed access to Snowflake. For more information about this resource, see docs.
	// Specifies a list of fully qualified network rules that contain the network identifiers that are allowed access to Snowflake. For more information about this resource, see [docs](./network_rule).
	// +listType=set
	AllowedNetworkRuleList []*string `json:"allowedNetworkRuleList,omitempty" tf:"allowed_network_rule_list,omitempty"`

	// (Set of String) Specifies one or more IPv4 addresses (CIDR notation) that are denied access to your Snowflake account. Do not add 0.0.0.0/0 to blocked_ip_list, in order to block all IP addresses except a select list, you only need to add IP addresses to allowed_ip_list.
	// Specifies one or more IPv4 addresses (CIDR notation) that are denied access to your Snowflake account. **Do not** add `0.0.0.0/0` to `blocked_ip_list`, in order to block all IP addresses except a select list, you only need to add IP addresses to `allowed_ip_list`.
	// +listType=set
	BlockedIPList []*string `json:"blockedIpList,omitempty" tf:"blocked_ip_list,omitempty"`

	// (Set of String) Specifies a list of fully qualified network rules that contain the network identifiers that are denied access to Snowflake. For more information about this resource, see docs.
	// Specifies a list of fully qualified network rules that contain the network identifiers that are denied access to Snowflake. For more information about this resource, see [docs](./network_rule).
	// +listType=set
	BlockedNetworkRuleList []*string `json:"blockedNetworkRuleList,omitempty" tf:"blocked_network_rule_list,omitempty"`

	// (String) Specifies a comment for the network policy.
	// Specifies a comment for the network policy.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (List of Object) Outputs the result of DESCRIBE NETWORK POLICY for the given network policy. (see below for nested schema)
	// Outputs the result of `DESCRIBE NETWORK POLICY` for the given network policy.
	DescribeOutput []NetworkPolicyDescribeOutputObservation `json:"describeOutput,omitempty" tf:"describe_output,omitempty"`

	// (String) Fully qualified name of the resource. For more information, see object name resolution.
	// Fully qualified name of the resource. For more information, see [object name resolution](https://docs.snowflake.com/en/sql-reference/name-resolution).
	FullyQualifiedName *string `json:"fullyQualifiedName,omitempty" tf:"fully_qualified_name,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (List of Object) Outputs the result of SHOW NETWORK POLICIES for the given network policy. (see below for nested schema)
	// Outputs the result of `SHOW NETWORK POLICIES` for the given network policy.
	ShowOutput []NetworkPolicyShowOutputObservation `json:"showOutput,omitempty" tf:"show_output,omitempty"`
}

type NetworkPolicyParameters_2 struct {

	// (Set of String) Specifies one or more IPv4 addresses (CIDR notation) that are allowed access to your Snowflake account.
	// Specifies one or more IPv4 addresses (CIDR notation) that are allowed access to your Snowflake account.
	// +kubebuilder:validation:Optional
	// +listType=set
	AllowedIPList []*string `json:"allowedIpList,omitempty" tf:"allowed_ip_list,omitempty"`

	// (Set of String) Specifies a list of fully qualified network rules that contain the network identifiers that are allowed access to Snowflake. For more information about this resource, see docs.
	// Specifies a list of fully qualified network rules that contain the network identifiers that are allowed access to Snowflake. For more information about this resource, see [docs](./network_rule).
	// +kubebuilder:validation:Optional
	// +listType=set
	AllowedNetworkRuleList []*string `json:"allowedNetworkRuleList,omitempty" tf:"allowed_network_rule_list,omitempty"`

	// (Set of String) Specifies one or more IPv4 addresses (CIDR notation) that are denied access to your Snowflake account. Do not add 0.0.0.0/0 to blocked_ip_list, in order to block all IP addresses except a select list, you only need to add IP addresses to allowed_ip_list.
	// Specifies one or more IPv4 addresses (CIDR notation) that are denied access to your Snowflake account. **Do not** add `0.0.0.0/0` to `blocked_ip_list`, in order to block all IP addresses except a select list, you only need to add IP addresses to `allowed_ip_list`.
	// +kubebuilder:validation:Optional
	// +listType=set
	BlockedIPList []*string `json:"blockedIpList,omitempty" tf:"blocked_ip_list,omitempty"`

	// (Set of String) Specifies a list of fully qualified network rules that contain the network identifiers that are denied access to Snowflake. For more information about this resource, see docs.
	// Specifies a list of fully qualified network rules that contain the network identifiers that are denied access to Snowflake. For more information about this resource, see [docs](./network_rule).
	// +kubebuilder:validation:Optional
	// +listType=set
	BlockedNetworkRuleList []*string `json:"blockedNetworkRuleList,omitempty" tf:"blocked_network_rule_list,omitempty"`

	// (String) Specifies a comment for the network policy.
	// Specifies a comment for the network policy.
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`
}

type NetworkPolicyShowOutputInitParameters struct {
}

type NetworkPolicyShowOutputObservation struct {

	// (String) Specifies a comment for the network policy.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String)
	CreatedOn *string `json:"createdOn,omitempty" tf:"created_on,omitempty"`

	// (Number)
	EntriesInAllowedIPList *int64 `json:"entriesInAllowedIpList,omitempty" tf:"entries_in_allowed_ip_list,omitempty"`

	// (Number)
	EntriesInAllowedNetworkRules *int64 `json:"entriesInAllowedNetworkRules,omitempty" tf:"entries_in_allowed_network_rules,omitempty"`

	// (Number)
	EntriesInBlockedIPList *int64 `json:"entriesInBlockedIpList,omitempty" tf:"entries_in_blocked_ip_list,omitempty"`

	// (Number)
	EntriesInBlockedNetworkRules *int64 `json:"entriesInBlockedNetworkRules,omitempty" tf:"entries_in_blocked_network_rules,omitempty"`

	// (String) Specifies the identifier for the network policy; must be unique for the account in which the network policy is created. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type NetworkPolicyShowOutputParameters struct {
}

// NetworkPolicySpec defines the desired state of NetworkPolicy
type NetworkPolicySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            NetworkPolicyParameters_2 `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider NetworkPolicyInitParameters_2 `json:"initProvider,omitempty"`
}

// NetworkPolicyStatus defines the observed state of NetworkPolicy.
type NetworkPolicyStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               NetworkPolicyObservation_2 `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// NetworkPolicy is the Schema for the NetworkPolicys API. Resource used to control network traffic. For more information, check an official guide https://docs.snowflake.com/en/user-guide/network-policies on controlling network traffic with network policies.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,snowflake}
type NetworkPolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              NetworkPolicySpec   `json:"spec"`
	Status            NetworkPolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NetworkPolicyList contains a list of NetworkPolicys
type NetworkPolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkPolicy `json:"items"`
}

// Repository type metadata.
var (
	NetworkPolicy_Kind             = "NetworkPolicy"
	NetworkPolicy_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: NetworkPolicy_Kind}.String()
	NetworkPolicy_KindAPIVersion   = NetworkPolicy_Kind + "." + CRDGroupVersion.String()
	NetworkPolicy_GroupVersionKind = CRDGroupVersion.WithKind(NetworkPolicy_Kind)
)

func init() {
	SchemeBuilder.Register(&NetworkPolicy{}, &NetworkPolicyList{})
}
