// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type DescribeOutputSignatureInitParameters struct {
}

type DescribeOutputSignatureObservation struct {

	// (String) Specifies the identifier for the row access policy; must be unique for the database and schema in which the row access policy is created. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The argument type. VECTOR data types are not yet supported. For more information about data types, check Snowflake docs.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type DescribeOutputSignatureParameters struct {
}

type RowAccessPolicyArgumentInitParameters struct {

	// (String) Specifies the identifier for the row access policy; must be unique for the database and schema in which the row access policy is created. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The argument name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The argument type. VECTOR data types are not yet supported. For more information about data types, check Snowflake docs.
	// The argument type. VECTOR data types are not yet supported. For more information about data types, check [Snowflake docs](https://docs.snowflake.com/en/sql-reference/intro-summary-data-types).
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type RowAccessPolicyArgumentObservation struct {

	// (String) Specifies the identifier for the row access policy; must be unique for the database and schema in which the row access policy is created. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The argument name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The argument type. VECTOR data types are not yet supported. For more information about data types, check Snowflake docs.
	// The argument type. VECTOR data types are not yet supported. For more information about data types, check [Snowflake docs](https://docs.snowflake.com/en/sql-reference/intro-summary-data-types).
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type RowAccessPolicyArgumentParameters struct {

	// (String) Specifies the identifier for the row access policy; must be unique for the database and schema in which the row access policy is created. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The argument name
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// (String) The argument type. VECTOR data types are not yet supported. For more information about data types, check Snowflake docs.
	// The argument type. VECTOR data types are not yet supported. For more information about data types, check [Snowflake docs](https://docs.snowflake.com/en/sql-reference/intro-summary-data-types).
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type RowAccessPolicyDescribeOutputInitParameters struct {
}

type RowAccessPolicyDescribeOutputObservation struct {

	// valued SQL expression. To mitigate permadiff on this field, the provider replaces blank characters with a space. This can lead to false positives in cases where a change in case or run of whitespace is semantically significant.
	Body *string `json:"body,omitempty" tf:"body,omitempty"`

	// (String) Specifies the identifier for the row access policy; must be unique for the database and schema in which the row access policy is created. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	ReturnType *string `json:"returnType,omitempty" tf:"return_type,omitempty"`

	// (List of Object) (see below for nested schema)
	Signature []DescribeOutputSignatureObservation `json:"signature,omitempty" tf:"signature,omitempty"`
}

type RowAccessPolicyDescribeOutputParameters struct {
}

type RowAccessPolicyInitParameters struct {

	// (Block List, Min: 1) List of the arguments for the row access policy. A signature specifies a set of attributes that must be considered to determine whether the row is accessible. The attribute values come from the database object (e.g. table or view) to be protected by the row access policy. If any argument name or type is changed, the resource is recreated. (see below for nested schema)
	// List of the arguments for the row access policy. A signature specifies a set of attributes that must be considered to determine whether the row is accessible. The attribute values come from the database object (e.g. table or view) to be protected by the row access policy. If any argument name or type is changed, the resource is recreated.
	Argument []RowAccessPolicyArgumentInitParameters `json:"argument,omitempty" tf:"argument,omitempty"`

	// valued SQL expression. To mitigate permadiff on this field, the provider replaces blank characters with a space. This can lead to false positives in cases where a change in case or run of whitespace is semantically significant.
	// Specifies the SQL expression. The expression can be any boolean-valued SQL expression. To mitigate permadiff on this field, the provider replaces blank characters with a space. This can lead to false positives in cases where a change in case or run of whitespace is semantically significant.
	Body *string `json:"body,omitempty" tf:"body,omitempty"`

	// (String) Specifies a comment for the row access policy.
	// Specifies a comment for the row access policy.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`
}

type RowAccessPolicyObservation struct {

	// (Block List, Min: 1) List of the arguments for the row access policy. A signature specifies a set of attributes that must be considered to determine whether the row is accessible. The attribute values come from the database object (e.g. table or view) to be protected by the row access policy. If any argument name or type is changed, the resource is recreated. (see below for nested schema)
	// List of the arguments for the row access policy. A signature specifies a set of attributes that must be considered to determine whether the row is accessible. The attribute values come from the database object (e.g. table or view) to be protected by the row access policy. If any argument name or type is changed, the resource is recreated.
	Argument []RowAccessPolicyArgumentObservation `json:"argument,omitempty" tf:"argument,omitempty"`

	// valued SQL expression. To mitigate permadiff on this field, the provider replaces blank characters with a space. This can lead to false positives in cases where a change in case or run of whitespace is semantically significant.
	// Specifies the SQL expression. The expression can be any boolean-valued SQL expression. To mitigate permadiff on this field, the provider replaces blank characters with a space. This can lead to false positives in cases where a change in case or run of whitespace is semantically significant.
	Body *string `json:"body,omitempty" tf:"body,omitempty"`

	// (String) Specifies a comment for the row access policy.
	// Specifies a comment for the row access policy.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) The database in which to create the row access policy. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The database in which to create the row access policy. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// (List of Object) Outputs the result of DESCRIBE ROW ACCESS POLICY for the given row access policy. (see below for nested schema)
	// Outputs the result of `DESCRIBE ROW ACCESS POLICY` for the given row access policy.
	DescribeOutput []RowAccessPolicyDescribeOutputObservation `json:"describeOutput,omitempty" tf:"describe_output,omitempty"`

	// (String) Fully qualified name of the resource. For more information, see object name resolution.
	// Fully qualified name of the resource. For more information, see [object name resolution](https://docs.snowflake.com/en/sql-reference/name-resolution).
	FullyQualifiedName *string `json:"fullyQualifiedName,omitempty" tf:"fully_qualified_name,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The schema in which to create the row access policy. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The schema in which to create the row access policy. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// (List of Object) Outputs the result of SHOW ROW ACCESS POLICIES for the given row access policy. (see below for nested schema)
	// Outputs the result of `SHOW ROW ACCESS POLICIES` for the given row access policy.
	ShowOutput []RowAccessPolicyShowOutputObservation `json:"showOutput,omitempty" tf:"show_output,omitempty"`
}

type RowAccessPolicyParameters struct {

	// (Block List, Min: 1) List of the arguments for the row access policy. A signature specifies a set of attributes that must be considered to determine whether the row is accessible. The attribute values come from the database object (e.g. table or view) to be protected by the row access policy. If any argument name or type is changed, the resource is recreated. (see below for nested schema)
	// List of the arguments for the row access policy. A signature specifies a set of attributes that must be considered to determine whether the row is accessible. The attribute values come from the database object (e.g. table or view) to be protected by the row access policy. If any argument name or type is changed, the resource is recreated.
	// +kubebuilder:validation:Optional
	Argument []RowAccessPolicyArgumentParameters `json:"argument,omitempty" tf:"argument,omitempty"`

	// valued SQL expression. To mitigate permadiff on this field, the provider replaces blank characters with a space. This can lead to false positives in cases where a change in case or run of whitespace is semantically significant.
	// Specifies the SQL expression. The expression can be any boolean-valued SQL expression. To mitigate permadiff on this field, the provider replaces blank characters with a space. This can lead to false positives in cases where a change in case or run of whitespace is semantically significant.
	// +kubebuilder:validation:Optional
	Body *string `json:"body,omitempty" tf:"body,omitempty"`

	// (String) Specifies a comment for the row access policy.
	// Specifies a comment for the row access policy.
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) The database in which to create the row access policy. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The database in which to create the row access policy. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	// +kubebuilder:validation:Required
	Database *string `json:"database" tf:"database,omitempty"`

	// (String) The schema in which to create the row access policy. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The schema in which to create the row access policy. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	// +kubebuilder:validation:Required
	Schema *string `json:"schema" tf:"schema,omitempty"`
}

type RowAccessPolicyShowOutputInitParameters struct {
}

type RowAccessPolicyShowOutputObservation struct {

	// (String) Specifies a comment for the row access policy.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String)
	CreatedOn *string `json:"createdOn,omitempty" tf:"created_on,omitempty"`

	// (String)
	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`

	// (String)
	Kind *string `json:"kind,omitempty" tf:"kind,omitempty"`

	// (String) Specifies the identifier for the row access policy; must be unique for the database and schema in which the row access policy is created. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	Options *string `json:"options,omitempty" tf:"options,omitempty"`

	// (String)
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// (String)
	OwnerRoleType *string `json:"ownerRoleType,omitempty" tf:"owner_role_type,omitempty"`

	// (String)
	SchemaName *string `json:"schemaName,omitempty" tf:"schema_name,omitempty"`
}

type RowAccessPolicyShowOutputParameters struct {
}

// RowAccessPolicySpec defines the desired state of RowAccessPolicy
type RowAccessPolicySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            RowAccessPolicyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RowAccessPolicyInitParameters `json:"initProvider,omitempty"`
}

// RowAccessPolicyStatus defines the observed state of RowAccessPolicy.
type RowAccessPolicyStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               RowAccessPolicyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RowAccessPolicy is the Schema for the RowAccessPolicys API. Resource used to manage row access policy objects. For more information, check row access policy documentation https://docs.snowflake.com/en/sql-reference/sql/create-row-access-policy.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,snowflake}
type RowAccessPolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.argument) || (has(self.initProvider) && has(self.initProvider.argument))",message="spec.forProvider.argument is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.body) || (has(self.initProvider) && has(self.initProvider.body))",message="spec.forProvider.body is a required parameter"
	Spec   RowAccessPolicySpec   `json:"spec"`
	Status RowAccessPolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RowAccessPolicyList contains a list of RowAccessPolicys
type RowAccessPolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RowAccessPolicy `json:"items"`
}

// Repository type metadata.
var (
	RowAccessPolicy_Kind             = "RowAccessPolicy"
	RowAccessPolicy_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RowAccessPolicy_Kind}.String()
	RowAccessPolicy_KindAPIVersion   = RowAccessPolicy_Kind + "." + CRDGroupVersion.String()
	RowAccessPolicy_GroupVersionKind = CRDGroupVersion.WithKind(RowAccessPolicy_Kind)
)

func init() {
	SchemeBuilder.Register(&RowAccessPolicy{}, &RowAccessPolicyList{})
}
