// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type RuleDescribeOutputInitParameters struct {
}

type RuleDescribeOutputObservation struct {

	// (String) Specifies a comment for the network rule.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String)
	CreatedOn *string `json:"createdOn,omitempty" tf:"created_on,omitempty"`

	// (String)
	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`

	// reference/sql/create-network-rule#required-parameters for details. Valid values are (case-insensitive): INGRESS | INTERNAL_STAGE | EGRESS | POSTGRES_INGRESS | POSTGRES_EGRESS.
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// (String) Specifies the identifier for the network rule; must be unique for the database and schema in which the network rule is created.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// (String)
	SchemaName *string `json:"schemaName,omitempty" tf:"schema_name,omitempty"`

	// reference/sql/create-network-rule#required-parameters for details. Valid values are (case-insensitive): IPV4 | AWSVPCEID | AZURELINKID | GCPPSCID | HOST_PORT | PRIVATE_HOST_PORT.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// reference/sql/create-network-rule#required-parameters for details.
	ValueList []*string `json:"valueList,omitempty" tf:"value_list,omitempty"`
}

type RuleDescribeOutputParameters struct {
}

type RuleInitParameters struct {

	// (String) Specifies a comment for the network rule.
	// Specifies a comment for the network rule.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// reference/sql/create-network-rule#required-parameters for details. Valid values are (case-insensitive): INGRESS | INTERNAL_STAGE | EGRESS | POSTGRES_INGRESS | POSTGRES_EGRESS.
	// Specifies what is restricted by the network rule, see https://docs.snowflake.com/en/sql-reference/sql/create-network-rule#required-parameters for details. Valid values are (case-insensitive): `INGRESS` | `INTERNAL_STAGE` | `EGRESS` | `POSTGRES_INGRESS` | `POSTGRES_EGRESS`.
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// reference/sql/create-network-rule#required-parameters for details. Valid values are (case-insensitive): IPV4 | AWSVPCEID | AZURELINKID | GCPPSCID | HOST_PORT | PRIVATE_HOST_PORT.
	// Specifies the type of network identifiers being allowed or blocked. A network rule can have only one type. Allowed values are determined by the mode of the network rule; see https://docs.snowflake.com/en/sql-reference/sql/create-network-rule#required-parameters for details. Valid values are (case-insensitive): `IPV4` | `AWSVPCEID` | `AZURELINKID` | `GCPPSCID` | `HOST_PORT` | `PRIVATE_HOST_PORT`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// reference/sql/create-network-rule#required-parameters for details.
	// Specifies the network identifiers that will be allowed or blocked. Valid values in the list are determined by the type of network rule, see https://docs.snowflake.com/en/sql-reference/sql/create-network-rule#required-parameters for details.
	// +listType=set
	ValueList []*string `json:"valueList,omitempty" tf:"value_list,omitempty"`
}

type RuleObservation struct {

	// (String) Specifies a comment for the network rule.
	// Specifies a comment for the network rule.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) The database in which to create the network rule.
	// The database in which to create the network rule.
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// (List of Object) Outputs the result of DESCRIBE NETWORK RULE for the given network rule. (see below for nested schema)
	// Outputs the result of `DESCRIBE NETWORK RULE` for the given network rule.
	DescribeOutput []RuleDescribeOutputObservation `json:"describeOutput,omitempty" tf:"describe_output,omitempty"`

	// (String) Fully qualified name of the resource. For more information, see object name resolution.
	// Fully qualified name of the resource. For more information, see [object name resolution](https://docs.snowflake.com/en/sql-reference/name-resolution).
	FullyQualifiedName *string `json:"fullyQualifiedName,omitempty" tf:"fully_qualified_name,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// reference/sql/create-network-rule#required-parameters for details. Valid values are (case-insensitive): INGRESS | INTERNAL_STAGE | EGRESS | POSTGRES_INGRESS | POSTGRES_EGRESS.
	// Specifies what is restricted by the network rule, see https://docs.snowflake.com/en/sql-reference/sql/create-network-rule#required-parameters for details. Valid values are (case-insensitive): `INGRESS` | `INTERNAL_STAGE` | `EGRESS` | `POSTGRES_INGRESS` | `POSTGRES_EGRESS`.
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// (String) The schema in which to create the network rule.
	// The schema in which to create the network rule.
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// (List of Object) Outputs the result of SHOW NETWORK RULES for the given network rule. (see below for nested schema)
	// Outputs the result of `SHOW NETWORK RULES` for the given network rule.
	ShowOutput []RuleShowOutputObservation `json:"showOutput,omitempty" tf:"show_output,omitempty"`

	// reference/sql/create-network-rule#required-parameters for details. Valid values are (case-insensitive): IPV4 | AWSVPCEID | AZURELINKID | GCPPSCID | HOST_PORT | PRIVATE_HOST_PORT.
	// Specifies the type of network identifiers being allowed or blocked. A network rule can have only one type. Allowed values are determined by the mode of the network rule; see https://docs.snowflake.com/en/sql-reference/sql/create-network-rule#required-parameters for details. Valid values are (case-insensitive): `IPV4` | `AWSVPCEID` | `AZURELINKID` | `GCPPSCID` | `HOST_PORT` | `PRIVATE_HOST_PORT`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// reference/sql/create-network-rule#required-parameters for details.
	// Specifies the network identifiers that will be allowed or blocked. Valid values in the list are determined by the type of network rule, see https://docs.snowflake.com/en/sql-reference/sql/create-network-rule#required-parameters for details.
	// +listType=set
	ValueList []*string `json:"valueList,omitempty" tf:"value_list,omitempty"`
}

type RuleParameters struct {

	// (String) Specifies a comment for the network rule.
	// Specifies a comment for the network rule.
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) The database in which to create the network rule.
	// The database in which to create the network rule.
	// +kubebuilder:validation:Required
	Database *string `json:"database" tf:"database,omitempty"`

	// reference/sql/create-network-rule#required-parameters for details. Valid values are (case-insensitive): INGRESS | INTERNAL_STAGE | EGRESS | POSTGRES_INGRESS | POSTGRES_EGRESS.
	// Specifies what is restricted by the network rule, see https://docs.snowflake.com/en/sql-reference/sql/create-network-rule#required-parameters for details. Valid values are (case-insensitive): `INGRESS` | `INTERNAL_STAGE` | `EGRESS` | `POSTGRES_INGRESS` | `POSTGRES_EGRESS`.
	// +kubebuilder:validation:Optional
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// (String) The schema in which to create the network rule.
	// The schema in which to create the network rule.
	// +kubebuilder:validation:Required
	Schema *string `json:"schema" tf:"schema,omitempty"`

	// reference/sql/create-network-rule#required-parameters for details. Valid values are (case-insensitive): IPV4 | AWSVPCEID | AZURELINKID | GCPPSCID | HOST_PORT | PRIVATE_HOST_PORT.
	// Specifies the type of network identifiers being allowed or blocked. A network rule can have only one type. Allowed values are determined by the mode of the network rule; see https://docs.snowflake.com/en/sql-reference/sql/create-network-rule#required-parameters for details. Valid values are (case-insensitive): `IPV4` | `AWSVPCEID` | `AZURELINKID` | `GCPPSCID` | `HOST_PORT` | `PRIVATE_HOST_PORT`.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// reference/sql/create-network-rule#required-parameters for details.
	// Specifies the network identifiers that will be allowed or blocked. Valid values in the list are determined by the type of network rule, see https://docs.snowflake.com/en/sql-reference/sql/create-network-rule#required-parameters for details.
	// +kubebuilder:validation:Optional
	// +listType=set
	ValueList []*string `json:"valueList,omitempty" tf:"value_list,omitempty"`
}

type RuleShowOutputInitParameters struct {
}

type RuleShowOutputObservation struct {

	// (String) Specifies a comment for the network rule.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String)
	CreatedOn *string `json:"createdOn,omitempty" tf:"created_on,omitempty"`

	// (String)
	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`

	// (Number)
	EntriesInValueList *float64 `json:"entriesInValueList,omitempty" tf:"entries_in_value_list,omitempty"`

	// reference/sql/create-network-rule#required-parameters for details. Valid values are (case-insensitive): INGRESS | INTERNAL_STAGE | EGRESS | POSTGRES_INGRESS | POSTGRES_EGRESS.
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// (String) Specifies the identifier for the network rule; must be unique for the database and schema in which the network rule is created.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// (String)
	OwnerRoleType *string `json:"ownerRoleType,omitempty" tf:"owner_role_type,omitempty"`

	// (String)
	SchemaName *string `json:"schemaName,omitempty" tf:"schema_name,omitempty"`

	// reference/sql/create-network-rule#required-parameters for details. Valid values are (case-insensitive): IPV4 | AWSVPCEID | AZURELINKID | GCPPSCID | HOST_PORT | PRIVATE_HOST_PORT.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type RuleShowOutputParameters struct {
}

// RuleSpec defines the desired state of Rule
type RuleSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            RuleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RuleInitParameters `json:"initProvider,omitempty"`
}

// RuleStatus defines the observed state of Rule.
type RuleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RuleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Rule is the Schema for the Rules API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,snowflake}
type Rule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.mode) || (has(self.initProvider) && has(self.initProvider.mode))",message="spec.forProvider.mode is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.valueList) || (has(self.initProvider) && has(self.initProvider.valueList))",message="spec.forProvider.valueList is a required parameter"
	Spec   RuleSpec   `json:"spec"`
	Status RuleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RuleList contains a list of Rules
type RuleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Rule `json:"items"`
}

// Repository type metadata.
var (
	Rule_Kind             = "Rule"
	Rule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Rule_Kind}.String()
	Rule_KindAPIVersion   = Rule_Kind + "." + CRDGroupVersion.String()
	Rule_GroupVersionKind = CRDGroupVersion.WithKind(Rule_Kind)
)

func init() {
	SchemeBuilder.Register(&Rule{}, &RuleList{})
}
