apiVersion: preview.snowflake.m.crossplane.io/v1alpha1
kind: AccountPasswordPolicyAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: preview/v1alpha1/accountpasswordpolicyattachment
  labels:
    testing.upbound.io/example-name: attachment
  name: attachment
  namespace: crossplane-system
spec:
  forProvider: {}
