apiVersion: user.snowflake.m.crossplane.io/v1alpha1
kind: ProgrammaticAccessToken
metadata:
  annotations:
    meta.upbound.io/example-id: user/v1alpha1/programmaticaccesstoken
  labels:
    testing.upbound.io/example-name: basic
  name: basic
  namespace: crossplane-system
spec:
  forProvider:
    name: TOKEN
    user: USER

---

apiVersion: user.snowflake.m.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: user/v1alpha1/programmaticaccesstoken
  labels:
    testing.upbound.io/example-name: user
  name: user
  namespace: crossplane-system
spec:
  forProvider: {}
