// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type AccountSessionPolicyAttachmentInitParameters struct {
}

type AccountSessionPolicyAttachmentObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type AccountSessionPolicyAttachmentParameters struct {
}

// AccountSessionPolicyAttachmentSpec defines the desired state of AccountSessionPolicyAttachment
type AccountSessionPolicyAttachmentSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   AccountSessionPolicyAttachmentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AccountSessionPolicyAttachmentInitParameters `json:"initProvider,omitempty"`
}

// AccountSessionPolicyAttachmentStatus defines the observed state of AccountSessionPolicyAttachment.
type AccountSessionPolicyAttachmentStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               AccountSessionPolicyAttachmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AccountSessionPolicyAttachment is the Schema for the AccountSessionPolicyAttachments API. Specifies the session policy to use for the current account. To set the session policy of a different account, use a provider alias.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,snowflake}
type AccountSessionPolicyAttachment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              AccountSessionPolicyAttachmentSpec   `json:"spec"`
	Status            AccountSessionPolicyAttachmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccountSessionPolicyAttachmentList contains a list of AccountSessionPolicyAttachments
type AccountSessionPolicyAttachmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccountSessionPolicyAttachment `json:"items"`
}

// Repository type metadata.
var (
	AccountSessionPolicyAttachment_Kind             = "AccountSessionPolicyAttachment"
	AccountSessionPolicyAttachment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccountSessionPolicyAttachment_Kind}.String()
	AccountSessionPolicyAttachment_KindAPIVersion   = AccountSessionPolicyAttachment_Kind + "." + CRDGroupVersion.String()
	AccountSessionPolicyAttachment_GroupVersionKind = CRDGroupVersion.WithKind(AccountSessionPolicyAttachment_Kind)
)

func init() {
	SchemeBuilder.Register(&AccountSessionPolicyAttachment{}, &AccountSessionPolicyAttachmentList{})
}
