// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type CatalogIntegrationObjectStorageDescribeOutputInitParameters struct {
}

type CatalogIntegrationObjectStorageDescribeOutputObservation struct {

	// (String) Specifies the type of catalog source.
	CatalogSource *string `json:"catalogSource,omitempty" tf:"catalog_source,omitempty"`

	// (String) (Default: “) Specifies a comment for the catalog integration.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean) Specifies whether the catalog integration is available for use for Iceberg tables. true allows users to create new Iceberg tables that reference this integration. Existing Iceberg tables that reference this integration function normally. false prevents users from creating new Iceberg tables that reference this integration. Existing Iceberg tables that reference this integration cannot access the catalog in the table definition.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// based tables, specifies the number of seconds to wait between attempts to poll your external cloud storage for new metadata.
	RefreshIntervalSeconds *int64 `json:"refreshIntervalSeconds,omitempty" tf:"refresh_interval_seconds,omitempty"`

	// insensitive): ICEBERG | DELTA.
	TableFormat *string `json:"tableFormat,omitempty" tf:"table_format,omitempty"`
}

type CatalogIntegrationObjectStorageDescribeOutputParameters struct {
}

type CatalogIntegrationObjectStorageInitParameters struct {

	// (String) (Default: “) Specifies a comment for the catalog integration.
	// Specifies a comment for the catalog integration.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean) Specifies whether the catalog integration is available for use for Iceberg tables. true allows users to create new Iceberg tables that reference this integration. Existing Iceberg tables that reference this integration function normally. false prevents users from creating new Iceberg tables that reference this integration. Existing Iceberg tables that reference this integration cannot access the catalog in the table definition.
	// Specifies whether the catalog integration is available for use for Iceberg tables. `true` allows users to create new Iceberg tables that reference this integration. Existing Iceberg tables that reference this integration function normally. `false` prevents users from creating new Iceberg tables that reference this integration. Existing Iceberg tables that reference this integration cannot access the catalog in the table definition.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// based tables, specifies the number of seconds to wait between attempts to poll your external cloud storage for new metadata.
	// Specifies the number of seconds to wait between attempts to poll the external Iceberg catalog for metadata updates for automated refresh. For Delta-based tables, specifies the number of seconds to wait between attempts to poll your external cloud storage for new metadata.
	RefreshIntervalSeconds *int64 `json:"refreshIntervalSeconds,omitempty" tf:"refresh_interval_seconds,omitempty"`

	// insensitive): ICEBERG | DELTA.
	// Specifies the table format. Valid values are (case-insensitive): `ICEBERG` | `DELTA`.
	TableFormat *string `json:"tableFormat,omitempty" tf:"table_format,omitempty"`
}

type CatalogIntegrationObjectStorageObservation struct {

	// (String) Specifies the type of catalog source.
	// Specifies the type of catalog source.
	CatalogSource *string `json:"catalogSource,omitempty" tf:"catalog_source,omitempty"`

	// (String) (Default: “) Specifies a comment for the catalog integration.
	// Specifies a comment for the catalog integration.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (List of Object) Outputs the result of DESCRIBE CATALOG INTEGRATION for the given catalog integration. (see below for nested schema)
	// Outputs the result of `DESCRIBE CATALOG INTEGRATION` for the given catalog integration.
	DescribeOutput []CatalogIntegrationObjectStorageDescribeOutputObservation `json:"describeOutput,omitempty" tf:"describe_output,omitempty"`

	// (Boolean) Specifies whether the catalog integration is available for use for Iceberg tables. true allows users to create new Iceberg tables that reference this integration. Existing Iceberg tables that reference this integration function normally. false prevents users from creating new Iceberg tables that reference this integration. Existing Iceberg tables that reference this integration cannot access the catalog in the table definition.
	// Specifies whether the catalog integration is available for use for Iceberg tables. `true` allows users to create new Iceberg tables that reference this integration. Existing Iceberg tables that reference this integration function normally. `false` prevents users from creating new Iceberg tables that reference this integration. Existing Iceberg tables that reference this integration cannot access the catalog in the table definition.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Fully qualified name of the resource. For more information, see object name resolution.
	// Fully qualified name of the resource. For more information, see [object name resolution](https://docs.snowflake.com/en/sql-reference/name-resolution).
	FullyQualifiedName *string `json:"fullyQualifiedName,omitempty" tf:"fully_qualified_name,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// based tables, specifies the number of seconds to wait between attempts to poll your external cloud storage for new metadata.
	// Specifies the number of seconds to wait between attempts to poll the external Iceberg catalog for metadata updates for automated refresh. For Delta-based tables, specifies the number of seconds to wait between attempts to poll your external cloud storage for new metadata.
	RefreshIntervalSeconds *int64 `json:"refreshIntervalSeconds,omitempty" tf:"refresh_interval_seconds,omitempty"`

	// (List of Object) Outputs the result of SHOW CATALOG INTEGRATIONS for the given catalog integration. (see below for nested schema)
	// Outputs the result of `SHOW CATALOG INTEGRATIONS` for the given catalog integration.
	ShowOutput []CatalogIntegrationObjectStorageShowOutputObservation `json:"showOutput,omitempty" tf:"show_output,omitempty"`

	// insensitive): ICEBERG | DELTA.
	// Specifies the table format. Valid values are (case-insensitive): `ICEBERG` | `DELTA`.
	TableFormat *string `json:"tableFormat,omitempty" tf:"table_format,omitempty"`
}

type CatalogIntegrationObjectStorageParameters struct {

	// (String) (Default: “) Specifies a comment for the catalog integration.
	// Specifies a comment for the catalog integration.
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean) Specifies whether the catalog integration is available for use for Iceberg tables. true allows users to create new Iceberg tables that reference this integration. Existing Iceberg tables that reference this integration function normally. false prevents users from creating new Iceberg tables that reference this integration. Existing Iceberg tables that reference this integration cannot access the catalog in the table definition.
	// Specifies whether the catalog integration is available for use for Iceberg tables. `true` allows users to create new Iceberg tables that reference this integration. Existing Iceberg tables that reference this integration function normally. `false` prevents users from creating new Iceberg tables that reference this integration. Existing Iceberg tables that reference this integration cannot access the catalog in the table definition.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// based tables, specifies the number of seconds to wait between attempts to poll your external cloud storage for new metadata.
	// Specifies the number of seconds to wait between attempts to poll the external Iceberg catalog for metadata updates for automated refresh. For Delta-based tables, specifies the number of seconds to wait between attempts to poll your external cloud storage for new metadata.
	// +kubebuilder:validation:Optional
	RefreshIntervalSeconds *int64 `json:"refreshIntervalSeconds,omitempty" tf:"refresh_interval_seconds,omitempty"`

	// insensitive): ICEBERG | DELTA.
	// Specifies the table format. Valid values are (case-insensitive): `ICEBERG` | `DELTA`.
	// +kubebuilder:validation:Optional
	TableFormat *string `json:"tableFormat,omitempty" tf:"table_format,omitempty"`
}

type CatalogIntegrationObjectStorageShowOutputInitParameters struct {
}

type CatalogIntegrationObjectStorageShowOutputObservation struct {

	// (String)
	Category *string `json:"category,omitempty" tf:"category,omitempty"`

	// (String) (Default: “) Specifies a comment for the catalog integration.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String)
	CreatedOn *string `json:"createdOn,omitempty" tf:"created_on,omitempty"`

	// (Boolean) Specifies whether the catalog integration is available for use for Iceberg tables. true allows users to create new Iceberg tables that reference this integration. Existing Iceberg tables that reference this integration function normally. false prevents users from creating new Iceberg tables that reference this integration. Existing Iceberg tables that reference this integration cannot access the catalog in the table definition.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Specifies the identifier (i.e. name) of the catalog integration; must be unique in your account.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type CatalogIntegrationObjectStorageShowOutputParameters struct {
}

// CatalogIntegrationObjectStorageSpec defines the desired state of CatalogIntegrationObjectStorage
type CatalogIntegrationObjectStorageSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   CatalogIntegrationObjectStorageParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CatalogIntegrationObjectStorageInitParameters `json:"initProvider,omitempty"`
}

// CatalogIntegrationObjectStorageStatus defines the observed state of CatalogIntegrationObjectStorage.
type CatalogIntegrationObjectStorageStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               CatalogIntegrationObjectStorageObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// CatalogIntegrationObjectStorage is the Schema for the CatalogIntegrationObjectStorages API. Resource used to manage catalog integration objects for Apache Iceberg™ table files or Delta table files in object storage. For more information, check catalog integration documentation https://docs.snowflake.com/en/sql-reference/sql/create-catalog-integration-object-storage.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,snowflake}
type CatalogIntegrationObjectStorage struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.enabled) || (has(self.initProvider) && has(self.initProvider.enabled))",message="spec.forProvider.enabled is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.tableFormat) || (has(self.initProvider) && has(self.initProvider.tableFormat))",message="spec.forProvider.tableFormat is a required parameter"
	Spec   CatalogIntegrationObjectStorageSpec   `json:"spec"`
	Status CatalogIntegrationObjectStorageStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CatalogIntegrationObjectStorageList contains a list of CatalogIntegrationObjectStorages
type CatalogIntegrationObjectStorageList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CatalogIntegrationObjectStorage `json:"items"`
}

// Repository type metadata.
var (
	CatalogIntegrationObjectStorage_Kind             = "CatalogIntegrationObjectStorage"
	CatalogIntegrationObjectStorage_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CatalogIntegrationObjectStorage_Kind}.String()
	CatalogIntegrationObjectStorage_KindAPIVersion   = CatalogIntegrationObjectStorage_Kind + "." + CRDGroupVersion.String()
	CatalogIntegrationObjectStorage_GroupVersionKind = CRDGroupVersion.WithKind(CatalogIntegrationObjectStorage_Kind)
)

func init() {
	SchemeBuilder.Register(&CatalogIntegrationObjectStorage{}, &CatalogIntegrationObjectStorageList{})
}
