// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Account) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AccountRole) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AccountSessionPolicyAttachment) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ApplicationRole) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Association) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AuthenticationIntegrationWithAuthorizationCodeGrant) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AuthenticationIntegrationWithClientCredentials) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AuthenticationIntegrationWithJwtBearer) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AuthenticationPolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Connection) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Database) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DatabaseRole) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Execute) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ExternalAzure) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ExternalGcs) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ExternalS3) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ExternalS3Compatible) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GrantAccountRole) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Integration) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *IntegrationAws) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *IntegrationAwsGlue) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *IntegrationAzure) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *IntegrationForCustomClients) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *IntegrationForPartnerApplications) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *IntegrationGcs) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *IntegrationIcebergRest) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *IntegrationObjectStorage) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *IntegrationOpenCatalog) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LegacyServiceUser) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Listing) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MaskingPolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Monitor) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OauthIntegration) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OnDirectoryTable) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OnExternalTable) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OnTable) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OnView) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OrganizationAccount) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Ownership) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Parameter) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PasswordPolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Policy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Pool) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PrivilegesToAccountRole) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PrivilegesToDatabaseRole) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PrivilegesToShare) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProgrammaticAccessToken) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Repository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Role) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RowAccessPolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Rule) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Schema) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SecondaryDatabase) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Service) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ServiceUser) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SessionPolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SessionPolicyAttachment) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SharedDatabase) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *StageInternal) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Streamlit) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Tag) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Task) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *User) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *View) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Volume) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Warehouse) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *WithAuthorizationCodeGrant) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *WithBasicAuthentication) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *WithClientCredentials) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *WithGenericString) Hub() {}
