// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type DescribeOutputBlockedRolesListInitParameters struct {
}

type DescribeOutputBlockedRolesListObservation struct {

	// (String)
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// (String) Specifies the name of the OAuth integration. This name follows the rules for Object Identifiers. The name should be unique among security integrations in your account. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type DescribeOutputBlockedRolesListParameters struct {
}

type DescribeOutputOauthAllowNonTLSRedirectURIInitParameters struct {
}

type DescribeOutputOauthAllowNonTLSRedirectURIObservation struct {

	// (String)
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// (String) Specifies the name of the OAuth integration. This name follows the rules for Object Identifiers. The name should be unique among security integrations in your account. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type DescribeOutputOauthAllowNonTLSRedirectURIParameters struct {
}

type DescribeOutputOauthAllowedAuthorizationEndpointsInitParameters struct {
}

type DescribeOutputOauthAllowedAuthorizationEndpointsObservation struct {

	// (String)
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// (String) Specifies the name of the OAuth integration. This name follows the rules for Object Identifiers. The name should be unique among security integrations in your account. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type DescribeOutputOauthAllowedAuthorizationEndpointsParameters struct {
}

type DescribeOutputOauthAllowedTokenEndpointsInitParameters struct {
}

type DescribeOutputOauthAllowedTokenEndpointsObservation struct {

	// (String)
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// (String) Specifies the name of the OAuth integration. This name follows the rules for Object Identifiers. The name should be unique among security integrations in your account. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type DescribeOutputOauthAllowedTokenEndpointsParameters struct {
}

type DescribeOutputOauthClientRsaPublicKey2FpInitParameters struct {
}

type DescribeOutputOauthClientRsaPublicKey2FpObservation struct {

	// (String)
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// (String) Specifies the name of the OAuth integration. This name follows the rules for Object Identifiers. The name should be unique among security integrations in your account. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type DescribeOutputOauthClientRsaPublicKey2FpParameters struct {
}

type DescribeOutputOauthClientRsaPublicKeyFpInitParameters struct {
}

type DescribeOutputOauthClientRsaPublicKeyFpObservation struct {

	// (String)
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// (String) Specifies the name of the OAuth integration. This name follows the rules for Object Identifiers. The name should be unique among security integrations in your account. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type DescribeOutputOauthClientRsaPublicKeyFpParameters struct {
}

type DescribeOutputOauthClientTypeInitParameters struct {
}

type DescribeOutputOauthClientTypeObservation struct {

	// (String)
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// (String) Specifies the name of the OAuth integration. This name follows the rules for Object Identifiers. The name should be unique among security integrations in your account. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type DescribeOutputOauthClientTypeParameters struct {
}

type DescribeOutputOauthEnforcePkceInitParameters struct {
}

type DescribeOutputOauthEnforcePkceObservation struct {

	// (String)
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// (String) Specifies the name of the OAuth integration. This name follows the rules for Object Identifiers. The name should be unique among security integrations in your account. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type DescribeOutputOauthEnforcePkceParameters struct {
}

type DescribeOutputOauthIssueRefreshTokensInitParameters struct {
}

type DescribeOutputOauthIssueRefreshTokensObservation struct {

	// (String)
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// (String) Specifies the name of the OAuth integration. This name follows the rules for Object Identifiers. The name should be unique among security integrations in your account. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type DescribeOutputOauthIssueRefreshTokensParameters struct {
}

type DescribeOutputOauthUseSecondaryRolesInitParameters struct {
}

type DescribeOutputOauthUseSecondaryRolesObservation struct {

	// (String)
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// (String) Specifies the name of the OAuth integration. This name follows the rules for Object Identifiers. The name should be unique among security integrations in your account. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type DescribeOutputOauthUseSecondaryRolesParameters struct {
}

type DescribeOutputPreAuthorizedRolesListInitParameters struct {
}

type DescribeOutputPreAuthorizedRolesListObservation struct {

	// (String)
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// (String) Specifies the name of the OAuth integration. This name follows the rules for Object Identifiers. The name should be unique among security integrations in your account. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type DescribeOutputPreAuthorizedRolesListParameters struct {
}

type IntegrationForPartnerApplicationsDescribeOutputCommentInitParameters struct {
}

type IntegrationForPartnerApplicationsDescribeOutputCommentObservation struct {

	// (String)
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// (String) Specifies the name of the OAuth integration. This name follows the rules for Object Identifiers. The name should be unique among security integrations in your account. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type IntegrationForPartnerApplicationsDescribeOutputCommentParameters struct {
}

type IntegrationForPartnerApplicationsDescribeOutputEnabledInitParameters struct {
}

type IntegrationForPartnerApplicationsDescribeOutputEnabledObservation struct {

	// (String)
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// (String) Specifies the name of the OAuth integration. This name follows the rules for Object Identifiers. The name should be unique among security integrations in your account. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type IntegrationForPartnerApplicationsDescribeOutputEnabledParameters struct {
}

type IntegrationForPartnerApplicationsDescribeOutputInitParameters struct {
}

type IntegrationForPartnerApplicationsDescribeOutputNetworkPolicyInitParameters struct {
}

type IntegrationForPartnerApplicationsDescribeOutputNetworkPolicyObservation struct {

	// (String)
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// (String) Specifies the name of the OAuth integration. This name follows the rules for Object Identifiers. The name should be unique among security integrations in your account. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type IntegrationForPartnerApplicationsDescribeOutputNetworkPolicyParameters struct {
}

type IntegrationForPartnerApplicationsDescribeOutputOauthAuthorizationEndpointInitParameters struct {
}

type IntegrationForPartnerApplicationsDescribeOutputOauthAuthorizationEndpointObservation struct {

	// (String)
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// (String) Specifies the name of the OAuth integration. This name follows the rules for Object Identifiers. The name should be unique among security integrations in your account. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type IntegrationForPartnerApplicationsDescribeOutputOauthAuthorizationEndpointParameters struct {
}

type IntegrationForPartnerApplicationsDescribeOutputOauthRefreshTokenValidityInitParameters struct {
}

type IntegrationForPartnerApplicationsDescribeOutputOauthRefreshTokenValidityObservation struct {

	// (String)
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// (String) Specifies the name of the OAuth integration. This name follows the rules for Object Identifiers. The name should be unique among security integrations in your account. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type IntegrationForPartnerApplicationsDescribeOutputOauthRefreshTokenValidityParameters struct {
}

type IntegrationForPartnerApplicationsDescribeOutputOauthTokenEndpointInitParameters struct {
}

type IntegrationForPartnerApplicationsDescribeOutputOauthTokenEndpointObservation struct {

	// (String)
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// (String) Specifies the name of the OAuth integration. This name follows the rules for Object Identifiers. The name should be unique among security integrations in your account. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type IntegrationForPartnerApplicationsDescribeOutputOauthTokenEndpointParameters struct {
}

type IntegrationForPartnerApplicationsDescribeOutputObservation struct {

	// (Set of String) A set of Snowflake roles that a user cannot explicitly consent to using after authenticating. By default, this list includes the ACCOUNTADMIN, ORGADMIN and SECURITYADMIN roles. To remove these privileged roles from the list, use the ALTER ACCOUNT command to set the OAUTH_ADD_PRIVILEGED_ROLES_TO_BLOCKED_LIST account parameter to FALSE. For more information about this resource, see docs.
	BlockedRolesList []DescribeOutputBlockedRolesListObservation `json:"blockedRolesList,omitempty" tf:"blocked_roles_list,omitempty"`

	// (String) Specifies a comment for the OAuth integration.
	Comment []IntegrationForPartnerApplicationsDescribeOutputCommentObservation `json:"comment,omitempty" tf:"comment,omitempty"`

	// uses special value that cannot be set in the configuration manually (default)) Specifies whether this OAuth integration is enabled or disabled. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	Enabled []IntegrationForPartnerApplicationsDescribeOutputEnabledObservation `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (List of Object) (see below for nested schema)
	NetworkPolicy []IntegrationForPartnerApplicationsDescribeOutputNetworkPolicyObservation `json:"networkPolicy,omitempty" tf:"network_policy,omitempty"`

	// (List of Object) (see below for nested schema)
	OauthAllowNonTLSRedirectURI []DescribeOutputOauthAllowNonTLSRedirectURIObservation `json:"oauthAllowNonTlsRedirectUri,omitempty" tf:"oauth_allow_non_tls_redirect_uri,omitempty"`

	// (List of Object) (see below for nested schema)
	OauthAllowedAuthorizationEndpoints []DescribeOutputOauthAllowedAuthorizationEndpointsObservation `json:"oauthAllowedAuthorizationEndpoints,omitempty" tf:"oauth_allowed_authorization_endpoints,omitempty"`

	// (List of Object) (see below for nested schema)
	OauthAllowedTokenEndpoints []DescribeOutputOauthAllowedTokenEndpointsObservation `json:"oauthAllowedTokenEndpoints,omitempty" tf:"oauth_allowed_token_endpoints,omitempty"`

	// (List of Object) (see below for nested schema)
	OauthAuthorizationEndpoint []IntegrationForPartnerApplicationsDescribeOutputOauthAuthorizationEndpointObservation `json:"oauthAuthorizationEndpoint,omitempty" tf:"oauth_authorization_endpoint,omitempty"`

	// (List of Object) (see below for nested schema)
	OauthClientRsaPublicKey2Fp []DescribeOutputOauthClientRsaPublicKey2FpObservation `json:"oauthClientRsaPublicKey2Fp,omitempty" tf:"oauth_client_rsa_public_key_2_fp,omitempty"`

	// (List of Object) (see below for nested schema)
	OauthClientRsaPublicKeyFp []DescribeOutputOauthClientRsaPublicKeyFpObservation `json:"oauthClientRsaPublicKeyFp,omitempty" tf:"oauth_client_rsa_public_key_fp,omitempty"`

	// (List of Object) (see below for nested schema)
	OauthClientType []DescribeOutputOauthClientTypeObservation `json:"oauthClientType,omitempty" tf:"oauth_client_type,omitempty"`

	// (List of Object) (see below for nested schema)
	OauthEnforcePkce []DescribeOutputOauthEnforcePkceObservation `json:"oauthEnforcePkce,omitempty" tf:"oauth_enforce_pkce,omitempty"`

	// uses special value that cannot be set in the configuration manually (default)) Specifies whether to allow the client to exchange a refresh token for an access token when the current access token has expired. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	OauthIssueRefreshTokens []DescribeOutputOauthIssueRefreshTokensObservation `json:"oauthIssueRefreshTokens,omitempty" tf:"oauth_issue_refresh_tokens,omitempty"`

	// uses special value that cannot be set in the configuration manually (-1)) Specifies how long refresh tokens should be valid (in seconds). OAUTH_ISSUE_REFRESH_TOKENS must be set to TRUE.
	OauthRefreshTokenValidity []IntegrationForPartnerApplicationsDescribeOutputOauthRefreshTokenValidityObservation `json:"oauthRefreshTokenValidity,omitempty" tf:"oauth_refresh_token_validity,omitempty"`

	// (List of Object) (see below for nested schema)
	OauthTokenEndpoint []IntegrationForPartnerApplicationsDescribeOutputOauthTokenEndpointObservation `json:"oauthTokenEndpoint,omitempty" tf:"oauth_token_endpoint,omitempty"`

	// (String) Specifies whether default secondary roles set in the user properties are activated by default in the session being opened. Valid options are: IMPLICIT | NONE.
	OauthUseSecondaryRoles []DescribeOutputOauthUseSecondaryRolesObservation `json:"oauthUseSecondaryRoles,omitempty" tf:"oauth_use_secondary_roles,omitempty"`

	// (List of Object) (see below for nested schema)
	PreAuthorizedRolesList []DescribeOutputPreAuthorizedRolesListObservation `json:"preAuthorizedRolesList,omitempty" tf:"pre_authorized_roles_list,omitempty"`
}

type IntegrationForPartnerApplicationsDescribeOutputParameters struct {
}

type IntegrationForPartnerApplicationsInitParameters struct {

	// (Set of String) A set of Snowflake roles that a user cannot explicitly consent to using after authenticating. By default, this list includes the ACCOUNTADMIN, ORGADMIN and SECURITYADMIN roles. To remove these privileged roles from the list, use the ALTER ACCOUNT command to set the OAUTH_ADD_PRIVILEGED_ROLES_TO_BLOCKED_LIST account parameter to FALSE. For more information about this resource, see docs.
	// A set of Snowflake roles that a user cannot explicitly consent to using after authenticating. By default, this list includes the ACCOUNTADMIN, ORGADMIN and SECURITYADMIN roles. To remove these privileged roles from the list, use the ALTER ACCOUNT command to set the OAUTH_ADD_PRIVILEGED_ROLES_TO_BLOCKED_LIST account parameter to FALSE. For more information about this resource, see [docs](./account_role).
	// +listType=set
	BlockedRolesList []*string `json:"blockedRolesList,omitempty" tf:"blocked_roles_list,omitempty"`

	// (String) Specifies a comment for the OAuth integration.
	// Specifies a comment for the OAuth integration.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// uses special value that cannot be set in the configuration manually (default)) Specifies whether this OAuth integration is enabled or disabled. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	// (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`default`)) Specifies whether this OAuth integration is enabled or disabled. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	Enabled *string `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Creates an OAuth interface between Snowflake and a partner application. Valid options are: LOOKER | TABLEAU_DESKTOP | TABLEAU_SERVER.
	// Creates an OAuth interface between Snowflake and a partner application. Valid options are: `LOOKER` | `TABLEAU_DESKTOP` | `TABLEAU_SERVER`.
	OauthClient *string `json:"oauthClient,omitempty" tf:"oauth_client,omitempty"`

	// uses special value that cannot be set in the configuration manually (default)) Specifies whether to allow the client to exchange a refresh token for an access token when the current access token has expired. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	// (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`default`)) Specifies whether to allow the client to exchange a refresh token for an access token when the current access token has expired. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	OauthIssueRefreshTokens *string `json:"oauthIssueRefreshTokens,omitempty" tf:"oauth_issue_refresh_tokens,omitempty"`

	// (String, Sensitive) Specifies the client URI. After a user is authenticated, the web browser is redirected to this URI. The field should be only set when OAUTH_CLIENT = LOOKER. In any other case the field should be left out empty.
	// Specifies the client URI. After a user is authenticated, the web browser is redirected to this URI. The field should be only set when OAUTH_CLIENT = LOOKER. In any other case the field should be left out empty.
	OauthRedirectURISecretRef *v1.SecretKeySelector `json:"oauthRedirectUriSecretRef,omitempty" tf:"-"`

	// uses special value that cannot be set in the configuration manually (-1)) Specifies how long refresh tokens should be valid (in seconds). OAUTH_ISSUE_REFRESH_TOKENS must be set to TRUE.
	// (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`-1`)) Specifies how long refresh tokens should be valid (in seconds). OAUTH_ISSUE_REFRESH_TOKENS must be set to TRUE.
	OauthRefreshTokenValidity *float64 `json:"oauthRefreshTokenValidity,omitempty" tf:"oauth_refresh_token_validity,omitempty"`

	// (String) Specifies whether default secondary roles set in the user properties are activated by default in the session being opened. Valid options are: IMPLICIT | NONE.
	// Specifies whether default secondary roles set in the user properties are activated by default in the session being opened. Valid options are: `IMPLICIT` | `NONE`.
	OauthUseSecondaryRoles *string `json:"oauthUseSecondaryRoles,omitempty" tf:"oauth_use_secondary_roles,omitempty"`
}

type IntegrationForPartnerApplicationsObservation struct {

	// (Set of String) A set of Snowflake roles that a user cannot explicitly consent to using after authenticating. By default, this list includes the ACCOUNTADMIN, ORGADMIN and SECURITYADMIN roles. To remove these privileged roles from the list, use the ALTER ACCOUNT command to set the OAUTH_ADD_PRIVILEGED_ROLES_TO_BLOCKED_LIST account parameter to FALSE. For more information about this resource, see docs.
	// A set of Snowflake roles that a user cannot explicitly consent to using after authenticating. By default, this list includes the ACCOUNTADMIN, ORGADMIN and SECURITYADMIN roles. To remove these privileged roles from the list, use the ALTER ACCOUNT command to set the OAUTH_ADD_PRIVILEGED_ROLES_TO_BLOCKED_LIST account parameter to FALSE. For more information about this resource, see [docs](./account_role).
	// +listType=set
	BlockedRolesList []*string `json:"blockedRolesList,omitempty" tf:"blocked_roles_list,omitempty"`

	// (String) Specifies a comment for the OAuth integration.
	// Specifies a comment for the OAuth integration.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (List of Object) Outputs the result of DESCRIBE SECURITY INTEGRATION for the given integration. (see below for nested schema)
	// Outputs the result of `DESCRIBE SECURITY INTEGRATION` for the given integration.
	DescribeOutput []IntegrationForPartnerApplicationsDescribeOutputObservation `json:"describeOutput,omitempty" tf:"describe_output,omitempty"`

	// uses special value that cannot be set in the configuration manually (default)) Specifies whether this OAuth integration is enabled or disabled. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	// (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`default`)) Specifies whether this OAuth integration is enabled or disabled. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	Enabled *string `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Fully qualified name of the resource. For more information, see object name resolution.
	// Fully qualified name of the resource. For more information, see [object name resolution](https://docs.snowflake.com/en/sql-reference/name-resolution).
	FullyQualifiedName *string `json:"fullyQualifiedName,omitempty" tf:"fully_qualified_name,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Creates an OAuth interface between Snowflake and a partner application. Valid options are: LOOKER | TABLEAU_DESKTOP | TABLEAU_SERVER.
	// Creates an OAuth interface between Snowflake and a partner application. Valid options are: `LOOKER` | `TABLEAU_DESKTOP` | `TABLEAU_SERVER`.
	OauthClient *string `json:"oauthClient,omitempty" tf:"oauth_client,omitempty"`

	// uses special value that cannot be set in the configuration manually (default)) Specifies whether to allow the client to exchange a refresh token for an access token when the current access token has expired. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	// (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`default`)) Specifies whether to allow the client to exchange a refresh token for an access token when the current access token has expired. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	OauthIssueRefreshTokens *string `json:"oauthIssueRefreshTokens,omitempty" tf:"oauth_issue_refresh_tokens,omitempty"`

	// uses special value that cannot be set in the configuration manually (-1)) Specifies how long refresh tokens should be valid (in seconds). OAUTH_ISSUE_REFRESH_TOKENS must be set to TRUE.
	// (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`-1`)) Specifies how long refresh tokens should be valid (in seconds). OAUTH_ISSUE_REFRESH_TOKENS must be set to TRUE.
	OauthRefreshTokenValidity *float64 `json:"oauthRefreshTokenValidity,omitempty" tf:"oauth_refresh_token_validity,omitempty"`

	// (String) Specifies whether default secondary roles set in the user properties are activated by default in the session being opened. Valid options are: IMPLICIT | NONE.
	// Specifies whether default secondary roles set in the user properties are activated by default in the session being opened. Valid options are: `IMPLICIT` | `NONE`.
	OauthUseSecondaryRoles *string `json:"oauthUseSecondaryRoles,omitempty" tf:"oauth_use_secondary_roles,omitempty"`

	// (List of Object) Parameters related to this security integration. (see below for nested schema)
	// Parameters related to this security integration.
	RelatedParameters []IntegrationForPartnerApplicationsRelatedParametersObservation `json:"relatedParameters,omitempty" tf:"related_parameters,omitempty"`

	// (List of Object) Outputs the result of SHOW SECURITY INTEGRATION for the given integration. (see below for nested schema)
	// Outputs the result of `SHOW SECURITY INTEGRATION` for the given integration.
	ShowOutput []IntegrationForPartnerApplicationsShowOutputObservation `json:"showOutput,omitempty" tf:"show_output,omitempty"`
}

type IntegrationForPartnerApplicationsParameters struct {

	// (Set of String) A set of Snowflake roles that a user cannot explicitly consent to using after authenticating. By default, this list includes the ACCOUNTADMIN, ORGADMIN and SECURITYADMIN roles. To remove these privileged roles from the list, use the ALTER ACCOUNT command to set the OAUTH_ADD_PRIVILEGED_ROLES_TO_BLOCKED_LIST account parameter to FALSE. For more information about this resource, see docs.
	// A set of Snowflake roles that a user cannot explicitly consent to using after authenticating. By default, this list includes the ACCOUNTADMIN, ORGADMIN and SECURITYADMIN roles. To remove these privileged roles from the list, use the ALTER ACCOUNT command to set the OAUTH_ADD_PRIVILEGED_ROLES_TO_BLOCKED_LIST account parameter to FALSE. For more information about this resource, see [docs](./account_role).
	// +kubebuilder:validation:Optional
	// +listType=set
	BlockedRolesList []*string `json:"blockedRolesList,omitempty" tf:"blocked_roles_list,omitempty"`

	// (String) Specifies a comment for the OAuth integration.
	// Specifies a comment for the OAuth integration.
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// uses special value that cannot be set in the configuration manually (default)) Specifies whether this OAuth integration is enabled or disabled. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	// (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`default`)) Specifies whether this OAuth integration is enabled or disabled. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	// +kubebuilder:validation:Optional
	Enabled *string `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Creates an OAuth interface between Snowflake and a partner application. Valid options are: LOOKER | TABLEAU_DESKTOP | TABLEAU_SERVER.
	// Creates an OAuth interface between Snowflake and a partner application. Valid options are: `LOOKER` | `TABLEAU_DESKTOP` | `TABLEAU_SERVER`.
	// +kubebuilder:validation:Optional
	OauthClient *string `json:"oauthClient,omitempty" tf:"oauth_client,omitempty"`

	// uses special value that cannot be set in the configuration manually (default)) Specifies whether to allow the client to exchange a refresh token for an access token when the current access token has expired. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	// (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`default`)) Specifies whether to allow the client to exchange a refresh token for an access token when the current access token has expired. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	// +kubebuilder:validation:Optional
	OauthIssueRefreshTokens *string `json:"oauthIssueRefreshTokens,omitempty" tf:"oauth_issue_refresh_tokens,omitempty"`

	// (String, Sensitive) Specifies the client URI. After a user is authenticated, the web browser is redirected to this URI. The field should be only set when OAUTH_CLIENT = LOOKER. In any other case the field should be left out empty.
	// Specifies the client URI. After a user is authenticated, the web browser is redirected to this URI. The field should be only set when OAUTH_CLIENT = LOOKER. In any other case the field should be left out empty.
	// +kubebuilder:validation:Optional
	OauthRedirectURISecretRef *v1.SecretKeySelector `json:"oauthRedirectUriSecretRef,omitempty" tf:"-"`

	// uses special value that cannot be set in the configuration manually (-1)) Specifies how long refresh tokens should be valid (in seconds). OAUTH_ISSUE_REFRESH_TOKENS must be set to TRUE.
	// (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`-1`)) Specifies how long refresh tokens should be valid (in seconds). OAUTH_ISSUE_REFRESH_TOKENS must be set to TRUE.
	// +kubebuilder:validation:Optional
	OauthRefreshTokenValidity *float64 `json:"oauthRefreshTokenValidity,omitempty" tf:"oauth_refresh_token_validity,omitempty"`

	// (String) Specifies whether default secondary roles set in the user properties are activated by default in the session being opened. Valid options are: IMPLICIT | NONE.
	// Specifies whether default secondary roles set in the user properties are activated by default in the session being opened. Valid options are: `IMPLICIT` | `NONE`.
	// +kubebuilder:validation:Optional
	OauthUseSecondaryRoles *string `json:"oauthUseSecondaryRoles,omitempty" tf:"oauth_use_secondary_roles,omitempty"`
}

type IntegrationForPartnerApplicationsRelatedParametersInitParameters struct {
}

type IntegrationForPartnerApplicationsRelatedParametersObservation struct {

	// (List of Object) (see below for nested schema)
	OauthAddPrivilegedRolesToBlockedList []RelatedParametersOauthAddPrivilegedRolesToBlockedListObservation `json:"oauthAddPrivilegedRolesToBlockedList,omitempty" tf:"oauth_add_privileged_roles_to_blocked_list,omitempty"`
}

type IntegrationForPartnerApplicationsRelatedParametersParameters struct {
}

type IntegrationForPartnerApplicationsShowOutputInitParameters struct {
}

type IntegrationForPartnerApplicationsShowOutputObservation struct {

	// (String)
	Category *string `json:"category,omitempty" tf:"category,omitempty"`

	// (String) Specifies a comment for the OAuth integration.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String)
	CreatedOn *string `json:"createdOn,omitempty" tf:"created_on,omitempty"`

	// uses special value that cannot be set in the configuration manually (default)) Specifies whether this OAuth integration is enabled or disabled. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String)
	IntegrationType *string `json:"integrationType,omitempty" tf:"integration_type,omitempty"`

	// (String) Specifies the name of the OAuth integration. This name follows the rules for Object Identifiers. The name should be unique among security integrations in your account. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type IntegrationForPartnerApplicationsShowOutputParameters struct {
}

type RelatedParametersOauthAddPrivilegedRolesToBlockedListInitParameters struct {
}

type RelatedParametersOauthAddPrivilegedRolesToBlockedListObservation struct {

	// (String)
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String)
	Level *string `json:"level,omitempty" tf:"level,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type RelatedParametersOauthAddPrivilegedRolesToBlockedListParameters struct {
}

// IntegrationForPartnerApplicationsSpec defines the desired state of IntegrationForPartnerApplications
type IntegrationForPartnerApplicationsSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     IntegrationForPartnerApplicationsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider IntegrationForPartnerApplicationsInitParameters `json:"initProvider,omitempty"`
}

// IntegrationForPartnerApplicationsStatus defines the observed state of IntegrationForPartnerApplications.
type IntegrationForPartnerApplicationsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        IntegrationForPartnerApplicationsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// IntegrationForPartnerApplications is the Schema for the IntegrationForPartnerApplicationss API. Resource used to manage oauth security integration for partner applications objects. For more information, check security integrations documentation https://docs.snowflake.com/en/sql-reference/sql/create-security-integration-oauth-snowflake.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,snowflake}
type IntegrationForPartnerApplications struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.oauthClient) || (has(self.initProvider) && has(self.initProvider.oauthClient))",message="spec.forProvider.oauthClient is a required parameter"
	Spec   IntegrationForPartnerApplicationsSpec   `json:"spec"`
	Status IntegrationForPartnerApplicationsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// IntegrationForPartnerApplicationsList contains a list of IntegrationForPartnerApplicationss
type IntegrationForPartnerApplicationsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []IntegrationForPartnerApplications `json:"items"`
}

// Repository type metadata.
var (
	IntegrationForPartnerApplications_Kind             = "IntegrationForPartnerApplications"
	IntegrationForPartnerApplications_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: IntegrationForPartnerApplications_Kind}.String()
	IntegrationForPartnerApplications_KindAPIVersion   = IntegrationForPartnerApplications_Kind + "." + CRDGroupVersion.String()
	IntegrationForPartnerApplications_GroupVersionKind = CRDGroupVersion.WithKind(IntegrationForPartnerApplications_Kind)
)

func init() {
	SchemeBuilder.Register(&IntegrationForPartnerApplications{}, &IntegrationForPartnerApplicationsList{})
}
