// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type StorageIntegrationAwsDescribeOutputInitParameters struct {
}

type StorageIntegrationAwsDescribeOutputObservation struct {

	// (List of String)
	AllowedLocations []*string `json:"allowedLocations,omitempty" tf:"allowed_locations,omitempty"`

	// (List of String)
	BlockedLocations []*string `json:"blockedLocations,omitempty" tf:"blocked_locations,omitempty"`

	// (String) Specifies a comment for the storage integration.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean) Specifies whether this storage integration is available for usage in stages. TRUE allows users to create new stages that reference this integration. Existing stages that reference this integration function normally. FALSE prevents users from creating new stages that reference this integration. Existing stages that reference this integration cannot access the storage location in the stage definition.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String)
	ExternalID *string `json:"externalId,omitempty" tf:"external_id,omitempty"`

	// (String)
	IAMUserArn *string `json:"iamUserArn,omitempty" tf:"iam_user_arn,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	ObjectACL *string `json:"objectAcl,omitempty" tf:"object_acl,omitempty"`

	// (String)
	Provider *string `json:"provider,omitempty" tf:"provider,omitempty"`

	// (String)
	RoleArn *string `json:"roleArn,omitempty" tf:"role_arn,omitempty"`

	// uses special value that cannot be set in the configuration manually (default)) Specifies whether to use outbound private connectivity to harden the security posture. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	UsePrivatelinkEndpoint *bool `json:"usePrivatelinkEndpoint,omitempty" tf:"use_privatelink_endpoint,omitempty"`
}

type StorageIntegrationAwsDescribeOutputParameters struct {
}

type StorageIntegrationAwsInitParameters struct {

	// (String) Specifies a comment for the storage integration.
	// Specifies a comment for the storage integration.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean) Specifies whether this storage integration is available for usage in stages. TRUE allows users to create new stages that reference this integration. Existing stages that reference this integration function normally. FALSE prevents users from creating new stages that reference this integration. Existing stages that reference this integration cannot access the storage location in the stage definition.
	// Specifies whether this storage integration is available for usage in stages. `TRUE` allows users to create new stages that reference this integration. Existing stages that reference this integration function normally. `FALSE` prevents users from creating new stages that reference this integration. Existing stages that reference this integration cannot access the storage location in the stage definition.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Set of String) Explicitly limits external stages that use the integration to reference one or more storage locations.
	// Explicitly limits external stages that use the integration to reference one or more storage locations.
	// +listType=set
	StorageAllowedLocations []*string `json:"storageAllowedLocations,omitempty" tf:"storage_allowed_locations,omitempty"`

	// (String) Optionally specifies an external ID that Snowflake uses to establish a trust relationship with AWS.
	// Optionally specifies an external ID that Snowflake uses to establish a trust relationship with AWS.
	StorageAwsExternalID *string `json:"storageAwsExternalId,omitempty" tf:"storage_aws_external_id,omitempty"`

	// owner-full-control is the only currently supported value.
	// Enables support for AWS access control lists (ACLs) to grant the bucket owner full control. `bucket-owner-full-control` is the only currently supported value.
	StorageAwsObjectACL *string `json:"storageAwsObjectAcl,omitempty" tf:"storage_aws_object_acl,omitempty"`

	// (String) Specifies the Amazon Resource Name (ARN) of the AWS identity and access management (IAM) role that grants privileges on the S3 bucket containing your data files.
	// Specifies the Amazon Resource Name (ARN) of the AWS identity and access management (IAM) role that grants privileges on the S3 bucket containing your data files.
	StorageAwsRoleArn *string `json:"storageAwsRoleArn,omitempty" tf:"storage_aws_role_arn,omitempty"`

	// (Set of String) Explicitly prohibits external stages that use the integration from referencing one or more storage locations.
	// Explicitly prohibits external stages that use the integration from referencing one or more storage locations.
	// +listType=set
	StorageBlockedLocations []*string `json:"storageBlockedLocations,omitempty" tf:"storage_blocked_locations,omitempty"`

	// (String) Specifies the storage provider for the integration. Valid options are: S3 | S3GOV | S3CHINA | GCS | AZURE
	// Specifies the storage provider for the integration. Valid options are: `S3` | `S3GOV` | `S3CHINA` | `GCS` | `AZURE`
	StorageProvider *string `json:"storageProvider,omitempty" tf:"storage_provider,omitempty"`

	// uses special value that cannot be set in the configuration manually (default)) Specifies whether to use outbound private connectivity to harden the security posture. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	// (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`default`)) Specifies whether to use outbound private connectivity to harden the security posture. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	UsePrivatelinkEndpoint *string `json:"usePrivatelinkEndpoint,omitempty" tf:"use_privatelink_endpoint,omitempty"`
}

type StorageIntegrationAwsObservation struct {

	// (String) Specifies a comment for the storage integration.
	// Specifies a comment for the storage integration.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (List of Object) Outputs the result of DESCRIBE STORAGE INTEGRATION for the given storage integration. (see below for nested schema)
	// Outputs the result of `DESCRIBE STORAGE INTEGRATION` for the given storage integration.
	DescribeOutput []StorageIntegrationAwsDescribeOutputObservation `json:"describeOutput,omitempty" tf:"describe_output,omitempty"`

	// (Boolean) Specifies whether this storage integration is available for usage in stages. TRUE allows users to create new stages that reference this integration. Existing stages that reference this integration function normally. FALSE prevents users from creating new stages that reference this integration. Existing stages that reference this integration cannot access the storage location in the stage definition.
	// Specifies whether this storage integration is available for usage in stages. `TRUE` allows users to create new stages that reference this integration. Existing stages that reference this integration function normally. `FALSE` prevents users from creating new stages that reference this integration. Existing stages that reference this integration cannot access the storage location in the stage definition.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Fully qualified name of the resource. For more information, see object name resolution.
	// Fully qualified name of the resource. For more information, see [object name resolution](https://docs.snowflake.com/en/sql-reference/name-resolution).
	FullyQualifiedName *string `json:"fullyQualifiedName,omitempty" tf:"fully_qualified_name,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (List of Object) Outputs the result of SHOW STORAGE INTEGRATIONS for the given storage integration. (see below for nested schema)
	// Outputs the result of `SHOW STORAGE INTEGRATIONS` for the given storage integration.
	ShowOutput []StorageIntegrationAwsShowOutputObservation `json:"showOutput,omitempty" tf:"show_output,omitempty"`

	// (Set of String) Explicitly limits external stages that use the integration to reference one or more storage locations.
	// Explicitly limits external stages that use the integration to reference one or more storage locations.
	// +listType=set
	StorageAllowedLocations []*string `json:"storageAllowedLocations,omitempty" tf:"storage_allowed_locations,omitempty"`

	// (String) Optionally specifies an external ID that Snowflake uses to establish a trust relationship with AWS.
	// Optionally specifies an external ID that Snowflake uses to establish a trust relationship with AWS.
	StorageAwsExternalID *string `json:"storageAwsExternalId,omitempty" tf:"storage_aws_external_id,omitempty"`

	// owner-full-control is the only currently supported value.
	// Enables support for AWS access control lists (ACLs) to grant the bucket owner full control. `bucket-owner-full-control` is the only currently supported value.
	StorageAwsObjectACL *string `json:"storageAwsObjectAcl,omitempty" tf:"storage_aws_object_acl,omitempty"`

	// (String) Specifies the Amazon Resource Name (ARN) of the AWS identity and access management (IAM) role that grants privileges on the S3 bucket containing your data files.
	// Specifies the Amazon Resource Name (ARN) of the AWS identity and access management (IAM) role that grants privileges on the S3 bucket containing your data files.
	StorageAwsRoleArn *string `json:"storageAwsRoleArn,omitempty" tf:"storage_aws_role_arn,omitempty"`

	// (Set of String) Explicitly prohibits external stages that use the integration from referencing one or more storage locations.
	// Explicitly prohibits external stages that use the integration from referencing one or more storage locations.
	// +listType=set
	StorageBlockedLocations []*string `json:"storageBlockedLocations,omitempty" tf:"storage_blocked_locations,omitempty"`

	// (String) Specifies the storage provider for the integration. Valid options are: S3 | S3GOV | S3CHINA | GCS | AZURE
	// Specifies the storage provider for the integration. Valid options are: `S3` | `S3GOV` | `S3CHINA` | `GCS` | `AZURE`
	StorageProvider *string `json:"storageProvider,omitempty" tf:"storage_provider,omitempty"`

	// uses special value that cannot be set in the configuration manually (default)) Specifies whether to use outbound private connectivity to harden the security posture. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	// (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`default`)) Specifies whether to use outbound private connectivity to harden the security posture. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	UsePrivatelinkEndpoint *string `json:"usePrivatelinkEndpoint,omitempty" tf:"use_privatelink_endpoint,omitempty"`
}

type StorageIntegrationAwsParameters struct {

	// (String) Specifies a comment for the storage integration.
	// Specifies a comment for the storage integration.
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean) Specifies whether this storage integration is available for usage in stages. TRUE allows users to create new stages that reference this integration. Existing stages that reference this integration function normally. FALSE prevents users from creating new stages that reference this integration. Existing stages that reference this integration cannot access the storage location in the stage definition.
	// Specifies whether this storage integration is available for usage in stages. `TRUE` allows users to create new stages that reference this integration. Existing stages that reference this integration function normally. `FALSE` prevents users from creating new stages that reference this integration. Existing stages that reference this integration cannot access the storage location in the stage definition.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Set of String) Explicitly limits external stages that use the integration to reference one or more storage locations.
	// Explicitly limits external stages that use the integration to reference one or more storage locations.
	// +kubebuilder:validation:Optional
	// +listType=set
	StorageAllowedLocations []*string `json:"storageAllowedLocations,omitempty" tf:"storage_allowed_locations,omitempty"`

	// (String) Optionally specifies an external ID that Snowflake uses to establish a trust relationship with AWS.
	// Optionally specifies an external ID that Snowflake uses to establish a trust relationship with AWS.
	// +kubebuilder:validation:Optional
	StorageAwsExternalID *string `json:"storageAwsExternalId,omitempty" tf:"storage_aws_external_id,omitempty"`

	// owner-full-control is the only currently supported value.
	// Enables support for AWS access control lists (ACLs) to grant the bucket owner full control. `bucket-owner-full-control` is the only currently supported value.
	// +kubebuilder:validation:Optional
	StorageAwsObjectACL *string `json:"storageAwsObjectAcl,omitempty" tf:"storage_aws_object_acl,omitempty"`

	// (String) Specifies the Amazon Resource Name (ARN) of the AWS identity and access management (IAM) role that grants privileges on the S3 bucket containing your data files.
	// Specifies the Amazon Resource Name (ARN) of the AWS identity and access management (IAM) role that grants privileges on the S3 bucket containing your data files.
	// +kubebuilder:validation:Optional
	StorageAwsRoleArn *string `json:"storageAwsRoleArn,omitempty" tf:"storage_aws_role_arn,omitempty"`

	// (Set of String) Explicitly prohibits external stages that use the integration from referencing one or more storage locations.
	// Explicitly prohibits external stages that use the integration from referencing one or more storage locations.
	// +kubebuilder:validation:Optional
	// +listType=set
	StorageBlockedLocations []*string `json:"storageBlockedLocations,omitempty" tf:"storage_blocked_locations,omitempty"`

	// (String) Specifies the storage provider for the integration. Valid options are: S3 | S3GOV | S3CHINA | GCS | AZURE
	// Specifies the storage provider for the integration. Valid options are: `S3` | `S3GOV` | `S3CHINA` | `GCS` | `AZURE`
	// +kubebuilder:validation:Optional
	StorageProvider *string `json:"storageProvider,omitempty" tf:"storage_provider,omitempty"`

	// uses special value that cannot be set in the configuration manually (default)) Specifies whether to use outbound private connectivity to harden the security posture. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	// (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`default`)) Specifies whether to use outbound private connectivity to harden the security posture. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	// +kubebuilder:validation:Optional
	UsePrivatelinkEndpoint *string `json:"usePrivatelinkEndpoint,omitempty" tf:"use_privatelink_endpoint,omitempty"`
}

type StorageIntegrationAwsShowOutputInitParameters struct {
}

type StorageIntegrationAwsShowOutputObservation struct {

	// (String)
	Category *string `json:"category,omitempty" tf:"category,omitempty"`

	// (String) Specifies a comment for the storage integration.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String)
	CreatedOn *string `json:"createdOn,omitempty" tf:"created_on,omitempty"`

	// (Boolean) Specifies whether this storage integration is available for usage in stages. TRUE allows users to create new stages that reference this integration. Existing stages that reference this integration function normally. FALSE prevents users from creating new stages that reference this integration. Existing stages that reference this integration cannot access the storage location in the stage definition.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) String that specifies the identifier (i.e. name) for the integration; must be unique in your account. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	StorageType *string `json:"storageType,omitempty" tf:"storage_type,omitempty"`
}

type StorageIntegrationAwsShowOutputParameters struct {
}

// StorageIntegrationAwsSpec defines the desired state of StorageIntegrationAws
type StorageIntegrationAwsSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     StorageIntegrationAwsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider StorageIntegrationAwsInitParameters `json:"initProvider,omitempty"`
}

// StorageIntegrationAwsStatus defines the observed state of StorageIntegrationAws.
type StorageIntegrationAwsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        StorageIntegrationAwsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// StorageIntegrationAws is the Schema for the StorageIntegrationAwss API. Resource used to manage AWS storage integration objects. For more information, check storage integration documentation https://docs.snowflake.com/en/sql-reference/sql/create-storage-integration.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,snowflake}
type StorageIntegrationAws struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.enabled) || (has(self.initProvider) && has(self.initProvider.enabled))",message="spec.forProvider.enabled is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.storageAllowedLocations) || (has(self.initProvider) && has(self.initProvider.storageAllowedLocations))",message="spec.forProvider.storageAllowedLocations is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.storageAwsRoleArn) || (has(self.initProvider) && has(self.initProvider.storageAwsRoleArn))",message="spec.forProvider.storageAwsRoleArn is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.storageProvider) || (has(self.initProvider) && has(self.initProvider.storageProvider))",message="spec.forProvider.storageProvider is a required parameter"
	Spec   StorageIntegrationAwsSpec   `json:"spec"`
	Status StorageIntegrationAwsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// StorageIntegrationAwsList contains a list of StorageIntegrationAwss
type StorageIntegrationAwsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []StorageIntegrationAws `json:"items"`
}

// Repository type metadata.
var (
	StorageIntegrationAws_Kind             = "StorageIntegrationAws"
	StorageIntegrationAws_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: StorageIntegrationAws_Kind}.String()
	StorageIntegrationAws_KindAPIVersion   = StorageIntegrationAws_Kind + "." + CRDGroupVersion.String()
	StorageIntegrationAws_GroupVersionKind = CRDGroupVersion.WithKind(StorageIntegrationAws_Kind)
)

func init() {
	SchemeBuilder.Register(&StorageIntegrationAws{}, &StorageIntegrationAwsList{})
}
